{
	"alias": "FEDORA-2019-333a7aa511",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1652459,
			"feedback": [
				{
					"bug_id": 1652459,
					"comment": {
						"id": 867878,
						"karma": 1,
						"karma_critpath": 1,
						"text": "works as expected",
						"timestamp": "2018-11-28 09:45:32",
						"update_id": 127472,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5ed589dd93c3ff16e0ea2fc0f186dc1f2de667f3d60c0e168cb18fbaf3455286?s=24&d=retro",
							"email": "lnie@redhat.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								}
							],
							"id": 307,
							"name": "lnie",
							"openid": "lnie.id.fedoraproject.org"
						},
						"user_id": 307
					},
					"comment_id": 867878
				},
				{
					"bug_id": 1652459,
					"comment": {
						"id": 888842,
						"text": "How is that a security related bug? I dont see how an attacker can use this flaw. Is a CVE requested for this bug?",
						"timestamp": "2019-01-28 10:31:40",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ffa4b7625be5eced4d6d3ea49cd8c8f60d0c6bd502ed5eb97e52e63f15583009?s=24&d=retro",
							"id": 207,
							"name": "anonymous",
							"openid": "anonymous.id.fedoraproject.org"
						},
						"user_id": 207
					},
					"comment_id": 888842
				},
				{
					"bug_id": 1652459,
					"comment": {
						"id": 888843,
						"text": "https://bugzilla.redhat.com/show_bug.cgi?id=1669298#c1",
						"timestamp": "2019-01-28 10:38:36",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/a697e3056324536b5c3c5f17c44da8c0e9d10cf6e9086c74e2be77536ff9cc94?s=24&d=retro",
							"email": "pavel@zhukoff.net",
							"groups": [
								{
									"name": "packager"
								}
							],
							"id": 1165,
							"name": "landgraf",
							"openid": "landgraf.id.fedoraproject.org"
						},
						"user_id": 1165
					},
					"comment_id": 888843
				}
			],
			"title": "vlan interface doesn't exists once network target reached",
			"bugzilla": {
				"bug_id": "1652459",
				"creation_ts": "2018-11-22 07:27:18 +0000",
				"short_desc": "vlan interface doesn't exists once network target reached",
				"delta_ts": "2019-02-12 01:26:10 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"priority": "medium",
				"bug_severity": "urgent",
				"blocked": [
					{
						"bug_id": "1653658",
						"creation_ts": "2018-11-27 11:19:37 +0000",
						"short_desc": "vlan interface doesn't exists once network target reached",
						"delta_ts": "2019-06-14 01:14:17 +0000",
						"bug_status": "CLOSED",
						"resolution": "CURRENTRELEASE",
						"keywords": "EasyFix, Patch",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1652459"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12239933",
								"comment_count": "0",
								"who": {
									"text": "pzhukov",
									"name": "Pavel Zhukov"
								},
								"bug_when": "2018-11-27 11:19:37 +0000",
								"thetext": "+++ This bug was initially created as a clone of Bug #1652459 +++\n\nDescription of problem:\nWhen configured to serve VLAN interfaces, the radvd unit fails to start at boot.\n\n\nVersion-Release number of selected component (if applicable):\nradvd-2.17-10.fc28.x86_64\n\nHow reproducible:\nEvery time.\n\nSteps to Reproduce:\n1. Configure radvd to advertise on VLAN interfaces.\n2. Reboot.\n3. Watch radvd fail to start.\n\nActual results:\nFailed unit startup.\n\nExpected results:\nRunning radvd.service unit.\n\nAdditional info:\n\n--- Additional comment from Ben Herrick on 2018-11-22 02:28:54 EST ---\n\nFrom journalctl:\n\nNov 18 14:55:30 xxxx radvd[1191]: version 2.17 started\nNov 18 14:55:30 xxxx radvd[1191]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 18 14:55:30 xxxx radvd[1191]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 18 14:55:30 xxxx radvd[1194]: enp2s0.254 not found: No such device\n\n--- Additional comment from Pavel Zhukov on 2018-11-22 06:05:46 EST ---\n\nHello,\n\nThank you for the bug report.\nIt's weird nobody was noticed before. The fix is simple one line patch. I'll submit it upstream\n\n--- Additional comment from Pavel Zhukov on 2018-11-26 10:06:45 EST ---\n\nit's weird I've checked version in rawhide and it works fine. \n\n#without vlan device:\n\nNov 26 16:02:45 pzhukov-x240.example.com systemd[1]: Starting Router advertisement daemon for IPv6...\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: version 2.17 started\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 26 16:02:45 pzhukov-x240.example.com systemd[1]: Started Router advertisement daemon for IPv6.\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10088]: enp0s25.100 not found: No such device\n\n\n# sudo ip link add link enp0s25 name enp0s25.100 type vlan id 100\n\n# with vlan device\n-- Logs begin at Mon 2018-11-19 10:50:53 CET, end at Mon 2018-11-26 15:57:22 CET. --\nNov 26 15:57:14 pzhukov-x240.example.com systemd[1]: Starting Router advertisement daemon for IPv6...\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: version 2.17 started\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 26 15:57:14 pzhukov-x240.example.com systemd[1]: Started Router advertisement daemon for IPv6.\n\n\n# radvd.conf\ninterface enp0s25.100\n{\n// omitted\n\n};\n\nThere were not too many changes between f28 and rawhide\nCan you please double check your config? \n\n\n+* Wed Jun 13 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-14\n+- Log to stderr in non-daemon mode\n+- Add nodaemon option into manpage\n+- Re-enable test again\n+\n+* Mon Jun 04 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-12\n+- Enable tests and fix them on big endian arches\n+\n+* Thu Apr 12 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-11\n+- Enable Werror=all\n\n--- Additional comment from Ben Herrick on 2018-11-26 22:16:18 EST ---\n\nTry adding the VLAN interface using nmcli and then reboot.\n\nThe problem does not occur when starting radvd after the system is booted, but radvd will fail because the VLAN interfaces are started _AFTER_ radvd.\n\n--- Additional comment from Ben Herrick on 2018-11-26 22:19:54 EST ---\n\nTo be clear, you have to add the VLAN interface permanently in nmcli, also add the configuration for the prefix/interface in /etc/radvd.conf and then reboot in order to observe the behavior.\n\n--- Additional comment from Pavel Zhukov on 2018-11-27 02:52:42 EST ---\n\n(In reply to Ben Herrick from comment #4)\n> Try adding the VLAN interface using nmcli and then reboot.\n> \n> The problem does not occur when starting radvd after the system is booted,\n> but radvd will fail because the VLAN interfaces are started _AFTER_ radvd.\n\nIt's different problem and seems like radvd has nothing to do with it but NM brings vlan interface up too late.\n\n[Unit]\nDescription=Router advertisement daemon for IPv6\nAfter=network.target\n\n--- Additional comment from Beniamino Galvani on 2018-11-27 03:27:20 EST ---\n\nIf radvd needs that all connection profiles are activated when it's started, it should depend on the network-online.target in this way:\n\n After=network-online.target\n Wants=network-online.target\n\nso that it is delayed until NetworkManager has completed the initialization. The NetworkManager-wait-online.service should be active as well.\n\n--- Additional comment from Pavel Zhukov on 2018-11-27 03:50:47 EST ---\n\n(In reply to Beniamino Galvani from comment #7)\n> If radvd needs that all connection profiles are activated when it's started,\n> it should depend on the network-online.target in this way:\n> \n>  After=network-online.target\n>  Wants=network-online.target\n> \n> so that it is delayed until NetworkManager has completed the initialization.\n> The NetworkManager-wait-online.service should be active as well.\n\nOk. Thanks. Moving back then.\nSorry for the noise\n\n--- Additional comment from Pavel Zhukov on 2018-11-27 03:51:08 EST ---\n\n(In reply to Beniamino Galvani from comment #7)\n> If radvd needs that all connection profiles are activated when it's started,\n> it should depend on the network-online.target in this way:\n> \n>  After=network-online.target\n>  Wants=network-online.target\n> \n> so that it is delayed until NetworkManager has completed the initialization.\n> The NetworkManager-wait-online.service should be active as well.\n\nOk. Thanks. Moving back then.\nSorry for the noise\n\n--- Additional comment from Fedora Update System on 2018-11-27 06:15:55 EST ---\n\nradvd-2.17-11.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-3222e7c914\n\n--- Additional comment from Fedora Update System on 2018-11-27 06:16:37 EST ---\n\nradvd-2.17-16.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-b333ac9645"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12228989",
						"comment_count": "0",
						"who": {
							"text": "intrep",
							"name": "Ben Herrick"
						},
						"bug_when": "2018-11-22 07:27:18 +0000",
						"thetext": "Description of problem:\nWhen configured to serve VLAN interfaces, the radvd unit fails to start at boot.\n\n\nVersion-Release number of selected component (if applicable):\nradvd-2.17-10.fc28.x86_64\n\nHow reproducible:\nEvery time.\n\nSteps to Reproduce:\n1. Configure radvd to advertise on VLAN interfaces.\n2. Reboot.\n3. Watch radvd fail to start.\n\nActual results:\nFailed unit startup.\n\nExpected results:\nRunning radvd.service unit.\n\nAdditional info:"
					},
					{
						"isprivate": "0",
						"commentid": "12228992",
						"comment_count": "1",
						"who": {
							"text": "intrep",
							"name": "Ben Herrick"
						},
						"bug_when": "2018-11-22 07:28:54 +0000",
						"thetext": "From journalctl:\n\nNov 18 14:55:30 xxxx radvd[1191]: version 2.17 started\nNov 18 14:55:30 xxxx radvd[1191]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 18 14:55:30 xxxx radvd[1191]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 18 14:55:30 xxxx radvd[1194]: enp2s0.254 not found: No such device"
					},
					{
						"isprivate": "0",
						"commentid": "12229495",
						"comment_count": "2",
						"who": {
							"text": "pzhukov",
							"name": "Pavel Zhukov"
						},
						"bug_when": "2018-11-22 11:05:46 +0000",
						"thetext": "Hello,\n\nThank you for the bug report.\nIt's weird nobody was noticed before. The fix is simple one line patch. I'll submit it upstream"
					},
					{
						"isprivate": "0",
						"commentid": "12235830",
						"comment_count": "3",
						"who": {
							"text": "pzhukov",
							"name": "Pavel Zhukov"
						},
						"bug_when": "2018-11-26 15:06:45 +0000",
						"thetext": "it's weird I've checked version in rawhide and it works fine. \n\n#without vlan device:\n\nNov 26 16:02:45 pzhukov-x240.example.com systemd[1]: Starting Router advertisement daemon for IPv6...\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: version 2.17 started\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10087]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 26 16:02:45 pzhukov-x240.example.com systemd[1]: Started Router advertisement daemon for IPv6.\nNov 26 16:02:45 pzhukov-x240.example.com radvd[10088]: enp0s25.100 not found: No such device\n\n\n# sudo ip link add link enp0s25 name enp0s25.100 type vlan id 100\n\n# with vlan device\n-- Logs begin at Mon 2018-11-19 10:50:53 CET, end at Mon 2018-11-26 15:57:22 CET. --\nNov 26 15:57:14 pzhukov-x240.example.com systemd[1]: Starting Router advertisement daemon for IPv6...\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: version 2.17 started\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: IPv6 forwarding setting is: 0, should be 1 or 2\nNov 26 15:57:14 pzhukov-x240.example.com radvd[9677]: IPv6 forwarding seems to be disabled, but continuing anyway\nNov 26 15:57:14 pzhukov-x240.example.com systemd[1]: Started Router advertisement daemon for IPv6.\n\n\n# radvd.conf\ninterface enp0s25.100\n{\n// omitted\n\n};\n\nThere were not too many changes between f28 and rawhide\nCan you please double check your config? \n\n\n+* Wed Jun 13 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-14\n+- Log to stderr in non-daemon mode\n+- Add nodaemon option into manpage\n+- Re-enable test again\n+\n+* Mon Jun 04 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-12\n+- Enable tests and fix them on big endian arches\n+\n+* Thu Apr 12 2018 Pavel Zhukov <pzhukov@redhat.com> - 2.17-11\n+- Enable Werror=all"
					},
					{
						"isprivate": "0",
						"commentid": "12238582",
						"comment_count": "4",
						"who": {
							"text": "intrep",
							"name": "Ben Herrick"
						},
						"bug_when": "2018-11-27 03:16:18 +0000",
						"thetext": "Try adding the VLAN interface using nmcli and then reboot.\n\nThe problem does not occur when starting radvd after the system is booted, but radvd will fail because the VLAN interfaces are started _AFTER_ radvd."
					},
					{
						"isprivate": "0",
						"commentid": "12238584",
						"comment_count": "5",
						"who": {
							"text": "intrep",
							"name": "Ben Herrick"
						},
						"bug_when": "2018-11-27 03:19:54 +0000",
						"thetext": "To be clear, you have to add the VLAN interface permanently in nmcli, also add the configuration for the prefix/interface in /etc/radvd.conf and then reboot in order to observe the behavior."
					},
					{
						"isprivate": "0",
						"commentid": "12239115",
						"comment_count": "6",
						"who": {
							"text": "pzhukov",
							"name": "Pavel Zhukov"
						},
						"bug_when": "2018-11-27 07:52:42 +0000",
						"thetext": "(In reply to Ben Herrick from comment #4)\n> Try adding the VLAN interface using nmcli and then reboot.\n> \n> The problem does not occur when starting radvd after the system is booted,\n> but radvd will fail because the VLAN interfaces are started _AFTER_ radvd.\n\nIt's different problem and seems like radvd has nothing to do with it but NM brings vlan interface up too late.\n\n[Unit]\nDescription=Router advertisement daemon for IPv6\nAfter=network.target"
					},
					{
						"isprivate": "0",
						"commentid": "12239200",
						"comment_count": "7",
						"who": {
							"text": "bgalvani",
							"name": "Beniamino Galvani"
						},
						"bug_when": "2018-11-27 08:27:20 +0000",
						"thetext": "If radvd needs that all connection profiles are activated when it's started, it should depend on the network-online.target in this way:\n\n After=network-online.target\n Wants=network-online.target\n\nso that it is delayed until NetworkManager has completed the initialization. The NetworkManager-wait-online.service should be active as well."
					},
					{
						"isprivate": "0",
						"commentid": "12239248",
						"comment_count": "8",
						"who": {
							"text": "pzhukov",
							"name": "Pavel Zhukov"
						},
						"bug_when": "2018-11-27 08:50:47 +0000",
						"thetext": "(In reply to Beniamino Galvani from comment #7)\n> If radvd needs that all connection profiles are activated when it's started,\n> it should depend on the network-online.target in this way:\n> \n>  After=network-online.target\n>  Wants=network-online.target\n> \n> so that it is delayed until NetworkManager has completed the initialization.\n> The NetworkManager-wait-online.service should be active as well.\n\nOk. Thanks. Moving back then.\nSorry for the noise"
					},
					{
						"isprivate": "0",
						"commentid": "12239250",
						"comment_count": "9",
						"who": {
							"text": "pzhukov",
							"name": "Pavel Zhukov"
						},
						"bug_when": "2018-11-27 08:51:08 +0000",
						"thetext": "(In reply to Beniamino Galvani from comment #7)\n> If radvd needs that all connection profiles are activated when it's started,\n> it should depend on the network-online.target in this way:\n> \n>  After=network-online.target\n>  Wants=network-online.target\n> \n> so that it is delayed until NetworkManager has completed the initialization.\n> The NetworkManager-wait-online.service should be active as well.\n\nOk. Thanks. Moving back then.\nSorry for the noise"
					},
					{
						"isprivate": "0",
						"commentid": "12239922",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-27 11:15:55 +0000",
						"thetext": "radvd-2.17-11.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-3222e7c914"
					},
					{
						"isprivate": "0",
						"commentid": "12239923",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-27 11:16:37 +0000",
						"thetext": "radvd-2.17-16.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-b333ac9645"
					},
					{
						"isprivate": "0",
						"commentid": "12249384",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-28 03:47:27 +0000",
						"thetext": "radvd-2.17-11.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-3222e7c914"
					},
					{
						"isprivate": "0",
						"commentid": "12249487",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-28 04:51:28 +0000",
						"thetext": "radvd-2.17-16.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-b333ac9645"
					},
					{
						"isprivate": "0",
						"commentid": "12254076",
						"comment_count": "14",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-29 04:58:21 +0000",
						"thetext": "radvd-2.17-16.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12398492",
						"comment_count": "15",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-27 19:51:37 +0000",
						"thetext": "radvd-2.17-12.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2019-333a7aa511"
					},
					{
						"isprivate": "0",
						"commentid": "12398604",
						"comment_count": "16",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-28 01:02:33 +0000",
						"thetext": "radvd-2.17-12.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-333a7aa511"
					},
					{
						"isprivate": "0",
						"commentid": "12446389",
						"comment_count": "17",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-12 01:26:10 +0000",
						"thetext": "radvd-2.17-12.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1669297,
			"feedback": [
				{
					"bug_id": 1669297,
					"comment": {
						"id": 888842,
						"text": "How is that a security related bug? I dont see how an attacker can use this flaw. Is a CVE requested for this bug?",
						"timestamp": "2019-01-28 10:31:40",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ffa4b7625be5eced4d6d3ea49cd8c8f60d0c6bd502ed5eb97e52e63f15583009?s=24&d=retro",
							"id": 207,
							"name": "anonymous",
							"openid": "anonymous.id.fedoraproject.org"
						},
						"user_id": 207
					},
					"comment_id": 888842
				},
				{
					"bug_id": 1669297,
					"comment": {
						"id": 888843,
						"text": "https://bugzilla.redhat.com/show_bug.cgi?id=1669298#c1",
						"timestamp": "2019-01-28 10:38:36",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/a697e3056324536b5c3c5f17c44da8c0e9d10cf6e9086c74e2be77536ff9cc94?s=24&d=retro",
							"email": "pavel@zhukoff.net",
							"groups": [
								{
									"name": "packager"
								}
							],
							"id": 1165,
							"name": "landgraf",
							"openid": "landgraf.id.fedoraproject.org"
						},
						"user_id": 1165
					},
					"comment_id": 888843
				}
			],
			"parent": true,
			"security": true,
			"title": "radvd: Use After Free in case of misconfiguration",
			"bugzilla": {
				"bug_id": "1669297",
				"creation_ts": "2019-01-24 21:14:22 +0000",
				"short_desc": "radvd: Use After Free in case of misconfiguration",
				"delta_ts": "2019-09-29 15:06:38 +0000",
				"bug_status": "CLOSED",
				"resolution": "NOTABUG",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1669298"
				],
				"blocked": [
					{
						"bug_id": "1669299",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12394171",
						"comment_count": "0",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-01-24 21:14:22 +0000",
						"thetext": "A flaw was found in radvd. In case of misconfiguration a race condition between privsep and main thread occurs. This leads to double-free and crashing of radvd.\n\n\nReferences:\nhttps://github.com/reubenhwk/radvd/issues/100\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1630167\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1668812\n\nUpstream Patch:\nhttps://github.com/reubenhwk/radvd/pull/101"
					},
					{
						"isprivate": "0",
						"commentid": "12394174",
						"comment_count": "1",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-01-24 21:14:54 +0000",
						"thetext": "Created radvd tracking bugs for this issue:\n\nAffects: fedora-all [bug 1669298]"
					},
					{
						"isprivate": "0",
						"commentid": "12509469",
						"comment_count": "2",
						"who": {
							"text": "dmoppert",
							"name": "Doran Moppert"
						},
						"bug_when": "2019-03-04 05:23:24 +0000",
						"thetext": "In general, mis-handling of incorrect configuration files does not constitute a security vulnerability.  The configuration file for radvd (and most daemons) is trusted input provided by the administrator.\n\nThe bugs referenced in comment#0 track the fixing of this issue in radvd.  No security handling is required."
					}
				]
			}
		},
		{
			"bug_id": 1669298,
			"feedback": [
				{
					"bug_id": 1669298,
					"comment": {
						"id": 888842,
						"text": "How is that a security related bug? I dont see how an attacker can use this flaw. Is a CVE requested for this bug?",
						"timestamp": "2019-01-28 10:31:40",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ffa4b7625be5eced4d6d3ea49cd8c8f60d0c6bd502ed5eb97e52e63f15583009?s=24&d=retro",
							"id": 207,
							"name": "anonymous",
							"openid": "anonymous.id.fedoraproject.org"
						},
						"user_id": 207
					},
					"comment_id": 888842
				},
				{
					"bug_id": 1669298,
					"comment": {
						"id": 888843,
						"text": "https://bugzilla.redhat.com/show_bug.cgi?id=1669298#c1",
						"timestamp": "2019-01-28 10:38:36",
						"update_id": 130537,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/a697e3056324536b5c3c5f17c44da8c0e9d10cf6e9086c74e2be77536ff9cc94?s=24&d=retro",
							"email": "pavel@zhukoff.net",
							"groups": [
								{
									"name": "packager"
								}
							],
							"id": 1165,
							"name": "landgraf",
							"openid": "landgraf.id.fedoraproject.org"
						},
						"user_id": 1165
					},
					"comment_id": 888843
				}
			],
			"security": true,
			"title": "radvd: Use After Free in case of misconfiguration [fedora-all]",
			"bugzilla": {
				"bug_id": "1669298",
				"creation_ts": "2019-01-24 21:14:51 +0000",
				"short_desc": "radvd: Use After Free in case of misconfiguration [fedora-all]",
				"delta_ts": "2019-02-12 01:26:09 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1669297",
						"creation_ts": "2019-01-24 21:14:22 +0000",
						"short_desc": "radvd: Use After Free in case of misconfiguration",
						"delta_ts": "2019-09-29 15:06:38 +0000",
						"bug_status": "CLOSED",
						"resolution": "NOTABUG",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1669298"
						],
						"blocked": [
							{
								"bug_id": "1669299",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12394171",
								"comment_count": "0",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-01-24 21:14:22 +0000",
								"thetext": "A flaw was found in radvd. In case of misconfiguration a race condition between privsep and main thread occurs. This leads to double-free and crashing of radvd.\n\n\nReferences:\nhttps://github.com/reubenhwk/radvd/issues/100\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1630167\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1668812\n\nUpstream Patch:\nhttps://github.com/reubenhwk/radvd/pull/101"
							},
							{
								"isprivate": "0",
								"commentid": "12394174",
								"comment_count": "1",
								"who": {
									"text": "lpardo",
									"name": "Laura Pardo"
								},
								"bug_when": "2019-01-24 21:14:54 +0000",
								"thetext": "Created radvd tracking bugs for this issue:\n\nAffects: fedora-all [bug 1669298]"
							},
							{
								"isprivate": "0",
								"commentid": "12509469",
								"comment_count": "2",
								"who": {
									"text": "dmoppert",
									"name": "Doran Moppert"
								},
								"bug_when": "2019-03-04 05:23:24 +0000",
								"thetext": "In general, mis-handling of incorrect configuration files does not constitute a security vulnerability.  The configuration file for radvd (and most daemons) is trusted input provided by the administrator.\n\nThe bugs referenced in comment#0 track the fixing of this issue in radvd.  No security handling is required."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12394172",
						"comment_count": "0",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-01-24 21:14:51 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "12394173",
						"comment_count": "1",
						"who": {
							"text": "lpardo",
							"name": "Laura Pardo"
						},
						"bug_when": "2019-01-24 21:14:53 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1669297,1669298\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "12398457",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-27 17:50:01 +0000",
						"thetext": "radvd-2.17-17.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-9790f1867a"
					},
					{
						"isprivate": "0",
						"commentid": "12398491",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-27 19:51:36 +0000",
						"thetext": "radvd-2.17-12.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2019-333a7aa511"
					},
					{
						"isprivate": "0",
						"commentid": "12398603",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-28 01:02:32 +0000",
						"thetext": "radvd-2.17-12.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-333a7aa511"
					},
					{
						"isprivate": "0",
						"commentid": "12398672",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-28 02:24:52 +0000",
						"thetext": "radvd-2.17-17.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-9790f1867a"
					},
					{
						"isprivate": "0",
						"commentid": "12406737",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-01-30 02:07:02 +0000",
						"thetext": "radvd-2.17-17.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12446388",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-02-12 01:26:09 +0000",
						"thetext": "radvd-2.17-12.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "radvd-2.17-12.fc28",
			"release_id": 21,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "aarch64"
					},
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "aarch64"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "i686"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "i686"
					},
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "i686"
					}
				],
				"ppc64": [
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64"
					},
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64"
					}
				],
				"ppc64le": [
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "s390x"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "s390x"
					},
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "radvd",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "x86_64"
					},
					{
						"name": "radvd-debugsource",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "x86_64"
					},
					{
						"name": "radvd-debuginfo",
						"version": "2.17",
						"release": "12.fc28",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 888706,
			"text": "This update has been submitted for testing by landgraf. ",
			"timestamp": "2019-01-27 19:51:30",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 888708,
			"text": "This update has obsoleted [radvd-2.17-11.fc28](https://bodhi.fedoraproject.org/updates/FEDORA-2018-3222e7c914), and has inherited its bugs and notes.",
			"timestamp": "2019-01-27 19:51:33",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 888740,
			"text": "This update has been pushed to testing.",
			"timestamp": "2019-01-28 01:02:41",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1652459,
						"title": "vlan interface doesn't exists once network target reached"
					},
					"bug_id": 1652459,
					"comment_id": 888842
				},
				{
					"bug": {
						"bug_id": 1669297,
						"parent": true,
						"security": true,
						"title": "radvd: Use After Free in case of misconfiguration"
					},
					"bug_id": 1669297,
					"comment_id": 888842
				},
				{
					"bug": {
						"bug_id": 1669298,
						"security": true,
						"title": "radvd: Use After Free in case of misconfiguration [fedora-all]"
					},
					"bug_id": 1669298,
					"comment_id": 888842
				}
			],
			"id": 888842,
			"text": "How is that a security related bug? I dont see how an attacker can use this flaw. Is a CVE requested for this bug?",
			"timestamp": "2019-01-28 10:31:40",
			"update_id": 130537,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/ffa4b7625be5eced4d6d3ea49cd8c8f60d0c6bd502ed5eb97e52e63f15583009?s=24&d=retro",
				"id": 207,
				"name": "anonymous",
				"openid": "anonymous.id.fedoraproject.org"
			},
			"user_id": 207
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1652459,
						"title": "vlan interface doesn't exists once network target reached"
					},
					"bug_id": 1652459,
					"comment_id": 888843
				},
				{
					"bug": {
						"bug_id": 1669297,
						"parent": true,
						"security": true,
						"title": "radvd: Use After Free in case of misconfiguration"
					},
					"bug_id": 1669297,
					"comment_id": 888843
				},
				{
					"bug": {
						"bug_id": 1669298,
						"security": true,
						"title": "radvd: Use After Free in case of misconfiguration [fedora-all]"
					},
					"bug_id": 1669298,
					"comment_id": 888843
				}
			],
			"id": 888843,
			"text": "https://bugzilla.redhat.com/show_bug.cgi?id=1669298#c1",
			"timestamp": "2019-01-28 10:38:36",
			"update_id": 130537,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/a697e3056324536b5c3c5f17c44da8c0e9d10cf6e9086c74e2be77536ff9cc94?s=24&d=retro",
				"email": "pavel@zhukoff.net",
				"groups": [
					{
						"name": "packager"
					}
				],
				"id": 1165,
				"name": "landgraf",
				"openid": "landgraf.id.fedoraproject.org"
			},
			"user_id": 1165
		},
		{
			"id": 893430,
			"text": "This update has reached 14 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2019-02-11 06:00:22",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 893435,
			"text": "This update has been submitted for batched by landgraf. ",
			"timestamp": "2019-02-11 06:58:28",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 893436,
			"text": "This update has been submitted for stable by landgraf. ",
			"timestamp": "2019-02-11 06:58:35",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 893811,
			"text": "This update has been pushed to stable.",
			"timestamp": "2019-02-12 01:26:24",
			"update_id": 130537,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"date_pushed": "2019-02-12 01:26:01",
	"date_stable": "2019-02-12 01:26:01",
	"date_submitted": "2019-01-27 19:51:30",
	"date_testing": "2019-01-28 01:02:20",
	"meets_testing_requirements": true,
	"notes": "Fix double-free in InterfaceList\n\n----\n\nDepends on network-online target (#1652459)",
	"pushed": true,
	"release": {
		"branch": "f28",
		"candidate_tag": "f28-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f28",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 28",
		"mail_template": "fedora_errata_template",
		"name": "F28",
		"override_tag": "f28-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f28-signing-pending",
		"pending_stable_tag": "f28-updates-pending",
		"pending_testing_tag": "f28-updates-testing-pending",
		"stable_tag": "f28-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f28-updates-testing",
		"version": "28"
	},
	"require_bugs": true,
	"require_testcases": true,
	"requirements": "",
	"severity": "medium",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "radvd-2.17-12.fc28",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2019-333a7aa511",
	"unstable_karma": -3,
	"updateid": "FEDORA-2019-333a7aa511",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/a697e3056324536b5c3c5f17c44da8c0e9d10cf6e9086c74e2be77536ff9cc94?s=24&d=retro",
		"email": "pavel@zhukoff.net",
		"groups": [
			{
				"name": "packager"
			}
		],
		"id": 1165,
		"name": "landgraf",
		"openid": "landgraf.id.fedoraproject.org"
	},
	"version_hash": "348e98763aa7067ab74444a01507276fba412cd1"
}
