{
	"alias": "FEDORA-2019-bd4843561c",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1757214,
			"feedback": [
				{
					"bug_id": 1757214,
					"comment": {
						"id": 1085857,
						"karma": 1,
						"timestamp": "2019-10-07 17:57:47",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/65ac01c684e76450d8575348b4894728e9c69ffdbd7c08718a4156e8e0daf5b6?s=24&d=retro",
							"email": "hansmueller183@yahoo.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								}
							],
							"id": 284,
							"name": "cairo",
							"openid": "cairo.id.fedoraproject.org"
						},
						"user_id": 284
					},
					"comment_id": 1085857
				},
				{
					"bug_id": 1757214,
					"comment": {
						"id": 1085973,
						"karma": 1,
						"text": "Works",
						"timestamp": "2019-10-07 19:20:25",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/20f7756718e08ef810fe23344dfdcafe17dfb277e2c27d5cbf81e35b66247795?s=24&d=retro",
							"email": "walter.pete@yandex.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								}
							],
							"id": 491,
							"name": "pwalter",
							"openid": "pwalter.id.fedoraproject.org"
						},
						"user_id": 491
					},
					"comment_id": 1085973
				},
				{
					"bug_id": 1757214,
					"comment": {
						"id": 1086006,
						"karma": 1,
						"text": "Works for me. No regressions noted compared to previous version.",
						"timestamp": "2019-10-07 19:36:20",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/c9ddae9d692ab2ea6cecd787db18332407bb29982c8a1eae39771bfb270b71fd?s=24&d=retro",
							"email": "chr77@protonmail.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 308,
							"name": "chr77",
							"openid": "chr77.id.fedoraproject.org"
						},
						"user_id": 308
					},
					"comment_id": 1086006
				},
				{
					"bug_id": 1757214,
					"comment": {
						"id": 1094155,
						"karma": 1,
						"text": "No issues found.",
						"timestamp": "2019-10-14 13:48:16",
						"update_id": 161269,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/9f9c7ca41ea68469600931af4193d0dc1dcb47d3cdbd481fa39fbaae417f4f2f?s=24&d=retro",
							"email": "mhayden@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "gitfedora-security-team"
								},
								{
									"name": "aws-fedora-ci"
								},
								{
									"name": "cloud-sig"
								},
								{
									"name": "rhel-lightspeed"
								}
							],
							"id": 536,
							"name": "mhayden",
							"openid": "mhayden.id.fedoraproject.org"
						},
						"user_id": 536
					},
					"comment_id": 1094155
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc",
			"bugzilla": {
				"bug_id": "1757214",
				"alias": "CVE-2019-16884",
				"creation_ts": "2019-09-30 20:36:53 +0000",
				"short_desc": "CVE-2019-16884 runc: AppArmor/SELinux bypass with malicious image that specifies a volume at /proc",
				"delta_ts": "2023-09-07 20:42:27 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1757290",
					"1759650",
					"1759651",
					"1760088",
					"1760989",
					"1760990",
					"1764182",
					"1765465",
					"1765467",
					"1765468",
					"1810703"
				],
				"blocked": [
					{
						"bug_id": "1757218",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2020:1234",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13216505",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2019-09-30 20:36:53 +0000",
						"thetext": "runc through 1.0.0-rc8, as used in Docker through 19.03.2-ce and other products, allows AppArmor restriction bypass because libcontainer/rootfs_linux.go incorrectly checks mount targets, and thus a malicious Docker image can mount over a /proc directory.\n\nReferences:\nhttps://github.com/opencontainers/runc/issues/2128"
					},
					{
						"isprivate": "0",
						"commentid": "13217352",
						"comment_count": "1",
						"who": {
							"text": "darunesh",
							"name": "Dhananjay Arunesh"
						},
						"bug_when": "2019-10-01 05:37:28 +0000",
						"thetext": "Created runc tracking bugs for this issue:\n\nAffects: fedora-all [bug 1757290]"
					},
					{
						"isprivate": "0",
						"commentid": "13218283",
						"comment_count": "2",
						"who": {
							"text": "dbaker",
							"name": "Dave Baker"
						},
						"bug_when": "2019-10-01 12:27:47 +0000",
						"thetext": "According to the upstream bug report, this also affects SELinux labels:\n- https://github.com/opencontainers/runc/issues/2128#issuecomment-535478352"
					},
					{
						"isprivate": "0",
						"commentid": "13218388",
						"comment_count": "3",
						"who": {
							"text": "dwalsh",
							"name": "Daniel Walsh"
						},
						"bug_when": "2019-10-01 12:58:29 +0000",
						"thetext": "Yes this is an SELinux issue as well as an AppArmor problem."
					},
					{
						"isprivate": "0",
						"commentid": "13248911",
						"comment_count": "14",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2019-10-11 21:17:48 +0000",
						"thetext": "Created docker tracking bugs for this issue:\n\nAffects: fedora-all [bug 1760989]\nAffects: openstack-rdo [bug 1760990]"
					},
					{
						"isprivate": "0",
						"commentid": "13248920",
						"comment_count": "15",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2019-10-11 21:24:03 +0000",
						"thetext": "Statement:\n\nThe AppArmor security module is not supported by Red Hat, on the other hand the flaw also affects SELinux based distributions like Red Hat Enterprise Linux."
					},
					{
						"isprivate": "0",
						"commentid": "13248928",
						"comment_count": "16",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2019-10-11 21:30:36 +0000",
						"thetext": "When creating a new container runc doesn't proper validate whether a non-procfs filesystem is being mounted on top of /proc mount point. As runc relies on attr entries to read or set SELinux labels and attacker may leverage this weakness by creating a crafted container image, with malicious values set on security attributes entry for processes, and mounted on top of container's /proc. This flaw may allow containers to run with more privileged SELinux labels than the default, allowing tasks confined inside the container instance to eventually execute non expected actions.\nThe security impact for this issue is considered Medium for Red Hat Enterprise Linux, as with SELinux the task still runs confined under a less privileged label than unconfined_t."
					},
					{
						"isprivate": "0",
						"commentid": "13252871",
						"comment_count": "17",
						"who": {
							"text": "gscrivan",
							"name": "Giuseppe Scrivano"
						},
						"bug_when": "2019-10-14 13:44:56 +0000",
						"thetext": "WIP backports here: https://github.com/projectatomic/runc/pull/28"
					},
					{
						"isprivate": "0",
						"commentid": "13286653",
						"comment_count": "18",
						"who": {
							"text": "sfowler",
							"name": "Sam Fowler"
						},
						"bug_when": "2019-10-25 07:30:17 +0000",
						"thetext": "Upstream Fix:\n\nhttps://github.com/opencontainers/runc/pull/2129"
					},
					{
						"isprivate": "0",
						"commentid": "13383733",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-11-21 09:50:27 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenShift Container Platform 4.1\n\nVia RHSA-2019:3940 https://access.redhat.com/errata/RHSA-2019:3940"
					},
					{
						"isprivate": "0",
						"commentid": "13384951",
						"comment_count": "21",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2019-11-21 13:04:53 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2019-16884"
					},
					{
						"isprivate": "0",
						"commentid": "13424229",
						"comment_count": "22",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-12-03 21:05:47 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenShift Container Platform 4.2\n\nVia RHSA-2019:4074 https://access.redhat.com/errata/RHSA-2019:4074"
					},
					{
						"isprivate": "0",
						"commentid": "13465267",
						"comment_count": "23",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-12-17 10:47:34 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:4269 https://access.redhat.com/errata/RHSA-2019:4269"
					},
					{
						"isprivate": "0",
						"commentid": "13760609",
						"comment_count": "28",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-04-01 00:26:24 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7 Extras\n\nVia RHSA-2020:1234 https://access.redhat.com/errata/RHSA-2020:1234"
					},
					{
						"isprivate": "0",
						"commentid": "13789535",
						"comment_count": "29",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2020-04-09 18:03:51 +0000",
						"thetext": "This CVE was fixed in runc Red Hat Enterprise Linux 7.8 - Extra Packages via RHSA-2020:1232 https://access.redhat.com/errata/RHBA-2020:1232"
					}
				]
			}
		},
		{
			"bug_id": 1757290,
			"feedback": [
				{
					"bug_id": 1757290,
					"comment": {
						"id": 1085857,
						"karma": 1,
						"timestamp": "2019-10-07 17:57:47",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/65ac01c684e76450d8575348b4894728e9c69ffdbd7c08718a4156e8e0daf5b6?s=24&d=retro",
							"email": "hansmueller183@yahoo.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								}
							],
							"id": 284,
							"name": "cairo",
							"openid": "cairo.id.fedoraproject.org"
						},
						"user_id": 284
					},
					"comment_id": 1085857
				},
				{
					"bug_id": 1757290,
					"comment": {
						"id": 1085973,
						"karma": 1,
						"text": "Works",
						"timestamp": "2019-10-07 19:20:25",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/20f7756718e08ef810fe23344dfdcafe17dfb277e2c27d5cbf81e35b66247795?s=24&d=retro",
							"email": "walter.pete@yandex.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								}
							],
							"id": 491,
							"name": "pwalter",
							"openid": "pwalter.id.fedoraproject.org"
						},
						"user_id": 491
					},
					"comment_id": 1085973
				},
				{
					"bug_id": 1757290,
					"comment": {
						"id": 1086006,
						"karma": 1,
						"text": "Works for me. No regressions noted compared to previous version.",
						"timestamp": "2019-10-07 19:36:20",
						"update_id": 161264,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/c9ddae9d692ab2ea6cecd787db18332407bb29982c8a1eae39771bfb270b71fd?s=24&d=retro",
							"email": "chr77@protonmail.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 308,
							"name": "chr77",
							"openid": "chr77.id.fedoraproject.org"
						},
						"user_id": 308
					},
					"comment_id": 1086006
				},
				{
					"bug_id": 1757290,
					"comment": {
						"id": 1094155,
						"karma": 1,
						"text": "No issues found.",
						"timestamp": "2019-10-14 13:48:16",
						"update_id": 161269,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/9f9c7ca41ea68469600931af4193d0dc1dcb47d3cdbd481fa39fbaae417f4f2f?s=24&d=retro",
							"email": "mhayden@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "gitfedora-security-team"
								},
								{
									"name": "aws-fedora-ci"
								},
								{
									"name": "cloud-sig"
								},
								{
									"name": "rhel-lightspeed"
								}
							],
							"id": 536,
							"name": "mhayden",
							"openid": "mhayden.id.fedoraproject.org"
						},
						"user_id": 536
					},
					"comment_id": 1094155
				}
			],
			"security": true,
			"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc [fedora-all]",
			"bugzilla": {
				"bug_id": "1757290",
				"creation_ts": "2019-10-01 05:37:20 +0000",
				"short_desc": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc [fedora-all]",
				"delta_ts": "2019-10-15 23:13:20 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1757214",
						"alias": "CVE-2019-16884",
						"creation_ts": "2019-09-30 20:36:53 +0000",
						"short_desc": "CVE-2019-16884 runc: AppArmor/SELinux bypass with malicious image that specifies a volume at /proc",
						"delta_ts": "2023-09-07 20:42:27 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1757290",
							"1759650",
							"1759651",
							"1760088",
							"1760989",
							"1760990",
							"1764182",
							"1765465",
							"1765467",
							"1765468",
							"1810703"
						],
						"blocked": [
							{
								"bug_id": "1757218",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2020:1234",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "13216505",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2019-09-30 20:36:53 +0000",
								"thetext": "runc through 1.0.0-rc8, as used in Docker through 19.03.2-ce and other products, allows AppArmor restriction bypass because libcontainer/rootfs_linux.go incorrectly checks mount targets, and thus a malicious Docker image can mount over a /proc directory.\n\nReferences:\nhttps://github.com/opencontainers/runc/issues/2128"
							},
							{
								"isprivate": "0",
								"commentid": "13217352",
								"comment_count": "1",
								"who": {
									"text": "darunesh",
									"name": "Dhananjay Arunesh"
								},
								"bug_when": "2019-10-01 05:37:28 +0000",
								"thetext": "Created runc tracking bugs for this issue:\n\nAffects: fedora-all [bug 1757290]"
							},
							{
								"isprivate": "0",
								"commentid": "13218283",
								"comment_count": "2",
								"who": {
									"text": "dbaker",
									"name": "Dave Baker"
								},
								"bug_when": "2019-10-01 12:27:47 +0000",
								"thetext": "According to the upstream bug report, this also affects SELinux labels:\n- https://github.com/opencontainers/runc/issues/2128#issuecomment-535478352"
							},
							{
								"isprivate": "0",
								"commentid": "13218388",
								"comment_count": "3",
								"who": {
									"text": "dwalsh",
									"name": "Daniel Walsh"
								},
								"bug_when": "2019-10-01 12:58:29 +0000",
								"thetext": "Yes this is an SELinux issue as well as an AppArmor problem."
							},
							{
								"isprivate": "0",
								"commentid": "13248911",
								"comment_count": "14",
								"who": {
									"text": "mbenatto",
									"name": "Marco Benatto"
								},
								"bug_when": "2019-10-11 21:17:48 +0000",
								"thetext": "Created docker tracking bugs for this issue:\n\nAffects: fedora-all [bug 1760989]\nAffects: openstack-rdo [bug 1760990]"
							},
							{
								"isprivate": "0",
								"commentid": "13248920",
								"comment_count": "15",
								"who": {
									"text": "mbenatto",
									"name": "Marco Benatto"
								},
								"bug_when": "2019-10-11 21:24:03 +0000",
								"thetext": "Statement:\n\nThe AppArmor security module is not supported by Red Hat, on the other hand the flaw also affects SELinux based distributions like Red Hat Enterprise Linux."
							},
							{
								"isprivate": "0",
								"commentid": "13248928",
								"comment_count": "16",
								"who": {
									"text": "mbenatto",
									"name": "Marco Benatto"
								},
								"bug_when": "2019-10-11 21:30:36 +0000",
								"thetext": "When creating a new container runc doesn't proper validate whether a non-procfs filesystem is being mounted on top of /proc mount point. As runc relies on attr entries to read or set SELinux labels and attacker may leverage this weakness by creating a crafted container image, with malicious values set on security attributes entry for processes, and mounted on top of container's /proc. This flaw may allow containers to run with more privileged SELinux labels than the default, allowing tasks confined inside the container instance to eventually execute non expected actions.\nThe security impact for this issue is considered Medium for Red Hat Enterprise Linux, as with SELinux the task still runs confined under a less privileged label than unconfined_t."
							},
							{
								"isprivate": "0",
								"commentid": "13252871",
								"comment_count": "17",
								"who": {
									"text": "gscrivan",
									"name": "Giuseppe Scrivano"
								},
								"bug_when": "2019-10-14 13:44:56 +0000",
								"thetext": "WIP backports here: https://github.com/projectatomic/runc/pull/28"
							},
							{
								"isprivate": "0",
								"commentid": "13286653",
								"comment_count": "18",
								"who": {
									"text": "sfowler",
									"name": "Sam Fowler"
								},
								"bug_when": "2019-10-25 07:30:17 +0000",
								"thetext": "Upstream Fix:\n\nhttps://github.com/opencontainers/runc/pull/2129"
							},
							{
								"isprivate": "0",
								"commentid": "13383733",
								"comment_count": "20",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-11-21 09:50:27 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenShift Container Platform 4.1\n\nVia RHSA-2019:3940 https://access.redhat.com/errata/RHSA-2019:3940"
							},
							{
								"isprivate": "0",
								"commentid": "13384951",
								"comment_count": "21",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2019-11-21 13:04:53 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2019-16884"
							},
							{
								"isprivate": "0",
								"commentid": "13424229",
								"comment_count": "22",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-12-03 21:05:47 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenShift Container Platform 4.2\n\nVia RHSA-2019:4074 https://access.redhat.com/errata/RHSA-2019:4074"
							},
							{
								"isprivate": "0",
								"commentid": "13465267",
								"comment_count": "23",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-12-17 10:47:34 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:4269 https://access.redhat.com/errata/RHSA-2019:4269"
							},
							{
								"isprivate": "0",
								"commentid": "13760609",
								"comment_count": "28",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-01 00:26:24 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7 Extras\n\nVia RHSA-2020:1234 https://access.redhat.com/errata/RHSA-2020:1234"
							},
							{
								"isprivate": "0",
								"commentid": "13789535",
								"comment_count": "29",
								"who": {
									"text": "mbenatto",
									"name": "Marco Benatto"
								},
								"bug_when": "2020-04-09 18:03:51 +0000",
								"thetext": "This CVE was fixed in runc Red Hat Enterprise Linux 7.8 - Extra Packages via RHSA-2020:1232 https://access.redhat.com/errata/RHBA-2020:1232"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "13217350",
						"comment_count": "0",
						"who": {
							"text": "darunesh",
							"name": "Dhananjay Arunesh"
						},
						"bug_when": "2019-10-01 05:37:20 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "13217351",
						"comment_count": "1",
						"who": {
							"text": "darunesh",
							"name": "Dhananjay Arunesh"
						},
						"bug_when": "2019-10-01 05:37:23 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1757214,1757290\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "13218305",
						"comment_count": "2",
						"who": {
							"text": "dwalsh",
							"name": "Daniel Walsh"
						},
						"bug_when": "2019-10-01 12:34:57 +0000",
						"thetext": "Note the title of this Bugzilla is misleading, since Fedora does not support AppArmor.  This CVE also effects SELinux.\n\nRunc 0.9 is about to be released, with fixes for this."
					},
					{
						"isprivate": "0",
						"commentid": "13233124",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-07 13:04:02 +0000",
						"thetext": "FEDORA-2019-bd4843561c has been submitted as an update to Fedora 31. https://bodhi.fedoraproject.org/updates/FEDORA-2019-bd4843561c"
					},
					{
						"isprivate": "0",
						"commentid": "13233214",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-07 13:30:50 +0000",
						"thetext": "FEDORA-2019-96946c39dd has been submitted as an update to Fedora 30. https://bodhi.fedoraproject.org/updates/FEDORA-2019-96946c39dd"
					},
					{
						"isprivate": "0",
						"commentid": "13233310",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-07 13:57:11 +0000",
						"thetext": "FEDORA-2019-3fc86a518b has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2019-3fc86a518b"
					},
					{
						"isprivate": "0",
						"commentid": "13234870",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-08 00:27:28 +0000",
						"thetext": "runc-1.0.0-101.rc9.gitc1485a1.fc31 has been pushed to the Fedora 31 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "13237587",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-08 20:22:39 +0000",
						"thetext": "runc-1.0.0-95.rc9.gitc1485a1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-3fc86a518b"
					},
					{
						"isprivate": "0",
						"commentid": "13237659",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-08 20:32:47 +0000",
						"thetext": "runc-1.0.0-95.rc9.gitc1485a1.fc30 has been pushed to the Fedora 30 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2019-96946c39dd"
					},
					{
						"isprivate": "0",
						"commentid": "13258094",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-15 22:39:33 +0000",
						"thetext": "runc-1.0.0-95.rc9.gitc1485a1.fc30 has been pushed to the Fedora 30 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "13258157",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2019-10-15 23:13:20 +0000",
						"thetext": "runc-1.0.0-95.rc9.gitc1485a1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 2,
			"nvr": "runc-1.0.0-101.rc9.gitc1485a1.fc31",
			"release_id": 33,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "aarch64"
					},
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "aarch64"
					},
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "armv7hl"
					},
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "armv7hl"
					},
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "i686"
					},
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "i686"
					},
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "ppc64le"
					},
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "ppc64le"
					},
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "s390x"
					},
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "s390x"
					},
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "runc",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "x86_64"
					},
					{
						"name": "runc-debuginfo",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "x86_64"
					},
					{
						"name": "runc-debugsource",
						"epoch": 2,
						"version": "1.0.0",
						"release": "101.rc9.gitc1485a1.fc31",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1085525,
			"text": "This update has been submitted for testing by lsm5. ",
			"timestamp": "2019-10-07 13:03:57",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1085526,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2019-10-07 13:03:57",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1085528,
			"text": "This update has obsoleted [runc-1.0.0-100.dev.git2e94378.fc31](https://bodhi.fedoraproject.org/updates/FEDORA-2019-09b6884aa2), and has inherited its bugs and notes.",
			"timestamp": "2019-10-07 13:03:58",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1085529,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2019-10-07 13:04:03",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1757214,
						"parent": true,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc"
					},
					"bug_id": 1757214,
					"comment_id": 1085857
				},
				{
					"bug": {
						"bug_id": 1757290,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc [fedora-all]"
					},
					"bug_id": 1757290,
					"comment_id": 1085857
				}
			],
			"id": 1085857,
			"karma": 1,
			"timestamp": "2019-10-07 17:57:47",
			"update_id": 161264,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/65ac01c684e76450d8575348b4894728e9c69ffdbd7c08718a4156e8e0daf5b6?s=24&d=retro",
				"email": "hansmueller183@yahoo.com",
				"groups": [
					{
						"name": "ipausers"
					},
					{
						"name": "signed_fpca"
					}
				],
				"id": 284,
				"name": "cairo",
				"openid": "cairo.id.fedoraproject.org"
			},
			"user_id": 284
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1757214,
						"parent": true,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc"
					},
					"bug_id": 1757214,
					"comment_id": 1085973
				},
				{
					"bug": {
						"bug_id": 1757290,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc [fedora-all]"
					},
					"bug_id": 1757290,
					"comment_id": 1085973
				}
			],
			"id": 1085973,
			"karma": 1,
			"text": "Works",
			"timestamp": "2019-10-07 19:20:25",
			"update_id": 161264,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/20f7756718e08ef810fe23344dfdcafe17dfb277e2c27d5cbf81e35b66247795?s=24&d=retro",
				"email": "walter.pete@yandex.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 491,
				"name": "pwalter",
				"openid": "pwalter.id.fedoraproject.org"
			},
			"user_id": 491
		},
		{
			"bug_feedback": [
				{
					"bug": {
						"bug_id": 1757214,
						"parent": true,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc"
					},
					"bug_id": 1757214,
					"comment_id": 1086006
				},
				{
					"bug": {
						"bug_id": 1757290,
						"security": true,
						"title": "CVE-2019-16884 runc: AppArmor can be bypassed by a malicious image that specifies a volume at /proc [fedora-all]"
					},
					"bug_id": 1757290,
					"comment_id": 1086006
				}
			],
			"id": 1086006,
			"karma": 1,
			"text": "Works for me. No regressions noted compared to previous version.",
			"timestamp": "2019-10-07 19:36:20",
			"update_id": 161264,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/c9ddae9d692ab2ea6cecd787db18332407bb29982c8a1eae39771bfb270b71fd?s=24&d=retro",
				"email": "chr77@protonmail.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 308,
				"name": "chr77",
				"openid": "chr77.id.fedoraproject.org"
			},
			"user_id": 308
		},
		{
			"id": 1086007,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2019-10-07 19:36:21",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1086290,
			"text": "This update has been pushed to stable.",
			"timestamp": "2019-10-08 00:28:43",
			"update_id": 161264,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2019-10-08 00:07:07",
	"date_stable": "2019-10-08 00:07:07",
	"date_submitted": "2019-10-07 13:03:57",
	"karma": 3,
	"meets_testing_requirements": true,
	"notes": "Resolves: #1757214, #1757290 - CVE-2019-16884\n\n----\n\nadd patch for cgroupsv2",
	"pushed": true,
	"release": {
		"branch": "f31",
		"candidate_tag": "f31-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f31",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 31",
		"mail_template": "fedora_errata_template",
		"name": "F31",
		"override_tag": "f31-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f31-signing-pending",
		"pending_stable_tag": "f31-updates-pending",
		"pending_testing_tag": "f31-updates-testing-pending",
		"stable_tag": "f31-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f31-updates-testing",
		"version": "31"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "runc-1.0.0-101.rc9.gitc1485a1.fc31",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2019-bd4843561c",
	"unstable_karma": -3,
	"updateid": "FEDORA-2019-bd4843561c",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/05bd0d0810e225c716eba3290a5596c557d1ea3e4e2b0cf0de8e62a925927b5c?s=24&d=retro",
		"email": "lsm5@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "container-sig"
			}
		],
		"id": 228,
		"name": "lsm5",
		"openid": "lsm5.id.fedoraproject.org"
	},
	"version_hash": "32187845c114e93c3e7c46fb3e02a81416a9bed1"
}
