{
	"alias": "FEDORA-2024-6140989aaf",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2307370,
			"feedback": [
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3720960,
						"karma": 1,
						"timestamp": "2024-09-15 19:03:01",
						"update_id": 646827,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/f80c96a3994c2479fc4815a146079bf93ade230fe3f3993213d2b8222cafc73d?s=24&d=retro",
							"email": "fzatlouk@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "advocates"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								}
							],
							"id": 2240,
							"name": "frantisekz",
							"openid": "frantisekz.id.fedoraproject.org"
						},
						"user_id": 2240
					},
					"comment_id": 3720960
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3696993,
						"karma": 1,
						"text": "Works",
						"timestamp": "2024-08-29 19:13:53",
						"update_id": 643959,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/c12c2b537990fc7c6e095d9a2e4c4ffe07cb228788849f65861dcb112444ca4c?s=24&d=retro",
							"email": "derekenz@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8341,
							"name": "derekenz",
							"openid": "derekenz.id.fedoraproject.org"
						},
						"user_id": 8341
					},
					"comment_id": 3696993
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3698017,
						"karma": 1,
						"timestamp": "2024-08-30 07:05:19",
						"update_id": 643951,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/2b94c96c63ae9341f1af7e212918609b3c67be8deae4cfb2de732806dbde6f1d?s=24&d=retro",
							"email": "vtrefny@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "gitanaconda"
								},
								{
									"name": "storage_apis"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 892,
							"name": "vtrefny",
							"openid": "vtrefny.id.fedoraproject.org"
						},
						"user_id": 892
					},
					"comment_id": 3698017
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3698414,
						"karma": 1,
						"text": "Works",
						"timestamp": "2024-08-30 19:07:39",
						"update_id": 643956,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/c12c2b537990fc7c6e095d9a2e4c4ffe07cb228788849f65861dcb112444ca4c?s=24&d=retro",
							"email": "derekenz@gmail.com",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8341,
							"name": "derekenz",
							"openid": "derekenz.id.fedoraproject.org"
						},
						"user_id": 8341
					},
					"comment_id": 3698414
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3701408,
						"text": "Is this the correct commit fix? as I understand the commit from this pr https://github.com/python/cpython/pull/123161. But the real fix for the 3.9 branch is here https://github.com/python/cpython/pull/123432",
						"timestamp": "2024-09-02 12:20:14",
						"update_id": 643933,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ee174ccfe37d8be88350b84ed403afbafece548af3d908c209b47b22fb3e1cef?s=24&d=retro",
							"email": "ilia.polyvyanyy@red-soft.ru",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8376,
							"name": "polyvyanyy",
							"openid": "polyvyanyy.id.fedoraproject.org"
						},
						"user_id": 8376
					},
					"comment_id": 3701408
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3698025,
						"karma": 1,
						"timestamp": "2024-08-30 07:08:11",
						"update_id": 643961,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/2b94c96c63ae9341f1af7e212918609b3c67be8deae4cfb2de732806dbde6f1d?s=24&d=retro",
							"email": "vtrefny@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "gitanaconda"
								},
								{
									"name": "storage_apis"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 892,
							"name": "vtrefny",
							"openid": "vtrefny.id.fedoraproject.org"
						},
						"user_id": 892
					},
					"comment_id": 3698025
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3706903,
						"karma": -1,
						"text": "https://github.com/python/cpython/pull/123432 now merged",
						"timestamp": "2024-09-05 12:34:38",
						"update_id": 643933,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ee174ccfe37d8be88350b84ed403afbafece548af3d908c209b47b22fb3e1cef?s=24&d=retro",
							"email": "ilia.polyvyanyy@red-soft.ru",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8376,
							"name": "polyvyanyy",
							"openid": "polyvyanyy.id.fedoraproject.org"
						},
						"user_id": 8376
					},
					"comment_id": 3706903
				},
				{
					"bug_id": 2307370,
					"comment": {
						"id": 3713552,
						"karma": 1,
						"timestamp": "2024-09-10 09:46:10",
						"update_id": 646827,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/2b94c96c63ae9341f1af7e212918609b3c67be8deae4cfb2de732806dbde6f1d?s=24&d=retro",
							"email": "vtrefny@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "gitanaconda"
								},
								{
									"name": "storage_apis"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 892,
							"name": "vtrefny",
							"openid": "vtrefny.id.fedoraproject.org"
						},
						"user_id": 892
					},
					"comment_id": 3713552
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2024-8088 python: cpython: Iterating over a malicious ZIP file may lead to Denial of Service",
			"bugzilla": {
				"bug_id": "2307370",
				"alias": "CVE-2024-8088",
				"creation_ts": "2024-08-22 19:20:34 +0000",
				"short_desc": "CVE-2024-8088 python: cpython: Iterating over a malicious ZIP file may lead to Denial of Service",
				"delta_ts": "2024-10-11 01:27:43 +0000",
				"bug_status": "NEW",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"2307457",
					"2307458",
					"2307459",
					"2307460",
					"2307461",
					"2307462",
					"2307463",
					"2307464",
					"2307465",
					"2307466"
				],
				"external_bugs": {
					"text": "RHSA-2024:6962",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18159903",
						"comment_count": "0",
						"who": {
							"text": "bzimport",
							"name": "OSIDB Bzimport"
						},
						"bug_when": "2024-08-22 19:20:34 +0000",
						"thetext": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.ZipFile\" like \"namelist()\", \"iterdir()\", \"extractall()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected."
					},
					{
						"isprivate": "0",
						"commentid": "18165593",
						"comment_count": "1",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-08-28 18:51:55 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:5962 https://access.redhat.com/errata/RHSA-2024:5962"
					},
					{
						"isprivate": "0",
						"commentid": "18184757",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-09-12 01:27:58 +0000",
						"thetext": "FEDORA-2024-e887a10dee (python3.13-3.13.0~rc2-1.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18190050",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-09-17 02:07:35 +0000",
						"thetext": "FEDORA-2024-f2fc325c40 (python3.13-3.13.0~rc2-1.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18199601",
						"comment_count": "4",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-09-24 00:48:32 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6961 https://access.redhat.com/errata/RHSA-2024:6961"
					},
					{
						"isprivate": "0",
						"commentid": "18199602",
						"comment_count": "5",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2024-09-24 00:48:45 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6962 https://access.redhat.com/errata/RHSA-2024:6962"
					}
				]
			}
		},
		{
			"bug_id": 2307466,
			"feedback": [
				{
					"bug_id": 2307466,
					"comment": {
						"id": 3701408,
						"text": "Is this the correct commit fix? as I understand the commit from this pr https://github.com/python/cpython/pull/123161. But the real fix for the 3.9 branch is here https://github.com/python/cpython/pull/123432",
						"timestamp": "2024-09-02 12:20:14",
						"update_id": 643933,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ee174ccfe37d8be88350b84ed403afbafece548af3d908c209b47b22fb3e1cef?s=24&d=retro",
							"email": "ilia.polyvyanyy@red-soft.ru",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8376,
							"name": "polyvyanyy",
							"openid": "polyvyanyy.id.fedoraproject.org"
						},
						"user_id": 8376
					},
					"comment_id": 3701408
				},
				{
					"bug_id": 2307466,
					"comment": {
						"id": 3706903,
						"karma": -1,
						"text": "https://github.com/python/cpython/pull/123432 now merged",
						"timestamp": "2024-09-05 12:34:38",
						"update_id": 643933,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/ee174ccfe37d8be88350b84ed403afbafece548af3d908c209b47b22fb3e1cef?s=24&d=retro",
							"email": "ilia.polyvyanyy@red-soft.ru",
							"groups": [
								{
									"name": "ipausers"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 8376,
							"name": "polyvyanyy",
							"openid": "polyvyanyy.id.fedoraproject.org"
						},
						"user_id": 8376
					},
					"comment_id": 3706903
				}
			],
			"security": true,
			"title": "CVE-2024-8088 python3.9: From NVD collector [fedora-all]",
			"bugzilla": {
				"bug_id": "2307466",
				"creation_ts": "2024-08-22 23:00:03 +0000",
				"short_desc": "CVE-2024-8088 python3.9: From NVD collector [fedora-all]",
				"delta_ts": "2024-09-13 20:45:02 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2307370",
						"alias": "CVE-2024-8088",
						"creation_ts": "2024-08-22 19:20:34 +0000",
						"short_desc": "CVE-2024-8088 python: cpython: Iterating over a malicious ZIP file may lead to Denial of Service",
						"delta_ts": "2024-10-11 01:27:43 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2307457",
							"2307458",
							"2307459",
							"2307460",
							"2307461",
							"2307462",
							"2307463",
							"2307464",
							"2307465",
							"2307466"
						],
						"external_bugs": {
							"text": "RHSA-2024:6962",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18159903",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2024-08-22 19:20:34 +0000",
								"thetext": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.ZipFile\" like \"namelist()\", \"iterdir()\", \"extractall()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected."
							},
							{
								"isprivate": "0",
								"commentid": "18165593",
								"comment_count": "1",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-08-28 18:51:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:5962 https://access.redhat.com/errata/RHSA-2024:5962"
							},
							{
								"isprivate": "0",
								"commentid": "18184757",
								"comment_count": "2",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2024-09-12 01:27:58 +0000",
								"thetext": "FEDORA-2024-e887a10dee (python3.13-3.13.0~rc2-1.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "18190050",
								"comment_count": "3",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2024-09-17 02:07:35 +0000",
								"thetext": "FEDORA-2024-f2fc325c40 (python3.13-3.13.0~rc2-1.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "18199601",
								"comment_count": "4",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:32 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6961 https://access.redhat.com/errata/RHSA-2024:6961"
							},
							{
								"isprivate": "0",
								"commentid": "18199602",
								"comment_count": "5",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:45 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6962 https://access.redhat.com/errata/RHSA-2024:6962"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18160115",
						"comment_count": "0",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2024-08-22 23:00:03 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2307370\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18165046",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 10:51:39 +0000",
						"thetext": "FEDORA-2024-0cf8baac55 (python3.9-3.9.19-6.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-0cf8baac55"
					},
					{
						"isprivate": "0",
						"commentid": "18165052",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 10:56:01 +0000",
						"thetext": "FEDORA-2024-0cf8baac55 (python3.9-3.9.19-6.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18165054",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:27 +0000",
						"thetext": "FEDORA-2024-dc7f1d57e4 (python3.9-3.9.19-6.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-dc7f1d57e4"
					},
					{
						"isprivate": "0",
						"commentid": "18165055",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:30 +0000",
						"thetext": "FEDORA-2024-6140989aaf (python3.9-3.9.19-6.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-6140989aaf"
					},
					{
						"isprivate": "0",
						"commentid": "18165056",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-28 11:01:33 +0000",
						"thetext": "FEDORA-2024-9a940ffe4c (python3.9-3.9.19-6.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-9a940ffe4c"
					},
					{
						"isprivate": "0",
						"commentid": "18165841",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-29 01:59:11 +0000",
						"thetext": "FEDORA-2024-6140989aaf has been pushed to the Fedora 41 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-6140989aaf`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-6140989aaf\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18165882",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-29 02:38:34 +0000",
						"thetext": "FEDORA-2024-dc7f1d57e4 has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-dc7f1d57e4`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-dc7f1d57e4\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18165900",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-29 02:41:15 +0000",
						"thetext": "FEDORA-2024-9a940ffe4c has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-9a940ffe4c`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-9a940ffe4c\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18177171",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-09-06 03:52:38 +0000",
						"thetext": "FEDORA-2024-dc7f1d57e4 (python3.9-3.9.19-6.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18187281",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-09-13 20:45:02 +0000",
						"thetext": "FEDORA-2024-6140989aaf (python3.9-3.9.19-6.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.9-3.9.19-6.fc41",
			"release_id": 80,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.9-debugsource",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					},
					{
						"name": "python3.9-debuginfo",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					},
					{
						"name": "python3.9",
						"version": "3.9.19",
						"release": "6.fc41",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3695596,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2024-08-28 11:01:24",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3695597,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-08-28 11:01:24",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3696306,
			"text": "This update has been pushed to testing.",
			"timestamp": "2024-08-29 02:00:01",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3699924,
			"text": "This update has been submitted for stable by bodhi. \n\nThere is an ongoing freeze; this will be pushed to stable after the freeze is over. ",
			"timestamp": "2024-09-01 02:01:39",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3718946,
			"text": "This update has been pushed to stable.",
			"timestamp": "2024-09-13 20:57:33",
			"update_id": 643932,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2024-09-01 02:01:39",
	"date_pushed": "2024-09-13 20:43:08",
	"date_stable": "2024-09-13 20:43:08",
	"date_submitted": "2024-08-28 11:01:24",
	"date_testing": "2024-08-29 01:58:28",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2024-8088",
	"pushed": true,
	"release": {
		"branch": "f41",
		"candidate_tag": "f41-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f41",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 41",
		"mail_template": "fedora_errata_template",
		"name": "F41",
		"override_tag": "f41-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f41-signing-pending",
		"pending_stable_tag": "f41-updates-pending",
		"pending_testing_tag": "f41-updates-testing-pending",
		"stable_tag": "f41-updates",
		"state": "current",
		"testing_repository": "updates-testing",
		"testing_tag": "f41-updates-testing",
		"version": "41"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 3,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.9-3.9.19-6.fc41",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2024-6140989aaf",
	"unstable_karma": -1,
	"updateid": "FEDORA-2024-6140989aaf",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "d187b6dcc98f203d61d807020e58911c6cc46141"
}
