{
	"alias": "FEDORA-2021-a26257ccf5",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1935913,
			"feedback": [
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1979553,
						"karma": 1,
						"timestamp": "2021-04-09 14:58:05",
						"update_id": 297884,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/03fa5b58e8ac78544bf41ad8ecf9ee1920f2ebedb86542c2f4cdf7ef15813168?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1979553
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1981156,
						"karma": 1,
						"timestamp": "2021-04-11 11:54:35",
						"update_id": 297811,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/03fa5b58e8ac78544bf41ad8ecf9ee1920f2ebedb86542c2f4cdf7ef15813168?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1981156
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1978135,
						"karma": 1,
						"timestamp": "2021-04-08 16:08:17",
						"update_id": 297647,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/b7a62226e7d88529ca69787274bacac45092c0f9bc56e521090d83f859529ce4?s=24&d=retro",
							"email": "oguz@ersen.moe",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "l10n"
								},
								{
									"name": "fedora-join"
								},
								{
									"name": "ask-fedora"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 5615,
							"name": "ersen",
							"openid": "ersen.id.fedoraproject.org"
						},
						"user_id": 5615
					},
					"comment_id": 1978135
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1978281,
						"karma": 1,
						"timestamp": "2021-04-08 18:29:28",
						"update_id": 297648,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/03fa5b58e8ac78544bf41ad8ecf9ee1920f2ebedb86542c2f4cdf7ef15813168?s=24&d=retro",
							"email": "geraldo.simiao.kutz@gmail.com",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "fedora-br"
								},
								{
									"name": "advocates"
								},
								{
									"name": "respins-sig"
								}
							],
							"id": 5881,
							"name": "geraldosimiao",
							"openid": "geraldosimiao.id.fedoraproject.org"
						},
						"user_id": 5881
					},
					"comment_id": 1978281
				},
				{
					"bug_id": 1935913,
					"comment": {
						"id": 1979063,
						"karma": 1,
						"timestamp": "2021-04-09 06:49:50",
						"update_id": 297811,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/b7a62226e7d88529ca69787274bacac45092c0f9bc56e521090d83f859529ce4?s=24&d=retro",
							"email": "oguz@ersen.moe",
							"groups": [
								{
									"name": "qa"
								},
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "l10n"
								},
								{
									"name": "fedora-join"
								},
								{
									"name": "ask-fedora"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 5615,
							"name": "ersen",
							"openid": "ersen.id.fedoraproject.org"
						},
						"user_id": 5615
					},
					"comment_id": 1979063
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2021-3426 python: information disclosure via pydoc",
			"bugzilla": {
				"bug_id": "1935913",
				"alias": "CVE-2021-3426",
				"creation_ts": "2021-03-05 19:20:02 +0000",
				"short_desc": "CVE-2021-3426 python: Information disclosure via pydoc",
				"delta_ts": "2024-06-14 00:40:01 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1936931",
					"1936937",
					"1936698",
					"1936699",
					"1936700",
					"1936701",
					"1936702",
					"1936703",
					"1936933",
					"1936936",
					"1937474",
					"1937475",
					"1937476",
					"1937477",
					"1937479",
					"1937480",
					"1937481",
					"1937482",
					"1937483",
					"1969518"
				],
				"blocked": [
					{
						"bug_id": "1919196",
						"error": "NotPermitted"
					},
					{
						"bug_id": "1937052",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2021:4399",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14846426",
						"comment_count": "0",
						"who": {
							"text": "msiddiqu"
						},
						"bug_when": "2021-03-05 19:20:02 +0000",
						"thetext": "Running `pydoc -p` allows other local users to extract arbitrary files"
					},
					{
						"isprivate": "0",
						"commentid": "14846906",
						"comment_count": "1",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-05 21:50:00 +0000",
						"thetext": "Related upstream PRs:\n\nhttps://github.com/python/cpython/pull/24337\nhttps://github.com/python/cpython/pull/24285"
					},
					{
						"isprivate": "0",
						"commentid": "14857175",
						"comment_count": "11",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 00:11:13 +0000",
						"thetext": "Not sure why it's not mentioned upstream, but in Python 3.7.0 alpha 1+, pydoc has the -n command[1][2]. So using -n can additionally expose this to adjacent attackers rather than just local attackers.\n\n1. https://bugs.python.org/issue31128\n2. https://github.com/python/cpython/commit/6a396c9807b1674a24e240731f18e20de97117a5"
					},
					{
						"isprivate": "0",
						"commentid": "14857211",
						"comment_count": "13",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 00:32:09 +0000",
						"thetext": "Statement:\n\nRed Hat Quay from version 3.4 uses Python from Red Hat Enterprise Linux RPM repositories and therefore may receive an update for this issue in a future release. Earlier versions of Red Hat Quay will not receive an patch for this issue.\n\nPython 2.x.x as shipped in any Red Hat product is not affected. This flaw is out of support scope for python3 as shipped with Red Hat Enterprise Linux 7. For more information about Red Hat Enterprise Linux support scope, please see https://access.redhat.com/support/policy/updates/errata/ ."
					},
					{
						"isprivate": "0",
						"commentid": "14860081",
						"comment_count": "16",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 17:53:06 +0000",
						"thetext": "There is not yet a fix in an upstream Python release at this time."
					},
					{
						"isprivate": "0",
						"commentid": "14860124",
						"comment_count": "17",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-03-10 18:00:58 +0000",
						"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937475]\nAffects: fedora-33 [bug 1937483]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937476]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-7 [bug 1937474]\nAffects: fedora-32 [bug 1937477]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937479]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937480]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937481]\n\n\nCreated python39 tracking bugs for this issue:\n\nAffects: fedora-32 [bug 1937482]"
					},
					{
						"isprivate": "0",
						"commentid": "14947762",
						"comment_count": "19",
						"who": {
							"text": "tcullum",
							"name": "Todd Cullum"
						},
						"bug_when": "2021-04-08 22:03:52 +0000",
						"thetext": "Mitigation:\n\nUse the console (no argument needed) or HTML file (-w argument) output to generate docs rather than the HTTP server options. Put differently, do not use the -p or -n options of pydoc."
					},
					{
						"isprivate": "0",
						"commentid": "15415647",
						"comment_count": "23",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-08-24 08:09:10 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n\nVia RHSA-2021:3254 https://access.redhat.com/errata/RHSA-2021:3254"
					},
					{
						"isprivate": "0",
						"commentid": "15417479",
						"comment_count": "24",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2021-08-24 15:34:58 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2021-3426"
					},
					{
						"isprivate": "0",
						"commentid": "15667044",
						"comment_count": "25",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 17:27:06 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4160 https://access.redhat.com/errata/RHSA-2021:4160"
					},
					{
						"isprivate": "0",
						"commentid": "15667064",
						"comment_count": "26",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 17:28:15 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4162 https://access.redhat.com/errata/RHSA-2021:4162"
					},
					{
						"isprivate": "0",
						"commentid": "15668236",
						"comment_count": "27",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2021-11-09 18:37:04 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2021:4399 https://access.redhat.com/errata/RHSA-2021:4399"
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.8-3.8.9-1.fc34",
			"release_id": 47,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "aarch64"
					},
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "aarch64"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "armv7hl"
					},
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "armv7hl"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "i686"
					},
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "i686"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "ppc64le"
					},
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "ppc64le"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "s390x"
					},
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "s390x"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.8-debugsource",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "x86_64"
					},
					{
						"name": "python3.8-debuginfo",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "x86_64"
					},
					{
						"name": "python3.8",
						"version": "3.8.9",
						"release": "1.fc34",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1975713,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2021-04-07 12:35:38",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1975714,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-04-07 12:35:38",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1975715,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2021-04-07 12:35:38",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1975749,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2021-04-07 12:57:16",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1976502,
			"text": "This update has been pushed to testing.",
			"timestamp": "2021-04-07 18:17:09",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1980604,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2021-04-10 18:16:40",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1980605,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2021-04-10 18:16:41",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1999178,
			"text": "This update has been pushed to stable.",
			"timestamp": "2021-04-24 20:17:57",
			"update_id": 297736,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2021-04-24 20:00:51",
	"date_stable": "2021-04-24 20:00:51",
	"date_submitted": "2021-04-07 12:35:38",
	"date_testing": "2021-04-07 18:13:51",
	"meets_testing_requirements": true,
	"notes": "This is the ninth maintenance release of Python 3.8. [Changelog](https://docs.python.org/release/3.8.9/whatsnew/changelog.html#python-3-8-9). Contains a security fix for CVE-2021-3426.",
	"pushed": true,
	"release": {
		"branch": "f34",
		"candidate_tag": "f34-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f34",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 34",
		"mail_template": "fedora_errata_template",
		"name": "F34",
		"override_tag": "f34-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f34-signing-pending",
		"pending_stable_tag": "f34-updates-pending",
		"pending_testing_tag": "f34-updates-testing-pending",
		"stable_tag": "f34-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f34-updates-testing",
		"version": "34"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 3,
	"stable_karma": 2,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.8-3.8.9-1.fc34",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2021-a26257ccf5",
	"unstable_karma": -1,
	"updateid": "FEDORA-2021-a26257ccf5",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/e221b70024cf971d8b43de0260d2babde9179cdf72605bf3168420e3efe07423?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "74b111dbdd3d73eb530e558b80e903e37a7342e9"
}
