{
	"alias": "FEDORA-2020-e50244961a",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1854936,
			"security": true,
			"title": "CVE-2020-14422 mingw-python3: python: DoS via inefficiency in IPv{4,6}Interface classes [fedora-all]",
			"bugzilla": {
				"bug_id": "1854936",
				"creation_ts": "2020-07-08 12:55:17 +0000",
				"short_desc": "CVE-2020-14422 mingw-python3: python: DoS via inefficiency in IPv{4,6}Interface classes [fedora-all]",
				"delta_ts": "2020-07-23 01:06:01 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1854926",
						"alias": "CVE-2020-14422",
						"creation_ts": "2020-07-08 12:52:24 +0000",
						"short_desc": "CVE-2020-14422 python: DoS via inefficiency in IPv{4,6}Interface classes",
						"delta_ts": "2021-02-16 19:42:16 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1854930",
							"1854931",
							"1854932",
							"1854934",
							"1854936",
							"1854937",
							"1854938",
							"1854939",
							"1854940",
							"1854941",
							"1854942",
							"1854943",
							"1856382",
							"1856383",
							"1856384",
							"1856385",
							"1856386",
							"1857276",
							"1857277",
							"1857278",
							"1857279",
							"1857280",
							"1857282",
							"1857283",
							"1857284",
							"1857285",
							"1857286",
							"1857287",
							"1857288",
							"1857289",
							"1857292",
							"1857293",
							"1857294",
							"1858216",
							"1885290"
						],
						"blocked": [
							{
								"bug_id": "1854944",
								"error": "NotPermitted"
							},
							{
								"bug_id": "1854945",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2020:5010",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "14088166",
								"comment_count": "0",
								"who": {
									"text": "darunesh",
									"name": "Dhananjay Arunesh"
								},
								"bug_when": "2020-07-08 12:52:24 +0000",
								"thetext": "A vulnerability was found in Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in the IPv4Interface and IPv6Interface classes, which might allow a remote attacker to cause a denial of service if an application is affected by the performance of a dictionary containing IPv4Interface or IPv6Interface objects, and this attacker can cause many dictionary entries to be created.\n\nReferences:\nhttps://bugs.python.org/issue41004\nhttps://github.com/python/cpython/pull/20956"
							},
							{
								"isprivate": "0",
								"commentid": "14088216",
								"comment_count": "1",
								"who": {
									"text": "darunesh",
									"name": "Dhananjay Arunesh"
								},
								"bug_when": "2020-07-08 12:56:50 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854936]\n\n\nCreated python2 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854931]\n\n\nCreated python26 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854934]\n\n\nCreated python27 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854937]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854932]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 1854930]\nAffects: fedora-all [bug 1854938]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854939]\n\n\nCreated python36 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854940]\n\n\nCreated python37 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854941]\n\n\nCreated python38 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854942]\n\n\nCreated python39 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1854943]"
							},
							{
								"isprivate": "0",
								"commentid": "14111754",
								"comment_count": "4",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-07-15 15:12:38 +0000",
								"thetext": "The hash value returned by IPv4Interface/IPv6Interface classes is wrongly a constant value. When an IPvXInterface object is used as key of a python dictionary, the hash value is used to determine in which hash table bucket the object needs to be put. For a large number of elements, the constant hash value transforms most dictionary operation in O(n) instead of the expected O(1), making a program much slower."
							},
							{
								"isprivate": "0",
								"commentid": "14111763",
								"comment_count": "5",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-07-15 15:14:01 +0000",
								"thetext": "python3 embeds the ipaddress module, where the flaw lies. Instead python2 does not embeds it, but a separate python-ipaddress package is provided. Moreover, the ipaddress module is usually embedded in python-pip as well."
							},
							{
								"isprivate": "0",
								"commentid": "14111789",
								"comment_count": "6",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-07-15 15:20:37 +0000",
								"thetext": "Statement:\n\nIn Red Hat Enterprise Linux, python3 includes the ipaddress module by default, while for python2 a separate package, python-ipaddress, needs to be installed for the module to be used. Moreover, the ipaddress module is included in other packages as well, like python-pip."
							},
							{
								"isprivate": "0",
								"commentid": "14111860",
								"comment_count": "8",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-07-15 15:31:17 +0000",
								"thetext": "Created python-ipaddress tracking bugs for this issue:\n\nAffects: fedora-all [bug 1857292]\n\n\nCreated python-pip tracking bugs for this issue:\n\nAffects: epel-all [bug 1857294]\nAffects: fedora-all [bug 1857293]"
							},
							{
								"isprivate": "0",
								"commentid": "14111949",
								"comment_count": "9",
								"who": {
									"text": "mhroncok",
									"name": "Miro Hronƒçok"
								},
								"bug_when": "2020-07-15 15:59:30 +0000",
								"thetext": "Pip does not have dictionaries containing IPv4Interface or IPv6Interface objects. I don't think it's worth patching the bundled ipaddress module in it."
							},
							{
								"isprivate": "0",
								"commentid": "14118275",
								"comment_count": "12",
								"who": {
									"text": "rschiron",
									"name": "Riccardo Schirone"
								},
								"bug_when": "2020-07-17 09:21:58 +0000",
								"thetext": "Mitigation:\n\nAs a short term solution, if your application is using the IPv4Interface/IPv6Interface classes as keys of a dictionary, it is possible to patch the __hash__ method of those classes to not be constant.\n```\nIPv4Interface.__hash__ = lambda self: hash((self._ip, self._prefixlen, int(self.network.network_address)))\nIPv6Interface.__hash__ = lambda self: hash((self._ip, self._prefixlen, int(self.network.network_address)))\n```"
							},
							{
								"isprivate": "0",
								"commentid": "14405951",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-10-19 18:05:40 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n\nVia RHSA-2020:4285 https://access.redhat.com/errata/RHSA-2020:4285"
							},
							{
								"isprivate": "0",
								"commentid": "14406372",
								"comment_count": "19",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2020-10-19 20:21:15 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2020-14422"
							},
							{
								"isprivate": "0",
								"commentid": "14410057",
								"comment_count": "22",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-10-20 20:00:07 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n\nVia RHSA-2020:4299 https://access.redhat.com/errata/RHSA-2020:4299"
							},
							{
								"isprivate": "0",
								"commentid": "14468339",
								"comment_count": "23",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-11-04 00:51:35 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:4433 https://access.redhat.com/errata/RHSA-2020:4433"
							},
							{
								"isprivate": "0",
								"commentid": "14471264",
								"comment_count": "24",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-11-04 02:35:56 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:4641 https://access.redhat.com/errata/RHSA-2020:4641"
							},
							{
								"isprivate": "0",
								"commentid": "14492956",
								"comment_count": "26",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-11-10 12:59:24 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:5010 https://access.redhat.com/errata/RHSA-2020:5010"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "14088190",
						"comment_count": "0",
						"who": {
							"text": "darunesh",
							"name": "Dhananjay Arunesh"
						},
						"bug_when": "2020-07-08 12:55:17 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "14088191",
						"comment_count": "1",
						"who": {
							"text": "darunesh",
							"name": "Dhananjay Arunesh"
						},
						"bug_when": "2020-07-08 12:55:22 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1854926,1854936\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "14102375",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-07-13 15:04:35 +0000",
						"thetext": "FEDORA-2020-e50244961a has been submitted as an update to Fedora 32. https://bodhi.fedoraproject.org/updates/FEDORA-2020-e50244961a"
					},
					{
						"isprivate": "0",
						"commentid": "14105563",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-07-14 01:07:21 +0000",
						"thetext": "FEDORA-2020-e50244961a has been pushed to the Fedora 32 testing repository.\nIn short time you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-e50244961a`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-e50244961a\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14109456",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-07-15 02:00:56 +0000",
						"thetext": "FEDORA-2020-dfb11916cc has been pushed to the Fedora 32 testing repository.\nIn short time you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-dfb11916cc`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2020-dfb11916cc\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "14132271",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2020-07-23 01:06:01 +0000",
						"thetext": "FEDORA-2020-dfb11916cc has been pushed to the Fedora 32 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "mingw-python3-3.8.3-2.fc32",
			"release_id": 35,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "mingw64-python3",
						"version": "3.8.3",
						"release": "2.fc32",
						"arch": "noarch"
					},
					{
						"name": "mingw32-python3",
						"version": "3.8.3",
						"release": "2.fc32",
						"arch": "noarch"
					},
					{
						"name": "mingw32-python3-debuginfo",
						"version": "3.8.3",
						"release": "2.fc32",
						"arch": "noarch"
					},
					{
						"name": "mingw64-python3-debuginfo",
						"version": "3.8.3",
						"release": "2.fc32",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "mingw-python3",
						"version": "3.8.3",
						"release": "2.fc32",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1455914,
			"text": "This update has been submitted for testing by smani. ",
			"timestamp": "2020-07-13 15:04:32",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1455915,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-07-13 15:04:32",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1455916,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2020-07-13 15:04:32",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1455952,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-07-13 15:29:58",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1456598,
			"text": "This update has been pushed to testing.",
			"timestamp": "2020-07-14 01:07:36",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1457281,
			"text": "This update has been obsoleted by [mingw-python3-3.8.3-3.fc32](https://bodhi.fedoraproject.org/updates/FEDORA-2020-dfb11916cc).",
			"timestamp": "2020-07-14 14:18:33",
			"update_id": 219117,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2020-07-14 01:06:59",
	"date_submitted": "2020-07-13 15:04:32",
	"date_testing": "2020-07-14 01:06:59",
	"meets_testing_requirements": true,
	"notes": "Update to 3.8.3,  backport patch for CVE-2020-14422.",
	"release": {
		"branch": "f32",
		"candidate_tag": "f32-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f32",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 32",
		"mail_template": "fedora_errata_template",
		"name": "F32",
		"override_tag": "f32-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f32-signing-pending",
		"pending_stable_tag": "f32-updates-pending",
		"pending_testing_tag": "f32-updates-testing-pending",
		"stable_tag": "f32-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f32-updates-testing",
		"version": "32"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 7,
	"stable_karma": 3,
	"status": "obsolete",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "mingw-python3-3.8.3-2.fc32",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2020-e50244961a",
	"unstable_karma": -3,
	"updateid": "FEDORA-2020-e50244961a",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/30146b3eb0f2f15ffe42bd8fcd8a1fef46a4ce6a2025fb7052caaa089ce2e0cd?s=24&d=retro",
		"email": "manisandro@gmail.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "mkdocs-sig"
			}
		],
		"id": 117,
		"name": "smani",
		"openid": "smani.id.fedoraproject.org"
	},
	"version_hash": "c706efd17433e568e32ce5b761dde6a8d1aeeed1"
}
