{
	"alias": "FEDORA-2017-2e5a17c4cc",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1519605,
			"security": true,
			"title": "CVE-2017-1000158 python33: python: Integer overflow in PyString_DecodeEscape results in heap-base buffer overflow [fedora-all]",
			"bugzilla": {
				"bug_id": "1519605",
				"creation_ts": "2017-12-01 01:45:03 +0000",
				"short_desc": "CVE-2017-1000158 python33: python: Integer overflow in PyString_DecodeEscape results in heap-base buffer overflow [fedora-all]",
				"delta_ts": "2018-01-03 21:18:28 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1519595",
						"alias": "CVE-2017-1000158",
						"creation_ts": "2017-12-01 01:19:14 +0000",
						"short_desc": "CVE-2017-1000158 python: Integer overflow in PyString_DecodeEscape results in heap-base buffer overflow",
						"delta_ts": "2021-06-10 13:47:01 +0000",
						"bug_status": "CLOSED",
						"resolution": "WONTFIX",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1519601",
							"1519602",
							"1519603",
							"1519604",
							"1519605",
							"1519606"
						],
						"blocked": [
							{
								"bug_id": "1519600",
								"error": "NotPermitted"
							}
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "11052956",
								"comment_count": "0",
								"who": {
									"text": "sfowler",
									"name": "Sam Fowler"
								},
								"bug_when": "2017-12-01 01:19:14 +0000",
								"thetext": "In Python 2.7, Python 3.4 and Python 3.5 there is a possible integer overflow in PyString_DecodeEscape function of the file stringobject.c, which can be abused to gain a heap overflow, possibly leading to arbitrary code execution.\n\nReferences:\nhttps://bugs.python.org/issue30657\nhttp://python-security.readthedocs.io/vuln/cve-2017-1000158_pystring_decodeescape_integer_overflow.html\nhttps://github.com/python/cpython/commit/c3c9db89273fabc62ea1b48389d9a3000c1c03ae"
							},
							{
								"isprivate": "0",
								"commentid": "11053016",
								"comment_count": "1",
								"who": {
									"text": "sfowler",
									"name": "Sam Fowler"
								},
								"bug_when": "2017-12-01 01:45:18 +0000",
								"thetext": "Created python tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519606]\n\n\nCreated python26 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519602]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519604]\n\n\nCreated python33 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519605]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519601]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1519603]"
							},
							{
								"isprivate": "0",
								"commentid": "11081591",
								"comment_count": "2",
								"who": {
									"text": "pebarbos",
									"name": "Pedro Yóssis Silva Barbosa"
								},
								"bug_when": "2017-12-08 18:22:54 +0000",
								"thetext": "External References:\n\nhttp://python-security.readthedocs.io/vuln/cve-2017-1000158_pystring_decodeescape_integer_overflow.html"
							},
							{
								"isprivate": "0",
								"commentid": "11081695",
								"comment_count": "6",
								"who": {
									"text": "pebarbos",
									"name": "Pedro Yóssis Silva Barbosa"
								},
								"bug_when": "2017-12-08 19:03:10 +0000",
								"thetext": "Statement:\n\nThis issue affects the versions of python as shipped with Red Hat Enterprise Linux 6 and Red Hat Enterprise Linux 7, and python27-python, rh-python34-python, and rh-python35-python as shipped with Red Hat Software Collections 3. Red Hat Product Security has rated this issue as having Moderate security impact. A future update may address this issue. For additional information, refer to the Issue Severity Classification: https://access.redhat.com/security/updates/classification/."
							},
							{
								"isprivate": "0",
								"commentid": "11086732",
								"comment_count": "9",
								"who": {
									"text": "pebarbos",
									"name": "Pedro Yóssis Silva Barbosa"
								},
								"bug_when": "2017-12-11 12:24:18 +0000",
								"thetext": "Upstream commit:\n\nhttps://github.com/python/cpython/commit/c3c9db89273fabc62ea1b48389d9a3000c1c03ae"
							},
							{
								"isprivate": "0",
								"commentid": "11087034",
								"comment_count": "10",
								"who": {
									"text": "mhroncok",
									"name": "Miro Hrončok"
								},
								"bug_when": "2017-12-11 13:27:29 +0000",
								"thetext": "And for 3.4 and 3.5:\n\nhttps://github.com/python/cpython/commit/6c004b40f9d51872d848981ef1a18bb08c2dfc42\nhttps://github.com/python/cpython/commit/fd8614c5c5466a14a945db5b059c10c0fb8f76d9"
							},
							{
								"isprivate": "0",
								"commentid": "11383433",
								"comment_count": "13",
								"who": {
									"text": "pebarbos",
									"name": "Pedro Yóssis Silva Barbosa"
								},
								"bug_when": "2018-03-15 13:17:51 +0000",
								"thetext": "\"You need to compile a 1 GiB Python file on 32-bit system for reproducing it. It is very unlikely that this can happen by accident, and it is hard to used it in security attack. If you can make the attacked program compiling a 1 GiB Python file, you perhaps have easier ways to make a harm.\"\n\nRef: http://python-security.readthedocs.io/vuln/cve-2017-1000158_pystring_decodeescape_integer_overflow.html\n\n\"In the highly unlikely but definitely possible situation that we pass it a very large string (in the order of ~1GB on a 32-bit Python install), one can reliably get heap corruption.\"\n\nRef: https://bugs.python.org/msg295930"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11053008",
						"comment_count": "0",
						"who": {
							"text": "sfowler",
							"name": "Sam Fowler"
						},
						"bug_when": "2017-12-01 01:45:03 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "11053011",
						"comment_count": "1",
						"who": {
							"text": "sfowler",
							"name": "Sam Fowler"
						},
						"bug_when": "2017-12-01 01:45:08 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1519595,1519605\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "11087163",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2017-12-11 13:50:05 +0000",
						"thetext": "python33-3.3.7-2.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2017-2e5a17c4cc"
					},
					{
						"isprivate": "0",
						"commentid": "11087226",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2017-12-11 14:03:56 +0000",
						"thetext": "python33-3.3.7-2.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2017-7fe2c4bc0e"
					},
					{
						"isprivate": "0",
						"commentid": "11088920",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2017-12-11 19:58:05 +0000",
						"thetext": "python33-3.3.7-2.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-2e5a17c4cc"
					},
					{
						"isprivate": "0",
						"commentid": "11089048",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2017-12-11 20:33:50 +0000",
						"thetext": "python33-3.3.7-2.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-7fe2c4bc0e"
					},
					{
						"isprivate": "0",
						"commentid": "11148011",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-01-02 16:46:18 +0000",
						"thetext": "python33-3.3.7-2.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11152898",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-01-03 21:18:28 +0000",
						"thetext": "python33-3.3.7-2.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python33-3.3.7-2.fc27",
			"release_id": 17,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "aarch64"
					},
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "aarch64"
					},
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "armv7hl"
					},
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "armv7hl"
					},
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "i686"
					},
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "i686"
					},
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "i686"
					}
				],
				"ppc64": [
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64"
					},
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64"
					},
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64"
					}
				],
				"ppc64le": [
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64le"
					},
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64le"
					},
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "s390x"
					},
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "s390x"
					},
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python33-debuginfo",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "x86_64"
					},
					{
						"name": "python33-debugsource",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "x86_64"
					},
					{
						"name": "python33",
						"version": "3.3.7",
						"release": "2.fc27",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 707381,
			"text": "This update has been submitted for testing by cstratak. ",
			"timestamp": "2017-12-11 13:50:00",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 707558,
			"text": "This update has been pushed to testing.",
			"timestamp": "2017-12-11 19:58:57",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 710347,
			"text": "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2017-12-19 00:00:47",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 713584,
			"karma": 1,
			"text": "no regressions noted",
			"timestamp": "2017-12-30 03:04:46",
			"update_id": 104045,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/c60ab53f3bfe23061b21fd0bd0b53fe94c3322dfc6dc4a7d8d04f7d8efd098f8?s=24&d=retro",
				"email": "hotgalan@gmail.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "dotnet-team"
					},
					{
						"name": "marketing"
					},
					{
						"name": "mindshare"
					},
					{
						"name": "council"
					},
					{
						"name": "diversity-team"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "neuro-sig"
					},
					{
						"name": "commops"
					},
					{
						"name": "ask-fedora"
					},
					{
						"name": "fedora-join"
					},
					{
						"name": "wikiedit"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "summer-coding"
					},
					{
						"name": "fedora-mx"
					},
					{
						"name": "advocates"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "ipausers"
					}
				],
				"id": 3278,
				"name": "bt0dotninja",
				"openid": "bt0dotninja.id.fedoraproject.org"
			},
			"user_id": 3278
		},
		{
			"id": 713585,
			"text": "This update has been submitted for batched by bodhi. ",
			"timestamp": "2017-12-30 03:04:46",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 714114,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2018-01-02 03:00:44",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 714589,
			"text": "This update has been pushed to stable.",
			"timestamp": "2018-01-02 16:55:13",
			"update_id": 104045,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2018-01-02 14:45:21",
	"date_stable": "2018-01-02 14:45:21",
	"date_submitted": "2017-12-11 13:50:00",
	"date_testing": "2017-12-11 19:11:21",
	"karma": 1,
	"notes": "Fix for CVE-2017-1000158",
	"pushed": true,
	"release": {
		"branch": "f27",
		"candidate_tag": "f27-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f27",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 27",
		"mail_template": "fedora_errata_template",
		"name": "F27",
		"override_tag": "f27-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f27-signing-pending",
		"pending_stable_tag": "f27-updates-pending",
		"pending_testing_tag": "f27-updates-testing-pending",
		"stable_tag": "f27-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f27-updates-testing",
		"version": "27"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "unspecified",
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"title": "python33-3.3.7-2.fc27",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2017-2e5a17c4cc",
	"unstable_karma": -1,
	"updateid": "FEDORA-2017-2e5a17c4cc",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/af49eb5320c1c40d81a98d1fcdccc06c470c1458daab1a4f27be4cb170dbab3c?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "2cac38615913a2ee039c343d949891282cd52ab2"
}
