{
	"alias": "FEDORA-EPEL-2020-88a247cda8",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 1649153,
			"parent": true,
			"security": true,
			"title": "CVE-2018-20060 python-urllib3: Cross-host redirect does not remove Authorization header allow for credential exposure",
			"bugzilla": {
				"bug_id": "1649153",
				"alias": "CVE-2018-20060",
				"creation_ts": "2018-11-13 03:15:47 +0000",
				"short_desc": "CVE-2018-20060 python-urllib3: Cross-host redirect does not remove Authorization header allow for credential exposure",
				"delta_ts": "2023-10-06 17:59:28 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1649154",
					"1649155",
					"1649156",
					"1649157",
					"1658470",
					"1658471",
					"1658982",
					"1666506",
					"1666507",
					"1666508",
					"1666509",
					"1666511",
					"1678987",
					"1678988",
					"1717360",
					"1717362",
					"1717363",
					"1717364",
					"1717365",
					"1774425",
					"1774426",
					"1774427",
					"1774430",
					"1774431",
					"1774432",
					"1774433",
					"1774434",
					"1778102",
					"1778104",
					"1778105",
					"1778110",
					"1778111",
					"1778112",
					"1804581",
					"1804582",
					"1804583",
					"1804584"
				],
				"blocked": [
					{
						"bug_id": "1649158",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2020:2081",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12200473",
						"comment_count": "0",
						"who": {
							"text": "sfowler",
							"name": "Sam Fowler"
						},
						"bug_when": "2018-11-13 03:15:47 +0000",
						"thetext": "python-urllib3 before version 1.23 does not remove the 'Authorization' HTTP header when following a cross-origin redirect. This can allow for credentials in the 'Authorization' header to be exposed as they are transmitted in plaintext.\n\n\nUpstream Issues:\n\nhttps://github.com/urllib3/urllib3/issues/1316\nhttps://github.com/urllib3/urllib3/pull/1346"
					},
					{
						"isprivate": "0",
						"commentid": "12200481",
						"comment_count": "1",
						"who": {
							"text": "sfowler",
							"name": "Sam Fowler"
						},
						"bug_when": "2018-11-13 03:16:22 +0000",
						"thetext": "Created python-urllib3 tracking bugs for this issue:\n\nAffects: epel-all [bug 1649156]\nAffects: fedora-27 [bug 1649154]\nAffects: fedora-28 [bug 1649155]\nAffects: openstack-rdo [bug 1649157]"
					},
					{
						"isprivate": "0",
						"commentid": "12276214",
						"comment_count": "2",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2018-12-05 09:57:40 +0000",
						"thetext": "Upstream patch commits:\nhttps://github.com/urllib3/urllib3/commit/3d7f98b07b6e6e04c2e89cdf5afb18024a2d804c\nhttps://github.com/urllib3/urllib3/commit/f99912beeaf230ee3634b938d3ea426ffd1f3e57\nhttps://github.com/urllib3/urllib3/commit/48dba048081dfcb999afcda715d17147aa15b6ea\nhttps://github.com/urllib3/urllib3/commit/23e2eb56af23db5a1eeb8ad9b51dd99a27c15522\nhttps://github.com/urllib3/urllib3/commit/5e9c6b9175d66170ef65fc703f2e46788a59ca0c\nhttps://github.com/urllib3/urllib3/commit/9c9dd6f3014e89bb9c532b641abcf1b24c3896ab\nhttps://github.com/urllib3/urllib3/commit/6245ddddb7f80740c5c15e1750e5b9f68c5b2b5f\nhttps://github.com/urllib3/urllib3/commit/3b5f27449e153ad05186beca8fbd9b134936fe50\nhttps://github.com/urllib3/urllib3/commit/1742538d57865e61125c6c12a755b5db41636fe7\nhttps://github.com/urllib3/urllib3/commit/2a42e70ff077006d5a6da92251ddbb2939303f94\nhttps://github.com/urllib3/urllib3/commit/e8a727a0b8389f5f75981858a8bbb319646f4450\nhttps://github.com/urllib3/urllib3/commit/63948f3a607ed8e7a3ce9ac4e20782359896e27e\nhttps://github.com/urllib3/urllib3/commit/560bd227b90f74417ffaedebf5f8d05a8ee4f532\n\nGot from GitHub pull request:\nhttps://github.com/urllib3/urllib3/pull/1346"
					},
					{
						"isprivate": "0",
						"commentid": "12295289",
						"comment_count": "4",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2018-12-12 08:42:41 +0000",
						"thetext": "An attacker who can intercept traffic between the victim host and the server, may be able to read the Authorization header content when a server redirects to an HTTP endpoint on the same server. It is required that a server has such redirects and that the user visits it for the attack to take place.\n\nPatched python-urllib3 versions remove the Authorization header by default on redirects."
					},
					{
						"isprivate": "0",
						"commentid": "12295327",
						"comment_count": "8",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2018-12-12 08:55:36 +0000",
						"thetext": "Mitigation:\n\nUse `retries=urllib3.Retry(redirect=0)` when performing requests if you do not need redirection and handle the redirects manually if you need them."
					},
					{
						"isprivate": "0",
						"commentid": "12533965",
						"comment_count": "18",
						"who": {
							"text": "rcosta",
							"name": "Richard Maciel Costa"
						},
						"bug_when": "2019-03-12 04:12:29 +0000",
						"thetext": "In reply to comment #17:\n> (In reply to Riccardo Schirone from comment #3)\n> > Private reproducer available here (after Kerberos login):\n> > \n> > https://svn.devel.redhat.com/repos/srtvulns/trunk/components/python-urllib3/\n> > CVE-2018-20060\n> \n> I've managed to backport upstream patches to rhel7.7 and now I'd like to\n> test it but the link mentioned in comment #3 doesn't work so I cannot use\n> the reproducer.\n> \n> Richard, could you please take a look?\n\nSent a copy to you by email."
					},
					{
						"isprivate": "0",
						"commentid": "12980335",
						"comment_count": "24",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-07-23 08:09:01 +0000",
						"thetext": "In reply to comment #4:\n> An attacker who can intercept traffic between the victim host and the\n> server, may be able to read the Authorization header content when a server\n> redirects to an HTTP endpoint on the same server. It is required that a\n> server has such redirects and that the user visits it for the attack to take\n> place.\n\nActually this flaw can be triggered even when the redirect is cross-origin, thus the redirection can go on another server as well.\n\nUser Interaction set to Required (UI:R) because the user needs to visit the HTTPS server to trigger the vulnerability.\nAttack Vector set to Network(AV:N) because an attacker needs to perform a man-in-the-middle attack to get access to the transferred data.\nAttack Complexity set to High(AC:H) because the attack depends on the specific application that needs to be on HTTPS, to have a redirect to an HTTP server and to use HTTP authorization. Moreover, the attacker needs a man-in-the-middle attack."
					},
					{
						"isprivate": "0",
						"commentid": "13032826",
						"comment_count": "25",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-08-06 12:34:14 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2019:2272 https://access.redhat.com/errata/RHSA-2019:2272"
					},
					{
						"isprivate": "0",
						"commentid": "13036465",
						"comment_count": "26",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2019-08-06 19:20:07 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2018-20060"
					},
					{
						"isprivate": "0",
						"commentid": "13378767",
						"comment_count": "27",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-11-20 09:54:36 +0000",
						"thetext": "Created python-pip tracking bugs for this issue:\n\nAffects: epel-6 [bug 1774426]\nAffects: fedora-29 [bug 1774425]\n\n\nCreated python-pip-epel tracking bugs for this issue:\n\nAffects: epel-7 [bug 1774427]"
					},
					{
						"isprivate": "0",
						"commentid": "13413013",
						"comment_count": "29",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-11-29 10:24:27 +0000",
						"thetext": "Created python-virtualenv tracking bugs for this issue:\n\nAffects: epel-6 [bug 1778104]\nAffects: fedora-30 [bug 1778102]\n\n\nCreated python3-virtualenv tracking bugs for this issue:\n\nAffects: epel-7 [bug 1778105]"
					},
					{
						"isprivate": "0",
						"commentid": "13711383",
						"comment_count": "31",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-03-17 16:18:19 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0850 https://access.redhat.com/errata/RHSA-2020:0850"
					},
					{
						"isprivate": "0",
						"commentid": "13711388",
						"comment_count": "32",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-03-17 16:18:40 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0851 https://access.redhat.com/errata/RHSA-2020:0851"
					},
					{
						"isprivate": "0",
						"commentid": "13849943",
						"comment_count": "33",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-04-28 15:29:16 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1605 https://access.redhat.com/errata/RHSA-2020:1605"
					},
					{
						"isprivate": "0",
						"commentid": "13851287",
						"comment_count": "34",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-04-28 16:08:37 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1916 https://access.redhat.com/errata/RHSA-2020:1916"
					},
					{
						"isprivate": "0",
						"commentid": "13907632",
						"comment_count": "35",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-05-12 18:37:48 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2068 https://access.redhat.com/errata/RHSA-2020:2068"
					},
					{
						"isprivate": "0",
						"commentid": "13907641",
						"comment_count": "36",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-05-12 18:38:00 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2081 https://access.redhat.com/errata/RHSA-2020:2081"
					},
					{
						"isprivate": "0",
						"commentid": "14618908",
						"comment_count": "37",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2020-12-19 20:38:41 +0000",
						"thetext": "Statement:\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected critical and important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package."
					}
				]
			}
		},
		{
			"bug_id": 1700824,
			"feedback": [
				{
					"bug_id": 1700824,
					"comment": {
						"id": 1185735,
						"karma": 1,
						"text": "Tested with pip install ---user on both python2 and python3....LGTM",
						"timestamp": "2020-01-05 04:56:33",
						"update_id": 176492,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/5b06b02a427ed84d4dd9fdd82bb27ce11005630cb6635b0f6f6fa7ac9c72c1c0?s=24&d=retro",
							"email": "mhjacks@swbell.net",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "trust admins"
								}
							],
							"id": 2526,
							"name": "mhjacks",
							"openid": "mhjacks.id.fedoraproject.org"
						},
						"user_id": 2526
					},
					"comment_id": 1185735
				},
				{
					"bug_id": 1700824,
					"comment": {
						"id": 1186030,
						"karma": 1,
						"timestamp": "2020-01-05 13:19:10",
						"update_id": 176492,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/f8bedc4403c299647123b80f29741f3a9b80502dc926749b47d828741d2b474c?s=24&d=retro",
							"email": "da-max@tutanota.com",
							"id": 5270,
							"name": "damax",
							"openid": "damax.id.fedoraproject.org"
						},
						"user_id": 5270
					},
					"comment_id": 1186030
				},
				{
					"bug_id": 1700824,
					"comment": {
						"id": 1188779,
						"karma": 1,
						"text": "Works",
						"timestamp": "2020-01-07 21:06:20",
						"update_id": 176492,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/cd6029d8d81108a2a69c38a2373d2a185c0e86224b8ee4971cd77bb6cdad7a20?s=24&d=retro",
							"email": "walter.pete@yandex.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "ipausers"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "fedorabugs"
								}
							],
							"id": 491,
							"name": "pwalter",
							"openid": "pwalter.id.fedoraproject.org"
						},
						"user_id": 491
					},
					"comment_id": 1188779
				}
			],
			"parent": true,
			"security": true,
			"title": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
			"bugzilla": {
				"bug_id": "1700824",
				"alias": "CVE-2019-11236",
				"creation_ts": "2019-04-17 12:48:04 +0000",
				"short_desc": "CVE-2019-11236 python-urllib3: CRLF injection due to not encoding the '\\r\\n' sequence leading to possible attack on internal service",
				"delta_ts": "2021-12-14 18:47:58 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1697188",
					"1697189",
					"1697190",
					"1697191",
					"1697192",
					"1697193",
					"1700825",
					"1703360",
					"1703361",
					"1703363",
					"1703458",
					"1706762",
					"1707088",
					"1724439",
					"1775363",
					"1775364",
					"1775365",
					"1778100",
					"1778101",
					"1778103",
					"1778107",
					"1778108",
					"1778109",
					"1778113",
					"1778114",
					"1778115",
					"1778116",
					"1778117",
					"1805086",
					"1805087",
					"1805088",
					"1805089",
					"1822420",
					"1822421"
				],
				"blocked": [
					{
						"bug_id": "1700840",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2020:2081",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12647293",
						"comment_count": "0",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2019-04-17 12:48:04 +0000",
						"thetext": "The current implementation of python-urllib3 does not encode the ‘\\r\\n’ sequence in the query string, which allowed the attacker to manipulate a HTTP header with the ‘\\r\\n’ sequence in it, so the attacker could insert arbitrary content to the new line of the HTTP header.\n\nExternal References:\nhttps://bugs.python.org/issue36276"
					},
					{
						"isprivate": "0",
						"commentid": "12647296",
						"comment_count": "1",
						"who": {
							"text": "mrehak",
							"name": "Marian Rehak"
						},
						"bug_when": "2019-04-17 12:48:17 +0000",
						"thetext": "Created python-urllib3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1700825]"
					},
					{
						"isprivate": "0",
						"commentid": "12650233",
						"comment_count": "2",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2019-04-18 11:02:43 +0000",
						"thetext": "Additional references:\n\nhttps://github.com/urllib3/urllib3/issues/1553\nhttps://github.com/urllib3/urllib3/commit/0aa3e24fcd75f1bb59ab159e9f8adb44055b2271"
					},
					{
						"isprivate": "0",
						"commentid": "12670858",
						"comment_count": "8",
						"who": {
							"text": "hvyas",
							"name": "Hardik Vyas"
						},
						"bug_when": "2019-04-26 14:02:44 +0000",
						"thetext": "This issue is reproducible on Red Hat Gluster Storage 3, successfully injected the HTTP header. If an attacker manages to place a CRLF then he could exploit this vulnerability."
					},
					{
						"isprivate": "0",
						"commentid": "12706796",
						"comment_count": "13",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2019-05-06 19:12:41 +0000",
						"thetext": "All supported versions of Red Hat OpenStack Platform are affected by this flaw."
					},
					{
						"isprivate": "0",
						"commentid": "12706798",
						"comment_count": "14",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2019-05-06 19:12:54 +0000",
						"thetext": "Created python-urllib3 tracking bugs for this issue:\n\nAffects: openstack-rdo [bug 1707088]"
					},
					{
						"isprivate": "0",
						"commentid": "13032828",
						"comment_count": "18",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-08-06 12:34:20 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2019:2272 https://access.redhat.com/errata/RHSA-2019:2272"
					},
					{
						"isprivate": "0",
						"commentid": "13036494",
						"comment_count": "19",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2019-08-06 19:20:56 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2019-11236"
					},
					{
						"isprivate": "0",
						"commentid": "13329358",
						"comment_count": "20",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-11-05 20:38:10 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:3335 https://access.redhat.com/errata/RHSA-2019:3335"
					},
					{
						"isprivate": "0",
						"commentid": "13330466",
						"comment_count": "21",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2019-11-05 21:16:11 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2019:3590 https://access.redhat.com/errata/RHSA-2019:3590"
					},
					{
						"isprivate": "0",
						"commentid": "13385697",
						"comment_count": "22",
						"who": {
							"text": "rschiron",
							"name": "Riccardo Schirone"
						},
						"bug_when": "2019-11-21 15:42:57 +0000",
						"thetext": "Upstream patch for 1.24 versions:\nhttps://github.com/urllib3/urllib3/commit/efddd7e7bad26188c3b692d1090cba768afa9162"
					},
					{
						"isprivate": "0",
						"commentid": "13386427",
						"comment_count": "23",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-11-21 19:31:42 +0000",
						"thetext": "There are actually 2 related patches for 1.24:\n\nhttps://github.com/urllib3/urllib3/commit/9b76785331243689a9d52cef3db05ef7462cb02d\nhttps://github.com/urllib3/urllib3/commit/efddd7e7bad26188c3b692d1090cba768afa9162\n\nThe second one is the one linked from comment 22 above, and it needs to be applied on top of the first one.  Both patches mention CVE-2019-9740 in the commit message, which is the CVE for similar problem in urllib/urllib2 that is part of Python standard library."
					},
					{
						"isprivate": "0",
						"commentid": "13386441",
						"comment_count": "24",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-11-21 19:38:11 +0000",
						"thetext": "Created python-pip tracking bugs for this issue:\n\nAffects: epel-6 [bug 1775364]\nAffects: fedora-all [bug 1775363]\n\n\nCreated python-pip-epel tracking bugs for this issue:\n\nAffects: epel-7 [bug 1775365]"
					},
					{
						"isprivate": "0",
						"commentid": "13413010",
						"comment_count": "25",
						"who": {
							"text": "thoger",
							"name": "Tomas Hoger"
						},
						"bug_when": "2019-11-29 10:24:18 +0000",
						"thetext": "Created python-virtualenv tracking bugs for this issue:\n\nAffects: epel-6 [bug 1778101]\nAffects: fedora-30 [bug 1778100]\n\n\nCreated python3-virtualenv tracking bugs for this issue:\n\nAffects: epel-7 [bug 1778103]"
					},
					{
						"isprivate": "0",
						"commentid": "13711385",
						"comment_count": "28",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-03-17 16:18:26 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0850 https://access.redhat.com/errata/RHSA-2020:0850"
					},
					{
						"isprivate": "0",
						"commentid": "13711389",
						"comment_count": "29",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-03-17 16:18:48 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:0851 https://access.redhat.com/errata/RHSA-2020:0851"
					},
					{
						"isprivate": "0",
						"commentid": "13849945",
						"comment_count": "31",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-04-28 15:29:24 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1605 https://access.redhat.com/errata/RHSA-2020:1605"
					},
					{
						"isprivate": "0",
						"commentid": "13851289",
						"comment_count": "32",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-04-28 16:08:45 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2020:1916 https://access.redhat.com/errata/RHSA-2020:1916"
					},
					{
						"isprivate": "0",
						"commentid": "13907633",
						"comment_count": "33",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-05-12 18:37:49 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2068 https://access.redhat.com/errata/RHSA-2020:2068"
					},
					{
						"isprivate": "0",
						"commentid": "13907642",
						"comment_count": "34",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2020-05-12 18:38:05 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2020:2081 https://access.redhat.com/errata/RHSA-2020:2081"
					},
					{
						"isprivate": "0",
						"commentid": "14618909",
						"comment_count": "37",
						"who": {
							"text": "ntait",
							"name": "Nick Tait"
						},
						"bug_when": "2020-12-19 20:40:15 +0000",
						"thetext": "Statement:\n\nThis issue affects the version of python-urllib3 shipped with Red Hat Gluster Storage 3, as it is vulnerable to CRLF injection.\n\nRed Hat Satellite 6.2 is on Maintenance Support 2 phase, hence only selected critical and important issues will be fixed. Please refer to Red Hat Satellite Product Life Cycle page for more information.\n\nIn Red Hat OpenStack Platform 13, because the flaw has a lower impact and the fix would require a substantial amount of development, no update will be provided at this time for the RHOSP python-urllib3 package."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3-virtualenv-15.1.0-5.el7",
			"release_id": 8,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-virtualenv-doc",
						"version": "15.1.0",
						"release": "5.el7",
						"arch": "noarch"
					},
					{
						"name": "python36-virtualenv",
						"version": "15.1.0",
						"release": "5.el7",
						"arch": "noarch"
					},
					{
						"name": "python34-virtualenv",
						"version": "15.1.0",
						"release": "5.el7",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python3-virtualenv",
						"version": "15.1.0",
						"release": "5.el7",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 1229290,
			"text": "This update has been submitted for testing by orion. ",
			"timestamp": "2020-02-11 14:28:39",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1229291,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2020-02-11 14:28:41",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1229292,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2020-02-11 14:28:45",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1229595,
			"text": "This update has been pushed to testing.",
			"timestamp": "2020-02-12 00:10:47",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1255833,
			"text": "This update can be pushed to stable now if the maintainer wishes",
			"timestamp": "2020-02-26 00:12:07",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1255834,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2020-02-26 00:12:07",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 1257701,
			"text": "This update has been pushed to stable.",
			"timestamp": "2020-02-27 15:51:14",
			"update_id": 183887,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2020-02-27 15:51:09",
	"date_stable": "2020-02-27 15:51:09",
	"date_submitted": "2020-02-11 14:28:38",
	"date_testing": "2020-02-12 00:10:43",
	"meets_testing_requirements": true,
	"notes": "Fix CVE-2018-20060 and CVE-2019-11236 in bundled urllib3",
	"pushed": true,
	"release": {
		"branch": "epel7",
		"candidate_tag": "epel7-testing-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "epel7",
		"id_prefix": "FEDORA-EPEL",
		"long_name": "Fedora EPEL 7",
		"mail_template": "fedora_epel_legacy_errata_template",
		"name": "EPEL-7",
		"override_tag": "epel7-override",
		"package_manager": "unspecified",
		"pending_signing_tag": "epel7-signing-pending",
		"pending_stable_tag": "epel7-pending",
		"pending_testing_tag": "epel7-testing-pending",
		"stable_tag": "epel7",
		"state": "archived",
		"testing_tag": "epel7-testing",
		"version": "7"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 14,
	"stable_karma": 2,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3-virtualenv-15.1.0-5.el7",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-88a247cda8",
	"unstable_karma": -3,
	"updateid": "FEDORA-EPEL-2020-88a247cda8",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/b6fd449fcea49e2de27dacf226d46a01a0c8a44918672843e45bf5ac0bd0060b?s=24&d=retro",
		"email": "orion@nwra.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "astro-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "epel-packagers-sig"
			},
			{
				"name": "scitech_sig"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "scitech"
			},
			{
				"name": "clamav"
			}
		],
		"id": 97,
		"name": "orion",
		"openid": "orion.id.fedoraproject.org"
	},
	"version_hash": "f3c72d267a2424b6a770139a47b8ff7f03302521"
}
