{
	"alias": "FEDORA-2022-cae8089f93",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2140200,
			"parent": true,
			"security": true,
			"title": "CVE-2022-37454 XKCP: buffer overflow in the SHA-3 reference implementation",
			"bugzilla": {
				"bug_id": "2140200",
				"alias": "CVE-2022-37454",
				"creation_ts": "2022-11-04 19:16:33 +0000",
				"short_desc": "CVE-2022-37454 XKCP: buffer overflow in the SHA-3 reference implementation",
				"delta_ts": "2024-03-20 10:16:42 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security",
				"priority": "high",
				"bug_severity": "high",
				"depends_on": [
					"2141754",
					"2141755",
					"2141756",
					"2141757",
					"2141758",
					"2141759",
					"2141760",
					"2141761",
					"2141762",
					"2141763",
					"2141764",
					"2141766",
					"2141812",
					"2141813",
					"2141814",
					"2141815",
					"2141816",
					"2141818",
					"2141819",
					"2161670",
					"2161671"
				],
				"blocked": [
					{
						"bug_id": "2137582",
						"error": "NotPermitted"
					}
				],
				"external_bugs": {
					"text": "RHSA-2023:2903",
					"name": "Red Hat Product Errata"
				},
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16756570",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-04 19:16:33 +0000",
						"thetext": "The Keccak XKCP SHA-3 reference implementation before fdc6fef has an integer overflow and resultant buffer overflow that allows attackers to execute arbitrary code or eliminate expected cryptographic properties. This occurs in the sponge function interface.\n\nReferences:\nhttps://github.com/XKCP/XKCP/security/advisories/GHSA-6w4m-2xhg-2658\nhttps://mouha.be/sha-3-buffer-overflow/"
					},
					{
						"isprivate": "0",
						"commentid": "16759293",
						"comment_count": "1",
						"who": {
							"text": "vondruch",
							"name": "Vít Ondruch"
						},
						"bug_when": "2022-11-07 10:01:02 +0000",
						"thetext": "I can just guess that Ruby maintainers were added on the CC due to \"SHA3 for Ruby\" being mentioned at the second reference. If that is the case, I'd just like to point out that this library is not in Fedora neither in RHEL, therefore this is not of our interest."
					},
					{
						"isprivate": "0",
						"commentid": "16759709",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2022-11-07 11:33:52 +0000",
						"thetext": "This affects Fedora's Python 3.6, 3.7, 3.8, and PyPy 3.*.\n\nPython 3.9+ is not affected in Fedora, as it uses the OpenSSL implementation.\nPython 3.11 is not affected even upstream: Python 3.11 switched to using a different sha3 implementation as a fallback.\n\nPython/PyPy 2 does not seem to support Keccak.\n\nSee https://github.com/python/cpython/issues/98517"
					},
					{
						"isprivate": "0",
						"commentid": "16771085",
						"comment_count": "3",
						"who": {
							"text": "pviktori",
							"name": "Petr Viktorin (pviktori)"
						},
						"bug_when": "2022-11-09 13:45:02 +0000",
						"thetext": "Python in RHEL is not affected: our RHEL-only hashlib patches remove the fallbacks, so only OpenSSL is used there."
					},
					{
						"isprivate": "0",
						"commentid": "16771795",
						"comment_count": "4",
						"who": {
							"text": "jaruga",
							"name": "Jun Aruga"
						},
						"bug_when": "2022-11-09 17:55:19 +0000",
						"thetext": "> I can just guess that Ruby maintainers were added on the CC due to \"SHA3 for Ruby\" being mentioned at the second reference. If that is the case, I'd just like to point out that this library is not in Fedora neither in RHEL, therefore this is not of our interest.\n\nYes. In the second reference, the sentence for Ruby is below. There is no RPM package for the \"SHA3 for Ruby\" (sha3 gem package) on both Fedora and RHEL.\n\nhttps://mouha.be/sha-3-buffer-overflow/\n> The vulnerability has been assigned CVE-2022-37454 and bug reports are available for Python, PHP, PyPy, pysha3, SHA3 for Ruby, and XKCP.\n=> https://github.com/johanns/sha3/issues/17\n=> https://rubygems.org/gems/sha3"
					},
					{
						"isprivate": "0",
						"commentid": "16773184",
						"comment_count": "5",
						"who": {
							"text": "rcollet",
							"name": "Remi Collet"
						},
						"bug_when": "2022-11-10 09:04:02 +0000",
						"thetext": "Notice: the PHP security team doesn't consider this issue as a security vulnerability as it requires to be exploited some bad configuration (memory_limit). So any sane configuration protects from it."
					},
					{
						"isprivate": "0",
						"commentid": "16774662",
						"comment_count": "6",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 17:36:53 +0000",
						"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141755]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141756]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141757]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141758]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141759]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 2141754]"
					},
					{
						"isprivate": "0",
						"commentid": "16774678",
						"comment_count": "7",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 17:42:30 +0000",
						"thetext": "Created pypy tracking bugs for this issue:\n\nAffects: epel-all [bug 2141761]\nAffects: fedora-all [bug 2141760]\n\n\nCreated pypy3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141762]\n\n\nCreated pypy3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141763]\n\n\nCreated pypy3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141764]"
					},
					{
						"isprivate": "0",
						"commentid": "16774691",
						"comment_count": "8",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 17:49:37 +0000",
						"thetext": "Created php tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141766]"
					},
					{
						"isprivate": "0",
						"commentid": "16774941",
						"comment_count": "11",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 19:26:24 +0000",
						"thetext": "Created rust-keccak tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141818]\n\n\nCreated rust-tiny-keccak tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141819]"
					},
					{
						"isprivate": "0",
						"commentid": "16774996",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-10 19:53:52 +0000",
						"thetext": "FEDORA-2022-17bc21cf38 has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16783069",
						"comment_count": "13",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2022-11-14 17:37:30 +0000",
						"thetext": "For the record, any Python older than 3.6 does not even support SHA-3 and hence is not affected. I've verified this in python37 @ epel7 package [bug 2141754]."
					},
					{
						"isprivate": "0",
						"commentid": "16783070",
						"comment_count": "14",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2022-11-14 17:38:13 +0000",
						"thetext": "(In reply to Miro Hrončok from comment #13)\n> For the record, any Python older than 3.6 does not even support SHA-3 and\n> hence is not affected. I've verified this in python37 @ epel7 package [bug\n> 2141754].\n\nCorrection: I've verified this in python34 @ epel7 package [bug 2141754]."
					},
					{
						"isprivate": "0",
						"commentid": "17063107",
						"comment_count": "15",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-02-21 09:31:13 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:0848 https://access.redhat.com/errata/RHSA-2023:0848"
					},
					{
						"isprivate": "0",
						"commentid": "17079937",
						"comment_count": "16",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-02-28 08:20:44 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:0965 https://access.redhat.com/errata/RHSA-2023:0965"
					},
					{
						"isprivate": "0",
						"commentid": "17257494",
						"comment_count": "17",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-09 07:45:36 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:2417 https://access.redhat.com/errata/RHSA-2023:2417"
					},
					{
						"isprivate": "0",
						"commentid": "17288063",
						"comment_count": "18",
						"who": {
							"text": "errata-xmlrpc",
							"name": "errata-xmlrpc"
						},
						"bug_when": "2023-05-16 08:26:30 +0000",
						"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:2903 https://access.redhat.com/errata/RHSA-2023:2903"
					},
					{
						"isprivate": "0",
						"commentid": "17292983",
						"comment_count": "19",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2023-05-17 02:31:29 +0000",
						"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-37454"
					}
				]
			}
		},
		{
			"bug_id": 2141757,
			"security": true,
			"title": "CVE-2022-37454 python3.6: XKCP: buffer overflow in the SHA-3 reference implementation [fedora-all]",
			"bugzilla": {
				"bug_id": "2141757",
				"creation_ts": "2022-11-10 17:36:33 +0000",
				"short_desc": "CVE-2022-37454 python3.6: XKCP: buffer overflow in the SHA-3 reference implementation [fedora-all]",
				"delta_ts": "2022-11-21 01:13:23 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "high",
				"bug_severity": "high",
				"blocked": [
					{
						"bug_id": "2140200",
						"alias": "CVE-2022-37454",
						"creation_ts": "2022-11-04 19:16:33 +0000",
						"short_desc": "CVE-2022-37454 XKCP: buffer overflow in the SHA-3 reference implementation",
						"delta_ts": "2024-03-20 10:16:42 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "high",
						"bug_severity": "high",
						"depends_on": [
							"2141754",
							"2141755",
							"2141756",
							"2141757",
							"2141758",
							"2141759",
							"2141760",
							"2141761",
							"2141762",
							"2141763",
							"2141764",
							"2141766",
							"2141812",
							"2141813",
							"2141814",
							"2141815",
							"2141816",
							"2141818",
							"2141819",
							"2161670",
							"2161671"
						],
						"blocked": [
							{
								"bug_id": "2137582",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2023:2903",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "16756570",
								"comment_count": "0",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2022-11-04 19:16:33 +0000",
								"thetext": "The Keccak XKCP SHA-3 reference implementation before fdc6fef has an integer overflow and resultant buffer overflow that allows attackers to execute arbitrary code or eliminate expected cryptographic properties. This occurs in the sponge function interface.\n\nReferences:\nhttps://github.com/XKCP/XKCP/security/advisories/GHSA-6w4m-2xhg-2658\nhttps://mouha.be/sha-3-buffer-overflow/"
							},
							{
								"isprivate": "0",
								"commentid": "16759293",
								"comment_count": "1",
								"who": {
									"text": "vondruch",
									"name": "Vít Ondruch"
								},
								"bug_when": "2022-11-07 10:01:02 +0000",
								"thetext": "I can just guess that Ruby maintainers were added on the CC due to \"SHA3 for Ruby\" being mentioned at the second reference. If that is the case, I'd just like to point out that this library is not in Fedora neither in RHEL, therefore this is not of our interest."
							},
							{
								"isprivate": "0",
								"commentid": "16759709",
								"comment_count": "2",
								"who": {
									"text": "mhroncok",
									"name": "Miro Hrončok"
								},
								"bug_when": "2022-11-07 11:33:52 +0000",
								"thetext": "This affects Fedora's Python 3.6, 3.7, 3.8, and PyPy 3.*.\n\nPython 3.9+ is not affected in Fedora, as it uses the OpenSSL implementation.\nPython 3.11 is not affected even upstream: Python 3.11 switched to using a different sha3 implementation as a fallback.\n\nPython/PyPy 2 does not seem to support Keccak.\n\nSee https://github.com/python/cpython/issues/98517"
							},
							{
								"isprivate": "0",
								"commentid": "16771085",
								"comment_count": "3",
								"who": {
									"text": "pviktori",
									"name": "Petr Viktorin (pviktori)"
								},
								"bug_when": "2022-11-09 13:45:02 +0000",
								"thetext": "Python in RHEL is not affected: our RHEL-only hashlib patches remove the fallbacks, so only OpenSSL is used there."
							},
							{
								"isprivate": "0",
								"commentid": "16771795",
								"comment_count": "4",
								"who": {
									"text": "jaruga",
									"name": "Jun Aruga"
								},
								"bug_when": "2022-11-09 17:55:19 +0000",
								"thetext": "> I can just guess that Ruby maintainers were added on the CC due to \"SHA3 for Ruby\" being mentioned at the second reference. If that is the case, I'd just like to point out that this library is not in Fedora neither in RHEL, therefore this is not of our interest.\n\nYes. In the second reference, the sentence for Ruby is below. There is no RPM package for the \"SHA3 for Ruby\" (sha3 gem package) on both Fedora and RHEL.\n\nhttps://mouha.be/sha-3-buffer-overflow/\n> The vulnerability has been assigned CVE-2022-37454 and bug reports are available for Python, PHP, PyPy, pysha3, SHA3 for Ruby, and XKCP.\n=> https://github.com/johanns/sha3/issues/17\n=> https://rubygems.org/gems/sha3"
							},
							{
								"isprivate": "0",
								"commentid": "16773184",
								"comment_count": "5",
								"who": {
									"text": "rcollet",
									"name": "Remi Collet"
								},
								"bug_when": "2022-11-10 09:04:02 +0000",
								"thetext": "Notice: the PHP security team doesn't consider this issue as a security vulnerability as it requires to be exploited some bad configuration (memory_limit). So any sane configuration protects from it."
							},
							{
								"isprivate": "0",
								"commentid": "16774662",
								"comment_count": "6",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2022-11-10 17:36:53 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141755]\n\n\nCreated python2.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141756]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141757]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141758]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141759]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 2141754]"
							},
							{
								"isprivate": "0",
								"commentid": "16774678",
								"comment_count": "7",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2022-11-10 17:42:30 +0000",
								"thetext": "Created pypy tracking bugs for this issue:\n\nAffects: epel-all [bug 2141761]\nAffects: fedora-all [bug 2141760]\n\n\nCreated pypy3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141762]\n\n\nCreated pypy3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141763]\n\n\nCreated pypy3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141764]"
							},
							{
								"isprivate": "0",
								"commentid": "16774691",
								"comment_count": "8",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2022-11-10 17:49:37 +0000",
								"thetext": "Created php tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141766]"
							},
							{
								"isprivate": "0",
								"commentid": "16774941",
								"comment_count": "11",
								"who": {
									"text": "gsuckevi",
									"name": "Guilherme de Almeida Suckevicz"
								},
								"bug_when": "2022-11-10 19:26:24 +0000",
								"thetext": "Created rust-keccak tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141818]\n\n\nCreated rust-tiny-keccak tracking bugs for this issue:\n\nAffects: fedora-all [bug 2141819]"
							},
							{
								"isprivate": "0",
								"commentid": "16774996",
								"comment_count": "12",
								"who": {
									"text": "updates",
									"name": "Fedora Update System"
								},
								"bug_when": "2022-11-10 19:53:52 +0000",
								"thetext": "FEDORA-2022-17bc21cf38 has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
							},
							{
								"isprivate": "0",
								"commentid": "16783069",
								"comment_count": "13",
								"who": {
									"text": "mhroncok",
									"name": "Miro Hrončok"
								},
								"bug_when": "2022-11-14 17:37:30 +0000",
								"thetext": "For the record, any Python older than 3.6 does not even support SHA-3 and hence is not affected. I've verified this in python37 @ epel7 package [bug 2141754]."
							},
							{
								"isprivate": "0",
								"commentid": "16783070",
								"comment_count": "14",
								"who": {
									"text": "mhroncok",
									"name": "Miro Hrončok"
								},
								"bug_when": "2022-11-14 17:38:13 +0000",
								"thetext": "(In reply to Miro Hrončok from comment #13)\n> For the record, any Python older than 3.6 does not even support SHA-3 and\n> hence is not affected. I've verified this in python37 @ epel7 package [bug\n> 2141754].\n\nCorrection: I've verified this in python34 @ epel7 package [bug 2141754]."
							},
							{
								"isprivate": "0",
								"commentid": "17063107",
								"comment_count": "15",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-02-21 09:31:13 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:0848 https://access.redhat.com/errata/RHSA-2023:0848"
							},
							{
								"isprivate": "0",
								"commentid": "17079937",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-02-28 08:20:44 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:0965 https://access.redhat.com/errata/RHSA-2023:0965"
							},
							{
								"isprivate": "0",
								"commentid": "17257494",
								"comment_count": "17",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-05-09 07:45:36 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2023:2417 https://access.redhat.com/errata/RHSA-2023:2417"
							},
							{
								"isprivate": "0",
								"commentid": "17288063",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2023-05-16 08:26:30 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2023:2903 https://access.redhat.com/errata/RHSA-2023:2903"
							},
							{
								"isprivate": "0",
								"commentid": "17292983",
								"comment_count": "19",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2023-05-17 02:31:29 +0000",
								"thetext": "This bug is now closed. Further updates for individual products will be reflected on the CVE page(s):\n\nhttps://access.redhat.com/security/cve/cve-2022-37454"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "16774656",
						"comment_count": "0",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 17:36:33 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2140200\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "16774657",
						"comment_count": "1",
						"who": {
							"text": "gsuckevi",
							"name": "Guilherme de Almeida Suckevicz"
						},
						"bug_when": "2022-11-10 17:36:35 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2140200,2141757\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "16774781",
						"comment_count": "2",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hrončok"
						},
						"bug_when": "2022-11-10 18:03:01 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python3.6/pull-request/63\nhttps://src.fedoraproject.org/rpms/python3.6/pull-request/64\nhttps://src.fedoraproject.org/rpms/python3.6/pull-request/65\nhttps://src.fedoraproject.org/rpms/python3.6/pull-request/66"
					},
					{
						"isprivate": "0",
						"commentid": "16774991",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-10 19:49:18 +0000",
						"thetext": "FEDORA-2022-17bc21cf38 has been submitted as an update to Fedora 38. https://bodhi.fedoraproject.org/updates/FEDORA-2022-17bc21cf38"
					},
					{
						"isprivate": "0",
						"commentid": "16774993",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-10 19:50:03 +0000",
						"thetext": "FEDORA-2022-cae8089f93 has been submitted as an update to Fedora 37. https://bodhi.fedoraproject.org/updates/FEDORA-2022-cae8089f93"
					},
					{
						"isprivate": "0",
						"commentid": "16774997",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-10 19:53:55 +0000",
						"thetext": "FEDORA-2022-17bc21cf38 has been pushed to the Fedora 38 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16776025",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-11 00:56:24 +0000",
						"thetext": "FEDORA-2022-104076b1d8 has been submitted as an update to Fedora 36. https://bodhi.fedoraproject.org/updates/FEDORA-2022-104076b1d8"
					},
					{
						"isprivate": "0",
						"commentid": "16776791",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-11 10:27:18 +0000",
						"thetext": "FEDORA-2022-004b185fa4 has been submitted as an update to Fedora 35. https://bodhi.fedoraproject.org/updates/FEDORA-2022-004b185fa4"
					},
					{
						"isprivate": "0",
						"commentid": "16778971",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-12 04:19:16 +0000",
						"thetext": "FEDORA-2022-cae8089f93 has been pushed to the Fedora 37 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-cae8089f93`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-cae8089f93\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16779805",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-13 02:38:23 +0000",
						"thetext": "FEDORA-2022-004b185fa4 has been pushed to the Fedora 35 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-004b185fa4`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-004b185fa4\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16779814",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-13 02:38:55 +0000",
						"thetext": "FEDORA-2022-104076b1d8 has been pushed to the Fedora 36 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2022-104076b1d8`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2022-104076b1d8\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "16804164",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-20 01:23:03 +0000",
						"thetext": "FEDORA-2022-cae8089f93 has been pushed to the Fedora 37 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16805033",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-21 00:50:55 +0000",
						"thetext": "FEDORA-2022-004b185fa4 has been pushed to the Fedora 35 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "16805094",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2022-11-21 01:13:23 +0000",
						"thetext": "FEDORA-2022-104076b1d8 has been pushed to the Fedora 36 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.6-3.6.15-14.fc37",
			"release_id": 62,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.6-debugsource",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "aarch64"
					},
					{
						"name": "python3.6-debuginfo",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "aarch64"
					},
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.6-debugsource",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "i686"
					},
					{
						"name": "python3.6-debuginfo",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "i686"
					},
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.6-debugsource",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "python3.6-debuginfo",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "ppc64le"
					},
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.6-debugsource",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "s390x"
					},
					{
						"name": "python3.6-debuginfo",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "s390x"
					},
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.6-debugsource",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "x86_64"
					},
					{
						"name": "python3.6-debuginfo",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "x86_64"
					},
					{
						"name": "python3.6",
						"version": "3.6.15",
						"release": "14.fc37",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 2780424,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2022-11-10 19:50:00",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2780425,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2022-11-10 19:50:00",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2782550,
			"text": "This update has been pushed to testing.",
			"timestamp": "2022-11-12 04:19:25",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2784450,
			"text": "churchyard edited this update.",
			"timestamp": "2022-11-14 17:50:35",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2790383,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2022-11-19 04:19:48",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 2790716,
			"text": "This update has been pushed to stable.",
			"timestamp": "2022-11-20 01:23:33",
			"update_id": 460307,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_modified": "2022-11-14 17:50:35",
	"date_pushed": "2022-11-20 01:22:45",
	"date_stable": "2022-11-20 01:22:45",
	"date_submitted": "2022-11-10 19:49:59",
	"date_testing": "2022-11-12 04:19:02",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2022-37454.\n",
	"pushed": true,
	"release": {
		"branch": "f37",
		"candidate_tag": "f37-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f37",
		"eol": "2023-12-05",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 37",
		"mail_template": "fedora_errata_template",
		"name": "F37",
		"override_tag": "f37-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f37-signing-pending",
		"pending_stable_tag": "f37-updates-pending",
		"pending_testing_tag": "f37-updates-testing-pending",
		"stable_tag": "f37-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f37-updates-testing",
		"version": "37"
	},
	"require_testcases": true,
	"severity": "high",
	"stable_days": 7,
	"stable_karma": 1,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.6-3.6.15-14.fc37",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2022-cae8089f93",
	"unstable_karma": -1,
	"updateid": "FEDORA-2022-cae8089f93",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/e221b70024cf971d8b43de0260d2babde9179cdf72605bf3168420e3efe07423?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "2e6bc49a83a9897adabe5ffbfb1f449dd4bcedfc"
}
