{
	"alias": "FEDORA-2024-f247f05e2e",
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2293391,
			"security": true,
			"title": "CVE-2024-4032 python3.11: python: incorrect IPv4 and IPv6 private ranges [fedora-all]",
			"bugzilla": {
				"bug_id": "2293391",
				"creation_ts": "2024-06-20 14:45:00 +0000",
				"short_desc": "CVE-2024-4032 python3.11: python: incorrect IPv4 and IPv6 private ranges [fedora-all]",
				"delta_ts": "2024-08-25 04:44:06 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "low",
				"bug_severity": "low",
				"blocked": [
					{
						"bug_id": "2292921",
						"alias": "CVE-2024-4032",
						"creation_ts": "2024-06-18 16:50:01 +0000",
						"short_desc": "CVE-2024-4032 python: incorrect IPv4 and IPv6 private ranges",
						"delta_ts": "2024-10-03 13:31:57 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"2293387",
							"2293389",
							"2293390",
							"2293391",
							"2293392",
							"2293393",
							"2293394",
							"2293395",
							"2293396",
							"2293397"
						],
						"blocked": [
							{
								"bug_id": "2292923",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2024:7417",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18071193",
								"comment_count": "0",
								"who": {
									"text": "rgatica",
									"name": "Robb Gatica"
								},
								"bug_when": "2024-06-18 16:50:01 +0000",
								"thetext": "The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the 'is_private' and 'is_global' properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.\n\nReferences:\nhttps://github.com/python/cpython/issues/113171\nhttps://github.com/python/cpython/pull/113179\nhttps://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml\nhttps://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"
							},
							{
								"isprivate": "0",
								"commentid": "18074054",
								"comment_count": "1",
								"who": {
									"text": "rgatica",
									"name": "Robb Gatica"
								},
								"bug_when": "2024-06-20 14:50:59 +0000",
								"thetext": "Created mingw-python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293389]\n\n\nCreated python3.10 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293390]\n\n\nCreated python3.11 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293391]\n\n\nCreated python3.12 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293392]\n\n\nCreated python3.13 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293393]\n\n\nCreated python3.6 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293394]\n\n\nCreated python3.7 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293395]\n\n\nCreated python3.8 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293396]\n\n\nCreated python3.9 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2293397]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: epel-all [bug 2293387]"
							},
							{
								"isprivate": "0",
								"commentid": "18107121",
								"comment_count": "6",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-23 16:23:27 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:4766 https://access.redhat.com/errata/RHSA-2024:4766"
							},
							{
								"isprivate": "0",
								"commentid": "18107124",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-23 16:24:17 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:4779 https://access.redhat.com/errata/RHSA-2024:4779"
							},
							{
								"isprivate": "0",
								"commentid": "18165596",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-08-28 18:51:58 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:5962 https://access.redhat.com/errata/RHSA-2024:5962"
							},
							{
								"isprivate": "0",
								"commentid": "18166233",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-08-29 11:48:13 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.8 Extended Update Support\n\nVia RHSA-2024:6030 https://access.redhat.com/errata/RHSA-2024:6030"
							},
							{
								"isprivate": "0",
								"commentid": "18199599",
								"comment_count": "10",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6961 https://access.redhat.com/errata/RHSA-2024:6961"
							},
							{
								"isprivate": "0",
								"commentid": "18199604",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:49 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6962 https://access.redhat.com/errata/RHSA-2024:6962"
							},
							{
								"isprivate": "0",
								"commentid": "18199946",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 02:58:32 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6975 https://access.redhat.com/errata/RHSA-2024:6975"
							},
							{
								"isprivate": "0",
								"commentid": "18208919",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-10-01 00:40:28 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.6 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.6 Telecommunications Update Service\n\nVia RHSA-2024:7417 https://access.redhat.com/errata/RHSA-2024:7417"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18074026",
						"comment_count": "0",
						"who": {
							"text": "rgatica",
							"name": "Robb Gatica"
						},
						"bug_when": "2024-06-20 14:45:00 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2292921\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18074027",
						"comment_count": "1",
						"who": {
							"text": "rgatica",
							"name": "Robb Gatica"
						},
						"bug_when": "2024-06-20 14:45:03 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=low\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2292921,2293391\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "18153243",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 20:19:54 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c (python3.11-3.11.9-5.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-a4c978fa1c"
					},
					{
						"isprivate": "0",
						"commentid": "18153306",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 22:24:57 +0000",
						"thetext": "FEDORA-2024-f247f05e2e (python3.11-3.11.9-5.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-f247f05e2e"
					},
					{
						"isprivate": "0",
						"commentid": "18153312",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 22:57:02 +0000",
						"thetext": "FEDORA-2024-d3d904cb56 (python3.11-3.11.9-5.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-d3d904cb56"
					},
					{
						"isprivate": "0",
						"commentid": "18153324",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 23:26:35 +0000",
						"thetext": "FEDORA-2024-bed028af54 (python3.11-3.11.9-5.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-bed028af54"
					},
					{
						"isprivate": "0",
						"commentid": "18153398",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 01:49:56 +0000",
						"thetext": "FEDORA-2024-f247f05e2e (python3.11-3.11.9-5.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18153402",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 01:52:28 +0000",
						"thetext": "FEDORA-2024-d3d904cb56 (python3.11-3.11.9-5.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18153478",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 06:55:09 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-a4c978fa1c`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-a4c978fa1c\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18153864",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-18 02:42:54 +0000",
						"thetext": "FEDORA-2024-bed028af54 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-bed028af54`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-bed028af54\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18161599",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-25 02:02:13 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c (python3.11-3.11.9-5.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18161640",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-25 04:44:06 +0000",
						"thetext": "FEDORA-2024-bed028af54 (python3.11-3.11.9-5.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 2303158,
			"security": true,
			"title": "CVE-2024-6923 python3.11: email module doesn't properly quotes newlines in email headers, allowing header injection [fedora-all]",
			"bugzilla": {
				"bug_id": "2303158",
				"creation_ts": "2024-08-06 13:44:23 +0000",
				"short_desc": "CVE-2024-6923 python3.11: email module doesn't properly quotes newlines in email headers, allowing header injection [fedora-all]",
				"delta_ts": "2024-08-25 04:44:09 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2302255",
						"alias": "CVE-2024-6923",
						"creation_ts": "2024-08-01 14:30:31 +0000",
						"short_desc": "CVE-2024-6923 cpython: python: email module doesn't properly quotes newlines in email headers, allowing header injection",
						"delta_ts": "2024-10-03 13:32:04 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2303156",
							"2303162",
							"2303155",
							"2303157",
							"2303158",
							"2303159",
							"2303160",
							"2303161",
							"2303163",
							"2303164"
						],
						"external_bugs": {
							"text": "RHSA-2024:7415",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18125651",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2024-08-01 14:30:31 +0000",
								"thetext": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized."
							},
							{
								"isprivate": "0",
								"commentid": "18165594",
								"comment_count": "2",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-08-28 18:51:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:5962 https://access.redhat.com/errata/RHSA-2024:5962"
							},
							{
								"isprivate": "0",
								"commentid": "18171664",
								"comment_count": "3",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-03 02:21:11 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:6146 https://access.redhat.com/errata/RHSA-2024:6146"
							},
							{
								"isprivate": "0",
								"commentid": "18172909",
								"comment_count": "4",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-03 17:46:40 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:6163 https://access.redhat.com/errata/RHSA-2024:6163"
							},
							{
								"isprivate": "0",
								"commentid": "18173026",
								"comment_count": "5",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-03 19:53:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:6179 https://access.redhat.com/errata/RHSA-2024:6179"
							},
							{
								"isprivate": "0",
								"commentid": "18198160",
								"comment_count": "6",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-23 01:47:40 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.6 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.6 Telecommunications Update Service\n\nVia RHSA-2024:6915 https://access.redhat.com/errata/RHSA-2024:6915"
							},
							{
								"isprivate": "0",
								"commentid": "18198168",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-23 01:54:52 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.2 Extended Update Support\n\nVia RHSA-2024:6909 https://access.redhat.com/errata/RHSA-2024:6909"
							},
							{
								"isprivate": "0",
								"commentid": "18199600",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:30 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6961 https://access.redhat.com/errata/RHSA-2024:6961"
							},
							{
								"isprivate": "0",
								"commentid": "18199603",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 00:48:49 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6962 https://access.redhat.com/errata/RHSA-2024:6962"
							},
							{
								"isprivate": "0",
								"commentid": "18199947",
								"comment_count": "10",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-24 02:58:32 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:6975 https://access.redhat.com/errata/RHSA-2024:6975"
							},
							{
								"isprivate": "0",
								"commentid": "18202421",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-25 18:33:21 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2024:7137 https://access.redhat.com/errata/RHSA-2024:7137"
							},
							{
								"isprivate": "0",
								"commentid": "18203574",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-26 13:28:33 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Service Interconnect 1.4 for RHEL 9\n\nVia RHSA-2024:7213 https://access.redhat.com/errata/RHSA-2024:7213"
							},
							{
								"isprivate": "0",
								"commentid": "18208052",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-09-30 10:26:16 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Service Interconnect 1 for RHEL 9\n\nVia RHSA-2024:7374 https://access.redhat.com/errata/RHSA-2024:7374"
							},
							{
								"isprivate": "0",
								"commentid": "18209111",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-10-01 02:29:26 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.2 Extended Update Support\n\nVia RHSA-2024:7415 https://access.redhat.com/errata/RHSA-2024:7415"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18134967",
						"comment_count": "0",
						"who": {
							"text": "mbenatto",
							"name": "Marco Benatto"
						},
						"bug_when": "2024-08-06 13:44:23 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2302255\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18153244",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 20:19:56 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c (python3.11-3.11.9-5.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-a4c978fa1c"
					},
					{
						"isprivate": "0",
						"commentid": "18153307",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 22:25:00 +0000",
						"thetext": "FEDORA-2024-f247f05e2e (python3.11-3.11.9-5.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-f247f05e2e"
					},
					{
						"isprivate": "0",
						"commentid": "18153313",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 22:57:05 +0000",
						"thetext": "FEDORA-2024-d3d904cb56 (python3.11-3.11.9-5.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-d3d904cb56"
					},
					{
						"isprivate": "0",
						"commentid": "18153325",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-16 23:26:38 +0000",
						"thetext": "FEDORA-2024-bed028af54 (python3.11-3.11.9-5.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-bed028af54"
					},
					{
						"isprivate": "0",
						"commentid": "18153399",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 01:50:02 +0000",
						"thetext": "FEDORA-2024-f247f05e2e (python3.11-3.11.9-5.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18153403",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 01:52:30 +0000",
						"thetext": "FEDORA-2024-d3d904cb56 (python3.11-3.11.9-5.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18153479",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-17 06:55:11 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-a4c978fa1c`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-a4c978fa1c\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18153865",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-18 02:42:57 +0000",
						"thetext": "FEDORA-2024-bed028af54 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-bed028af54`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-bed028af54\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18161600",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-25 02:02:15 +0000",
						"thetext": "FEDORA-2024-a4c978fa1c (python3.11-3.11.9-5.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18161641",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-08-25 04:44:09 +0000",
						"thetext": "FEDORA-2024-bed028af54 (python3.11-3.11.9-5.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.11-3.11.9-5.fc42",
			"release_id": 84,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-devel",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-idle",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-tkinter",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-debugsource",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-debug",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-debuginfo",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-libs",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.11-test",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.11-debugsource",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-debuginfo",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-test",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-libs",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-debug",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-idle",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-tkinter",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11-devel",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.11-tkinter",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-devel",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-debugsource",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-debuginfo",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-debug",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-idle",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-libs",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11-test",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.11-debugsource",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-libs",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-test",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-debuginfo",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-debug",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-idle",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-tkinter",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11-devel",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.11-debugsource",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-devel",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-tkinter",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-idle",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-debug",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-debuginfo",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-libs",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.11-test",
						"version": "3.11.9",
						"release": "5.fc42",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3678921,
			"text": "This update was automatically created",
			"timestamp": "2024-08-16 22:24:54",
			"update_id": 640745,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3678922,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-08-16 22:25:05",
			"update_id": 640745,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3679093,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2024-08-17 01:49:02",
			"update_id": 640745,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3679094,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-08-17 01:49:02",
			"update_id": 640745,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3679099,
			"text": "This update has been submitted for stable by bodhi",
			"timestamp": "2024-08-17 01:49:53",
			"update_id": 640745,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2024-08-17 01:49:53",
	"date_pushed": "2024-08-17 01:49:53",
	"date_stable": "2024-08-17 01:49:53",
	"date_submitted": "2024-08-16 22:24:54",
	"date_testing": "2024-08-17 01:49:02",
	"meets_testing_requirements": true,
	"notes": "Automatic update for python3.11-3.11.9-5.fc42.\n\n##### **Changelog**\n\n```\n* Thu Aug 15 2024 Charalampos Stratakis <cstratak@redhat.com> - 3.11.9-5\n- Security fix for CVE-2024-4032 (rhbz#2293391)\n- Security fix for CVE-2024-6923 (rhbz#2303158)\n\n```",
	"pushed": true,
	"release": {
		"branch": "rawhide",
		"candidate_tag": "f42-updates-candidate",
		"create_automatic_updates": true,
		"dist_tag": "f42",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 42",
		"mail_template": "fedora_errata_template",
		"name": "F42",
		"override_tag": "f42-override",
		"package_manager": "unspecified",
		"pending_signing_tag": "f42-signing-pending",
		"pending_stable_tag": "f42-updates-pending",
		"pending_testing_tag": "f42-updates-testing-pending",
		"stable_tag": "f42",
		"state": "pending",
		"testing_tag": "f42-updates-testing",
		"version": "42"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.11-3.11.9-5.fc42",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2024-f247f05e2e",
	"unstable_karma": -3,
	"updateid": "FEDORA-2024-f247f05e2e",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/4bac0f6fccba44f6c476a5dd70dab5ecd3c5fc237db5b9c3af91be34b84a5758?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "23ca907d432ff41438a986ab12871d73e587c97c"
}
