{
	"alias": "FEDORA-2024-39f0ccfbc3",
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2321654,
			"security": true,
			"title": "CVE-2024-9287 python3.10: Virtual environment (venv) activation scripts don't quote paths [fedora-all]",
			"bugzilla": {
				"bug_id": "2321654",
				"creation_ts": "2024-10-24 22:56:17 +0000",
				"short_desc": "CVE-2024-9287 python3.10: Virtual environment (venv) activation scripts don't quote paths [fedora-all]",
				"delta_ts": "2024-12-14 06:58:25 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Reopened, Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2321440",
						"alias": "CVE-2024-9287",
						"creation_ts": "2024-10-24 10:14:35 +0000",
						"short_desc": "CVE-2024-9287 python: Virtual environment (venv) activation scripts don't quote paths",
						"delta_ts": "2024-12-18 16:16:37 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2321658",
							"2321661",
							"2321653",
							"2321654",
							"2321655",
							"2321656",
							"2321657",
							"2321659",
							"2321660",
							"2321662"
						],
						"external_bugs": {
							"text": "RHSA-2024:11111",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18238595",
								"comment_count": "0",
								"who": {
									"text": "bzimport",
									"name": "OSIDB Bzimport"
								},
								"bug_when": "2024-10-24 10:14:35 +0000",
								"thetext": "A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected."
							},
							{
								"isprivate": "0",
								"commentid": "18249710",
								"comment_count": "1",
								"who": {
									"text": "lbalhar",
									"name": "Lum√≠r Balhar"
								},
								"bug_when": "2024-11-04 06:47:35 +0000",
								"thetext": "Upstream issue: https://github.com/python/cpython/issues/124651\n\nThe fix has already been merged into 3.11+, PRs for 3.10 and 3.9 are waiting and all versions should get a security release after that."
							},
							{
								"isprivate": "0",
								"commentid": "18292363",
								"comment_count": "2",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-04 08:12:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:10779 https://access.redhat.com/errata/RHSA-2024:10779"
							},
							{
								"isprivate": "0",
								"commentid": "18299894",
								"comment_count": "3",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-12 08:38:16 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:10978 https://access.redhat.com/errata/RHSA-2024:10978"
							},
							{
								"isprivate": "0",
								"commentid": "18299924",
								"comment_count": "4",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-12 08:50:21 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:10979 https://access.redhat.com/errata/RHSA-2024:10979"
							},
							{
								"isprivate": "0",
								"commentid": "18299926",
								"comment_count": "5",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-12 08:50:29 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:10980 https://access.redhat.com/errata/RHSA-2024:10980"
							},
							{
								"isprivate": "0",
								"commentid": "18299941",
								"comment_count": "6",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-12 09:15:50 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:10983 https://access.redhat.com/errata/RHSA-2024:10983"
							},
							{
								"isprivate": "0",
								"commentid": "18300582",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-12 21:04:10 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.4 Extended Update Support\n\nVia RHSA-2024:11024 https://access.redhat.com/errata/RHSA-2024:11024"
							},
							{
								"isprivate": "0",
								"commentid": "18300947",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-13 09:15:02 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.4 Extended Update Support\n\nVia RHSA-2024:11035 https://access.redhat.com/errata/RHSA-2024:11035"
							},
							{
								"isprivate": "0",
								"commentid": "18303000",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-12-16 12:00:20 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:11111 https://access.redhat.com/errata/RHSA-2024:11111"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18239312",
						"comment_count": "0",
						"who": {
							"text": "rgatica",
							"name": "Robb Gatica"
						},
						"bug_when": "2024-10-24 22:56:17 +0000",
						"thetext": "More information about this security flaw is available in the following bug:\n\nhttps://bugzilla.redhat.com/show_bug.cgi?id=2321440\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18293634",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 11:44:07 +0000",
						"thetext": "FEDORA-2024-39f0ccfbc3 (python3.10-3.10.16-1.fc42) has been submitted as an update to Fedora 42.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-39f0ccfbc3"
					},
					{
						"isprivate": "0",
						"commentid": "18293637",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 11:48:22 +0000",
						"thetext": "FEDORA-2024-39f0ccfbc3 (python3.10-3.10.16-1.fc42) has been pushed to the Fedora 42 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18293645",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 12:13:37 +0000",
						"thetext": "FEDORA-2024-1a493abc67 (python3.10-3.10.16-1.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-1a493abc67"
					},
					{
						"isprivate": "0",
						"commentid": "18293646",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-05 12:13:38 +0000",
						"thetext": "FEDORA-2024-cae0bcc133 (python3.10-3.10.16-1.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-cae0bcc133"
					},
					{
						"isprivate": "0",
						"commentid": "18294347",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-06 02:47:17 +0000",
						"thetext": "FEDORA-2024-1a493abc67 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-1a493abc67`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-1a493abc67\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18294372",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-06 03:03:43 +0000",
						"thetext": "FEDORA-2024-cae0bcc133 has been pushed to the Fedora 41 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-cae0bcc133`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-cae0bcc133\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18301623",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-14 01:40:42 +0000",
						"thetext": "FEDORA-2024-cae0bcc133 (python3.10-3.10.16-1.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18301801",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-12-14 06:58:25 +0000",
						"thetext": "FEDORA-2024-1a493abc67 (python3.10-3.10.16-1.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3.10-3.10.16-1.fc42",
			"release_id": 84,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-debugsource",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-idle",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-tkinter",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-devel",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-debug",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-debuginfo",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-libs",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					},
					{
						"name": "python3.10-test",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "aarch64"
					}
				],
				"i686": [
					{
						"name": "python3.10-debugsource",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-debuginfo",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-libs",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-test",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-debug",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-idle",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-tkinter",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10-devel",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					},
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python3.10-tkinter",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-devel",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-idle",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-debuginfo",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-debug",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-debugsource",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-libs",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10-test",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					},
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3.10-debuginfo",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-libs",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-test",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-debugsource",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-debug",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-idle",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-tkinter",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10-devel",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					},
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3.10-tkinter",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-idle",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-devel",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-debugsource",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-debug",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-debuginfo",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-libs",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					},
					{
						"name": "python3.10-test",
						"version": "3.10.16",
						"release": "1.fc42",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3855716,
			"text": "This update was automatically created",
			"timestamp": "2024-12-05 11:44:03",
			"update_id": 674043,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3855717,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-12-05 11:44:17",
			"update_id": 674043,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3855718,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2024-12-05 11:46:05",
			"update_id": 674043,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3855719,
			"text": "This update's test gating status has been changed to 'ignored'.",
			"timestamp": "2024-12-05 11:46:05",
			"update_id": 674043,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3855723,
			"text": "This update has been submitted for stable by bodhi",
			"timestamp": "2024-12-05 11:48:20",
			"update_id": 674043,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath_groups": "",
	"date_approved": "2024-12-05 11:48:20",
	"date_pushed": "2024-12-05 11:48:20",
	"date_stable": "2024-12-05 11:48:20",
	"date_submitted": "2024-12-05 11:44:03",
	"date_testing": "2024-12-05 11:46:05",
	"meets_testing_requirements": true,
	"notes": "Automatic update for python3.10-3.10.16-1.fc42.\n\n##### **Changelog**\n\n```\n* Wed Dec  4 2024 Charalampos Stratakis <cstratak@redhat.com> - 3.10.16-1\n- Update to 3.10.16\n- Security fix for CVE-2024-9287\nResolves: rhbz#2321654\n* Wed Sep 11 2024 Miro Hronƒçok <mhroncok@redhat.com> - 3.10.15-2\n- Fix ThreadedVSOCKSocketStreamTest\n\n```",
	"pushed": true,
	"release": {
		"branch": "rawhide",
		"candidate_tag": "f42-updates-candidate",
		"create_automatic_updates": true,
		"dist_tag": "f42",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 42",
		"mail_template": "fedora_errata_template",
		"name": "F42",
		"override_tag": "f42-override",
		"package_manager": "unspecified",
		"pending_signing_tag": "f42-signing-pending",
		"pending_stable_tag": "f42-updates-pending",
		"pending_testing_tag": "f42-updates-testing-pending",
		"stable_tag": "f42",
		"state": "pending",
		"testing_tag": "f42-updates-testing",
		"version": "42"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python3.10-3.10.16-1.fc42",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2024-39f0ccfbc3",
	"unstable_karma": -3,
	"updateid": "FEDORA-2024-39f0ccfbc3",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/e221b70024cf971d8b43de0260d2babde9179cdf72605bf3168420e3efe07423?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "391b9d1847983d871bf7cc40ccf1a01bbd7f264f"
}
