{
	"alias": "FEDORA-2015-9664",
	"bugs": [
		{
			"bug_id": 1202077,
			"title": "python-requests-2.6.0 is available",
			"bugzilla": {
				"bug_id": "1202077",
				"creation_ts": "2015-03-15 01:22:00 +0000",
				"short_desc": "python-requests-2.6.0 is available",
				"delta_ts": "2015-06-18 13:23:22 +0000",
				"bug_status": "CLOSED",
				"resolution": "RAWHIDE",
				"keywords": "FutureFeature, Triaged",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8043262",
						"comment_count": "0",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2015-03-15 01:22:00 +0000",
						"thetext": "Latest upstream release: 2.6.0\nCurrent version/release in rawhide: 2.5.3-1.fc23\nURL: https://pypi.python.org/pypi/requests\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://fedoraproject.org/wiki/Updates_Policy\n\nMore information about the service that created this bug can be found at: https://fedoraproject.org/wiki/Upstream_release_monitoring"
					},
					{
						"isprivate": "0",
						"commentid": "8043263",
						"comment_count": "1",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2015-03-15 01:23:33 +0000",
						"thetext": "Scratch build succeeded http://koji.fedoraproject.org/koji/taskinfo?taskID=9235010"
					},
					{
						"isprivate": "0",
						"commentid": "8093252",
						"comment_count": "2",
						"who": {
							"text": "rbean",
							"name": "Ralph Bean"
						},
						"bug_when": "2015-03-28 11:50:01 +0000",
						"thetext": "Need to check if python-requests bundled a pre-release of python-urllib3 before bumping this."
					},
					{
						"isprivate": "0",
						"commentid": "8163343",
						"comment_count": "3",
						"who": {
							"text": "mbridon",
							"name": "Mathieu Bridon"
						},
						"bug_when": "2015-04-21 10:39:25 +0000",
						"thetext": "(In reply to Ralph Bean from comment #2)\n> Need to check if python-requests bundled a pre-release of python-urllib3\n> before bumping this.\n\nThey did:\n\n  $ git log -p v2.5.3..v2.6.0 --reverse -- requests/packages/urllib3\n  commit a0790f37b762ec737b2a4a13c167aad2defa8575\n  Author: Ian Cordasco <graffatcolmingov@gmail.com>\n  Date:   Tue Mar 10 19:34:34 2015 -0500\n  \n      Update urllib3 to 43b5b2b452e4344374de7d08ececcca495079b8d\n\nIt seems they require the dev version of 1.10.2, which hasn't been released yet. :("
					},
					{
						"isprivate": "0",
						"commentid": "8163376",
						"comment_count": "4",
						"who": {
							"text": "pingou",
							"name": "Pierre-YvesChibon"
						},
						"bug_when": "2015-04-21 10:52:41 +0000",
						"thetext": "(In reply to Mathieu Bridon from comment #3)\n> (In reply to Ralph Bean from comment #2)\n> > Need to check if python-requests bundled a pre-release of python-urllib3\n> > before bumping this.\n> \n> They did:\n> \n>   $ git log -p v2.5.3..v2.6.0 --reverse -- requests/packages/urllib3\n>   commit a0790f37b762ec737b2a4a13c167aad2defa8575\n>   Author: Ian Cordasco <graffatcolmingov@gmail.com>\n>   Date:   Tue Mar 10 19:34:34 2015 -0500\n>   \n>       Update urllib3 to 43b5b2b452e4344374de7d08ececcca495079b8d\n> \n> It seems they require the dev version of 1.10.2, which hasn't been released\n> yet. :(\n\nDo you know if they just updated their bundle or if they actually are using features from this new version?"
					},
					{
						"isprivate": "0",
						"commentid": "8163993",
						"comment_count": "5",
						"who": {
							"text": "rbean",
							"name": "Ralph Bean"
						},
						"bug_when": "2015-04-21 13:25:00 +0000",
						"thetext": "Filed a request for a release with urllib3 upstream:  https://github.com/shazow/urllib3/issues/592"
					},
					{
						"isprivate": "0",
						"commentid": "8168938",
						"comment_count": "6",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2015-04-22 14:24:54 +0000",
						"thetext": "ralph's python-requests-2.6.0-1.fc23 completed http://koji.fedoraproject.org/koji/buildinfo?buildID=629967"
					},
					{
						"isprivate": "0",
						"commentid": "8168946",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-22 14:28:37 +0000",
						"thetext": "python-requests-2.6.0-1.fc22,python-urllib3-1.10.3-1.fc22 has been submitted as an update for Fedora 22.\nhttps://admin.fedoraproject.org/updates/python-requests-2.6.0-1.fc22,python-urllib3-1.10.3-1.fc22"
					},
					{
						"isprivate": "0",
						"commentid": "8168988",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-22 14:36:58 +0000",
						"thetext": "python-requests-2.6.0-1.fc21,python-urllib3-1.10.3-1.fc21 has been submitted as an update for Fedora 21.\nhttps://admin.fedoraproject.org/updates/python-requests-2.6.0-1.fc21,python-urllib3-1.10.3-1.fc21"
					},
					{
						"isprivate": "0",
						"commentid": "8179238",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-04-26 12:51:39 +0000",
						"thetext": "python-requests-2.6.0-1.fc22, python-urllib3-1.10.3-1.fc22 has been pushed to the Fedora 22 stable repository.  If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "8275545",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-05-28 18:03:22 +0000",
						"thetext": "python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-2.20150503gita91975b.fc21 has been submitted as an update for Fedora 21.\nhttps://admin.fedoraproject.org/updates/python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-2.20150503gita91975b.fc21"
					},
					{
						"isprivate": "0",
						"commentid": "8315089",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-06-08 14:40:57 +0000",
						"thetext": "python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-3.20150503gita91975b.fc21 has been submitted as an update for Fedora 21.\nhttps://admin.fedoraproject.org/updates/python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-3.20150503gita91975b.fc21"
					},
					{
						"isprivate": "0",
						"commentid": "8349983",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-06-18 13:23:22 +0000",
						"thetext": "python-requests-2.7.0-1.fc21, python-urllib3-1.10.4-3.20150503gita91975b.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1222024,
			"title": "InsecurePlatformWarning: A true SSLContext object is not available",
			"bugzilla": {
				"bug_id": "1222024",
				"creation_ts": "2015-05-15 13:57:43 +0000",
				"short_desc": "InsecurePlatformWarning: A true SSLContext object is not available",
				"delta_ts": "2015-06-18 13:23:20 +0000",
				"bug_status": "CLOSED",
				"resolution": "CURRENTRELEASE",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"blocked": [
					{
						"bug_id": "1229387",
						"error": "NotPermitted"
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "8239117",
						"comment_count": "0",
						"who": {
							"text": "h.reindl",
							"name": "Harald Reindl"
						},
						"bug_when": "2015-05-15 13:57:43 +0000",
						"thetext": "that warning appear for weeks now\n\nWaiting for Bodhi for a list of packages in updates-testing (F21)...\n/usr/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning"
					},
					{
						"isprivate": "0",
						"commentid": "8239334",
						"comment_count": "1",
						"who": {
							"text": "opensource",
							"name": "Till Maas"
						},
						"bug_when": "2015-05-15 15:01:28 +0000",
						"thetext": "I guess this is a problem in python-fedora or maybe urllib3, but most likely not in fedora-easy-karma direclty."
					},
					{
						"isprivate": "0",
						"commentid": "8308157",
						"comment_count": "2",
						"who": {
							"text": "pp",
							"name": "Pekka Pietik√§inen"
						},
						"bug_when": "2015-06-05 06:05:47 +0000",
						"thetext": "It's messier than that, real fix would be to update Fedora 21 to python 2.7.9 (or .10), downgrade/patch python-requests and python-urllib3 to versions that don't care or just disable the warnings per package..."
					},
					{
						"isprivate": "0",
						"commentid": "8310740",
						"comment_count": "3",
						"who": {
							"text": "rbean",
							"name": "Ralph Bean"
						},
						"bug_when": "2015-06-05 20:42:02 +0000",
						"thetext": "Alternatively, we could build python-urllib3 against pyOpenSSL and patch it to inject the pyOpenSSL hooks at import-time (just for F21)."
					},
					{
						"isprivate": "0",
						"commentid": "8315088",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-06-08 14:40:56 +0000",
						"thetext": "python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-3.20150503gita91975b.fc21 has been submitted as an update for Fedora 21.\nhttps://admin.fedoraproject.org/updates/python-requests-2.7.0-1.fc21,python-urllib3-1.10.4-3.20150503gita91975b.fc21"
					},
					{
						"isprivate": "0",
						"commentid": "8315653",
						"comment_count": "5",
						"who": {
							"text": "pp",
							"name": "Pekka Pietik√§inen"
						},
						"bug_when": "2015-06-08 17:31:14 +0000",
						"thetext": "Quick testing suggests the patch makes the warning go away (and probably now apps using urllib3/requests now do TLS \"correctly\" by default). Suppose some \"regression\" with self-signed certs/legacy servers may occur, but that is a small price for getting things secure ;-)\n\nIf I read the spec/patch correctly, pyOpenSSL gets used even with Python 3, which may not be desired (seems to work fine anyway)"
					},
					{
						"isprivate": "0",
						"commentid": "8349982",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2015-06-18 13:23:20 +0000",
						"thetext": "python-requests-2.7.0-1.fc21, python-urllib3-1.10.4-3.20150503gita91975b.fc21 has been pushed to the Fedora 21 stable repository.  If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"nvr": "python-requests-2.7.0-1.fc21",
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-requests",
						"version": "2.7.0",
						"release": "1.fc21",
						"arch": "noarch"
					},
					{
						"name": "python-requests",
						"version": "2.7.0",
						"release": "1.fc21",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-requests",
						"version": "2.7.0",
						"release": "1.fc21",
						"arch": "src"
					}
				]
			}
		},
		{
			"nvr": "python-urllib3-1.10.4-3.20150503gita91975b.fc21",
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python-urllib3",
						"version": "1.10.4",
						"release": "3.20150503gita91975b.fc21",
						"arch": "noarch"
					},
					{
						"name": "python3-urllib3",
						"version": "1.10.4",
						"release": "3.20150503gita91975b.fc21",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-urllib3",
						"version": "1.10.4",
						"release": "3.20150503gita91975b.fc21",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 296773,
			"text": "This update has been submitted for testing by ralph. ",
			"timestamp": "2015-06-08 14:41:01",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296774,
			"text": "Taskotron: depcheck test PASSED on i386. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/79431/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-06-08 14:45:45",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1c99e8328b68b58a71f5a9d6449baa7cb914591c56cbec0adfac7c50e4abefa4?s=24&d=retro",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 296775,
			"text": "Taskotron: depcheck test PASSED on x86_64. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/79431/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-06-08 14:46:29",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1c99e8328b68b58a71f5a9d6449baa7cb914591c56cbec0adfac7c50e4abefa4?s=24&d=retro",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 296776,
			"karma": 1,
			"text": "works for me and seems to fix\nhttps://bugzilla.redhat.com/show_bug.cgi?id=1222024 at least for\nfedora-easy-karma",
			"timestamp": "2015-06-08 17:45:31",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/c82951c2d404ca0cfea20f51b040175ba4d1624f51e8ec366e75565b672e943d?s=24&d=retro",
				"email": "h.reindl@thelounge.net",
				"id": 182,
				"name": "hreindl",
				"openid": "hreindl.id.fedoraproject.org"
			},
			"user_id": 182
		},
		{
			"id": 296777,
			"text": "This update is currently being pushed to the Fedora 21 testing updates repository.",
			"timestamp": "2015-06-08 19:44:24",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296778,
			"text": "This update has been pushed to testing",
			"timestamp": "2015-06-09 15:10:53",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296779,
			"karma": 1,
			"text": "fixes the InsecurePlatformWarning in fedora tools :)",
			"timestamp": "2015-06-10 07:41:51",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/dcc9b804c7f4931d90ad5f9b8b2518e79df4743a418f53589057dc035bddcd0d?s=24&d=retro",
				"email": "kparal@redhat.com",
				"groups": [
					{
						"name": "qa-tools-sig"
					},
					{
						"name": "proventesters"
					},
					{
						"name": "qa"
					},
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "qa-admin"
					},
					{
						"name": "common-issues-triage"
					}
				],
				"id": 411,
				"name": "kparal",
				"openid": "kparal.id.fedoraproject.org"
			},
			"user_id": 411
		},
		{
			"id": 296780,
			"karma": 1,
			"text": "works fine for me. fedora-easy-karma works well.",
			"timestamp": "2015-06-15 01:47:40",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/2087ddb84fdf1774c00fc96323f629621c9046b99eee2aa497044f598f3979d4?s=24&d=retro",
				"email": "yuwatana@redhat.com",
				"groups": [
					{
						"name": "packager"
					}
				],
				"id": 125,
				"name": "yuwata",
				"openid": "yuwata.id.fedoraproject.org"
			},
			"user_id": 125
		},
		{
			"id": 296781,
			"text": "This update has reached the stable karma threshold and will be pushed to the stable updates repository",
			"timestamp": "2015-06-15 01:47:45",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296782,
			"text": "Taskotron: upgradepath test FAILED on noarch. Result log:\nhttps://taskotron.fedoraproject.org/taskmaster//builders/x86_64/builds/81930/steps/runtask/logs/stdio\n(results are informative only)",
			"timestamp": "2015-06-15 01:57:32",
			"update_id": 35389,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/1c99e8328b68b58a71f5a9d6449baa7cb914591c56cbec0adfac7c50e4abefa4?s=24&d=retro",
				"email": "taskotron@fedoraproject.org",
				"groups": [
					{}
				],
				"id": 100,
				"name": "taskotron",
				"openid": "taskotron.id.fedoraproject.org"
			},
			"user_id": 100
		},
		{
			"id": 296783,
			"text": "Automatic push to stable based on karma has been disabled for this update due to failure of an AutoQA test. Update submitter, please check the AutoQA test result and see if there is a valid problem to be fixed here, and fix it if so. If the failure is a mistake on AutoQA's part, you can re-enable the automatic push feature for this update if you like, or push it stable manually once it reaches the requirements under the Updates Policy.",
			"timestamp": "2015-06-15 01:57:34",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296784,
			"text": "This update is currently being pushed to the Fedora 21 stable updates repository.",
			"timestamp": "2015-06-15 18:14:36",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 296785,
			"text": "This update has been pushed to stable",
			"timestamp": "2015-06-18 13:23:23",
			"update_id": 35389,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2015-06-18 13:23:23",
	"date_stable": "2015-06-18 13:23:23",
	"date_submitted": "2015-06-08 14:40:51",
	"date_testing": "2015-06-09 15:10:53",
	"karma": 3,
	"meets_testing_requirements": true,
	"notes": "Inject pyOpenSSL.  https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning  https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl",
	"pushed": true,
	"release": {
		"branch": "f21",
		"candidate_tag": "f21-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f21",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 21",
		"mail_template": "fedora_errata_template",
		"name": "F21",
		"override_tag": "f21-override",
		"package_manager": "dnf",
		"pending_stable_tag": "f21-updates-pending",
		"pending_testing_tag": "f21-updates-testing-pending",
		"stable_tag": "f21-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f21-updates-testing",
		"version": "21"
	},
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"title": "python-requests-2.7.0-1.fc21 python-urllib3-1.10.4-3.20150503gita91975b.fc21",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2015-9664",
	"unstable_karma": -3,
	"updateid": "FEDORA-2015-9664",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/9c9f7784935381befc302fe3c814f9136e7a33953d0318761669b8643f4df55c?s=24&d=retro",
		"email": "rbean@redhat.com",
		"groups": [
			{
				"name": "packager"
			}
		],
		"id": 128,
		"name": "ralph",
		"openid": "ralph.id.fedoraproject.org"
	},
	"version_hash": "0f64cb0779ed73ebff2343d178b0d2f9382c2b14"
}
