{
	"alias": "FEDORA-2024-903edb056a",
	"autokarma": true,
	"autotime": true,
	"bugs": [
		{
			"bug_id": 2279211,
			"feedback": [
				{
					"bug_id": 2279211,
					"comment": {
						"id": 3533235,
						"karma": 1,
						"timestamp": "2024-05-22 12:25:51",
						"update_id": 611218,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/f80c96a3994c2479fc4815a146079bf93ade230fe3f3993213d2b8222cafc73d?s=24&d=retro",
							"email": "fzatlouk@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "advocates"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								}
							],
							"id": 2240,
							"name": "frantisekz",
							"openid": "frantisekz.id.fedoraproject.org"
						},
						"user_id": 2240
					},
					"comment_id": 3533235
				}
			],
			"title": "python-jinja2-3.1.4 is available",
			"bugzilla": {
				"bug_id": "2279211",
				"creation_ts": "2024-05-06 00:29:46 +0000",
				"short_desc": "python-jinja2-3.1.4 is available",
				"delta_ts": "2024-06-01 01:12:19 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "FutureFeature, Triaged",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18003108",
						"comment_count": "0",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2024-05-06 00:29:46 +0000",
						"thetext": "Releases retrieved: 3.1.4\nUpstream release that is considered latest: 3.1.4\nCurrent version/release in rawhide: 3.1.3-3.fc40\nURL: https://pypi.python.org/pypi/Jinja2\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://docs.fedoraproject.org/en-US/fesco/Updates_Policy/\n\n\nMore information about the service that created this bug can be found at: https://docs.fedoraproject.org/en-US/package-maintainers/Upstream_Release_Monitoring\n\n\nPlease keep in mind that with any upstream change, there may also be packaging changes that need to be made. Specifically, please remember that it is your responsibility to review the new version to ensure that the licensing is still correct and that no non-free or legally problematic items have been added upstream.\n\n\nBased on the information from Anitya: https://release-monitoring.org/project/3894/\n\n\nTo change the monitoring settings for the project, please visit:\nhttps://src.fedoraproject.org/rpms/python-jinja2"
					},
					{
						"isprivate": "0",
						"commentid": "18003109",
						"comment_count": "1",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2024-05-06 00:29:51 +0000",
						"thetext": "Scratch build failed. Details below:\n\nBuilderException: Build failed:\nCommand '['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', '/var/tmp/thn-4pw29zb6/python-jinja2.spec']' returned non-zero exit status 1.\n\nStdOut:\nsetting SOURCE_DATE_EPOCH=1714953600\nerror: Bad file: ./Jinja2-3.1.4.tar.gz: No such file or directory\n\nRPM build errors:\n    Bad file: ./Jinja2-3.1.4.tar.gz: No such file or directory\n\n\nTraceback:\n  File \"/usr/local/lib/python3.11/site-packages/hotness/use_cases/package_scratch_build_use_case.py\", line 56, in build\n    result = self.builder.build(request.package, request.opts)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/hotness/builders/koji.py\", line 229, in build\n    raise BuilderException(\n\nIf you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues"
					},
					{
						"isprivate": "0",
						"commentid": "18003110",
						"comment_count": "2",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2024-05-06 00:29:53 +0000",
						"thetext": "Created attachment 2031517\nUpdate to 3.1.4 (#2279211)"
					},
					{
						"isprivate": "0",
						"commentid": "18013485",
						"comment_count": "3",
						"who": {
							"text": "lbalhar",
							"name": "Lum√≠r Balhar"
						},
						"bug_when": "2024-05-13 19:29:40 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-jinja2/pull-request/23"
					},
					{
						"isprivate": "0",
						"commentid": "18017164",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:41:25 +0000",
						"thetext": "FEDORA-2024-b595c68c09 (python-jinja2-3.1.4-1.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-b595c68c09"
					},
					{
						"isprivate": "0",
						"commentid": "18017175",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:53:49 +0000",
						"thetext": "FEDORA-2024-903edb056a (python-jinja2-3.1.4-1.fc38) has been submitted as an update to Fedora 38.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-903edb056a"
					},
					{
						"isprivate": "0",
						"commentid": "18017177",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:55:10 +0000",
						"thetext": "FEDORA-2024-ce7649d28e (python-jinja2-3.1.4-1.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-ce7649d28e"
					},
					{
						"isprivate": "0",
						"commentid": "18017179",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:56:38 +0000",
						"thetext": "FEDORA-2024-2005708761 (python-jinja2-3.1.4-1.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-2005708761"
					},
					{
						"isprivate": "0",
						"commentid": "18017461",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 15:59:08 +0000",
						"thetext": "FEDORA-2024-b595c68c09 (python-jinja2-3.1.4-1.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18018165",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 01:36:09 +0000",
						"thetext": "FEDORA-2024-ce7649d28e has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-ce7649d28e`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-ce7649d28e\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18018212",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 02:09:22 +0000",
						"thetext": "FEDORA-2024-2005708761 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-2005708761`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-2005708761\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18018233",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 02:23:40 +0000",
						"thetext": "FEDORA-2024-903edb056a has been pushed to the Fedora 38 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-903edb056a`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-903edb056a\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18030447",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-23 01:08:47 +0000",
						"thetext": "FEDORA-2024-2005708761 (python-jinja2-3.1.4-1.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18042451",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-06-01 01:12:19 +0000",
						"thetext": "FEDORA-2024-ce7649d28e (python-jinja2-3.1.4-1.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 2279491,
			"feedback": [
				{
					"bug_id": 2279491,
					"comment": {
						"id": 3533235,
						"karma": 1,
						"timestamp": "2024-05-22 12:25:51",
						"update_id": 611218,
						"user": {
							"avatar": "https://seccdn.libravatar.org/avatar/f80c96a3994c2479fc4815a146079bf93ade230fe3f3993213d2b8222cafc73d?s=24&d=retro",
							"email": "fzatlouk@redhat.com",
							"groups": [
								{
									"name": "packager"
								},
								{
									"name": "qa-tools-sig"
								},
								{
									"name": "provenpackager"
								},
								{
									"name": "fedora-contributor"
								},
								{
									"name": "qa-admin"
								},
								{
									"name": "signed_fpca"
								},
								{
									"name": "sysadmin-qa"
								},
								{
									"name": "sysadmin"
								},
								{
									"name": "ambassadors"
								},
								{
									"name": "advocates"
								},
								{
									"name": "fedorabugs"
								},
								{
									"name": "qa"
								},
								{
									"name": "ipausers"
								}
							],
							"id": 2240,
							"name": "frantisekz",
							"openid": "frantisekz.id.fedoraproject.org"
						},
						"user_id": 2240
					},
					"comment_id": 3533235
				}
			],
			"security": true,
			"title": "TRIAGE CVE-2024-34064 python-jinja2: jinja2: accepts keys containing non-attribute characters [fedora-all]",
			"bugzilla": {
				"bug_id": "2279491",
				"creation_ts": "2024-05-07 06:35:51 +0000",
				"short_desc": "TRIAGE CVE-2024-34064 python-jinja2: jinja2: accepts keys containing non-attribute characters [fedora-all]",
				"delta_ts": "2024-06-01 01:12:21 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "2279476",
						"alias": "CVE-2024-34064",
						"creation_ts": "2024-05-07 06:30:20 +0000",
						"short_desc": "CVE-2024-34064 jinja2: accepts keys containing non-attribute characters",
						"delta_ts": "2024-07-24 19:09:30 +0000",
						"bug_status": "NEW",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"2279477",
							"2279478",
							"2279480",
							"2279487",
							"2279489",
							"2279490",
							"2292741",
							"2279479",
							"2279481",
							"2279482",
							"2279483",
							"2279484",
							"2279485",
							"2279486",
							"2279488",
							"2279491"
						],
						"blocked": [
							{
								"bug_id": "2279475",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2024:4616",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "18004971",
								"comment_count": "0",
								"who": {
									"text": "rkeshri",
									"name": "Rohit Keshri"
								},
								"bug_when": "2024-05-07 06:30:20 +0000",
								"thetext": "Jinja is an extensible templating engine. The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for CVE-2024-22195 only addressed spaces but not other characters. Accepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe. This vulnerability is fixed in 3.1.4.\n\nhttps://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb\nhttps://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"
							},
							{
								"isprivate": "0",
								"commentid": "18005006",
								"comment_count": "1",
								"who": {
									"text": "rkeshri",
									"name": "Rohit Keshri"
								},
								"bug_when": "2024-05-07 06:36:32 +0000",
								"thetext": "Created mingw-python-jinja2 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2279486]\n\n\nCreated python-jinja2 tracking bugs for this issue:\n\nAffects: fedora-all [bug 2279491]\n\n\nCreated python3-jinja2 tracking bugs for this issue:\n\nAffects: epel-all [bug 2279489]\n\n\nCreated python3.11-jinja2-epel tracking bugs for this issue:\n\nAffects: epel-all [bug 2279487]\n\n\nCreated python39-jinja2-epel tracking bugs for this issue:\n\nAffects: epel-all [bug 2279488]"
							},
							{
								"isprivate": "0",
								"commentid": "18060151",
								"comment_count": "8",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-06-10 18:37:56 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Ansible Automation Platform 2.4 for RHEL 9\n  Red Hat Ansible Automation Platform 2.4 for RHEL 8\n\nVia RHSA-2024:3781 https://access.redhat.com/errata/RHSA-2024:3781"
							},
							{
								"isprivate": "0",
								"commentid": "18061026",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-06-11 13:08:58 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.4 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.4 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.4 Telecommunications Update Service\n\nVia RHSA-2024:3795 https://access.redhat.com/errata/RHSA-2024:3795"
							},
							{
								"isprivate": "0",
								"commentid": "18061305",
								"comment_count": "10",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-06-11 17:29:44 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.8 Extended Update Support\n\nVia RHSA-2024:3811 https://access.redhat.com/errata/RHSA-2024:3811"
							},
							{
								"isprivate": "0",
								"commentid": "18061362",
								"comment_count": "11",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-06-11 19:40:14 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9\n\nVia RHSA-2024:3820 https://access.redhat.com/errata/RHSA-2024:3820"
							},
							{
								"isprivate": "0",
								"commentid": "18084658",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-02 15:21:16 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8\n\nVia RHSA-2024:4231 https://access.redhat.com/errata/RHSA-2024:4231"
							},
							{
								"isprivate": "0",
								"commentid": "18093155",
								"comment_count": "13",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-09 08:48:36 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 8.6 Advanced Mission Critical Update Support\n  Red Hat Enterprise Linux 8.6 Update Services for SAP Solutions\n  Red Hat Enterprise Linux 8.6 Telecommunications Update Service\n\nVia RHSA-2024:4404 https://access.redhat.com/errata/RHSA-2024:4404"
							},
							{
								"isprivate": "0",
								"commentid": "18093189",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-09 09:20:53 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.0 Update Services for SAP Solutions\n\nVia RHSA-2024:4414 https://access.redhat.com/errata/RHSA-2024:4414"
							},
							{
								"isprivate": "0",
								"commentid": "18093437",
								"comment_count": "15",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-09 12:51:03 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 9.2 Extended Update Support\n\nVia RHSA-2024:4427 https://access.redhat.com/errata/RHSA-2024:4427"
							},
							{
								"isprivate": "0",
								"commentid": "18096246",
								"comment_count": "16",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-12 01:40:46 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Ansible Automation Platform 2.4 for RHEL 9\n  Red Hat Ansible Automation Platform 2.4 for RHEL 8\n\nVia RHSA-2024:4522 https://access.redhat.com/errata/RHSA-2024:4522"
							},
							{
								"isprivate": "0",
								"commentid": "18108364",
								"comment_count": "17",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2024-07-24 19:09:26 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat OpenShift Container Platform 4.16\n\nVia RHSA-2024:4616 https://access.redhat.com/errata/RHSA-2024:4616"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "18005004",
						"comment_count": "0",
						"who": {
							"text": "rkeshri",
							"name": "Rohit Keshri"
						},
						"bug_when": "2024-05-07 06:35:51 +0000",
						"thetext": "\nMore information about this security flaw is available in the following bug:\n\nhttp://bugzilla.redhat.com/show_bug.cgi?id=2279476\n\nDisclaimer: Community trackers are created by Red Hat Product Security team on a best effort basis. Package maintainers are required to ascertain if the flaw indeed affects their package, before starting the update process."
					},
					{
						"isprivate": "0",
						"commentid": "18005005",
						"comment_count": "1",
						"who": {
							"text": "rkeshri",
							"name": "Rohit Keshri"
						},
						"bug_when": "2024-05-07 06:35:54 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# low, medium, high, urgent (required)\nseverity=medium\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=2279476,2279491\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "18013486",
						"comment_count": "2",
						"who": {
							"text": "lbalhar",
							"name": "Lum√≠r Balhar"
						},
						"bug_when": "2024-05-13 19:29:52 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python-jinja2/pull-request/23"
					},
					{
						"isprivate": "0",
						"commentid": "18017165",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:41:28 +0000",
						"thetext": "FEDORA-2024-b595c68c09 (python-jinja2-3.1.4-1.fc41) has been submitted as an update to Fedora 41.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-b595c68c09"
					},
					{
						"isprivate": "0",
						"commentid": "18017176",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:53:52 +0000",
						"thetext": "FEDORA-2024-903edb056a (python-jinja2-3.1.4-1.fc38) has been submitted as an update to Fedora 38.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-903edb056a"
					},
					{
						"isprivate": "0",
						"commentid": "18017178",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:55:13 +0000",
						"thetext": "FEDORA-2024-ce7649d28e (python-jinja2-3.1.4-1.fc39) has been submitted as an update to Fedora 39.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-ce7649d28e"
					},
					{
						"isprivate": "0",
						"commentid": "18017180",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 11:56:41 +0000",
						"thetext": "FEDORA-2024-2005708761 (python-jinja2-3.1.4-1.fc40) has been submitted as an update to Fedora 40.\nhttps://bodhi.fedoraproject.org/updates/FEDORA-2024-2005708761"
					},
					{
						"isprivate": "0",
						"commentid": "18017462",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-16 15:59:11 +0000",
						"thetext": "FEDORA-2024-b595c68c09 (python-jinja2-3.1.4-1.fc41) has been pushed to the Fedora 41 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18018166",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 01:36:11 +0000",
						"thetext": "FEDORA-2024-ce7649d28e has been pushed to the Fedora 39 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-ce7649d28e`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-ce7649d28e\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18018213",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 02:09:24 +0000",
						"thetext": "FEDORA-2024-2005708761 has been pushed to the Fedora 40 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-2005708761`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-2005708761\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18018234",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-17 02:23:48 +0000",
						"thetext": "FEDORA-2024-903edb056a has been pushed to the Fedora 38 testing repository.\nSoon you'll be able to install the update with the following command:\n`sudo dnf upgrade --enablerepo=updates-testing --refresh --advisory=FEDORA-2024-903edb056a`\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2024-903edb056a\n\nSee also https://fedoraproject.org/wiki/QA:Updates_Testing for more information on how to test updates."
					},
					{
						"isprivate": "0",
						"commentid": "18030448",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-05-23 01:08:49 +0000",
						"thetext": "FEDORA-2024-2005708761 (python-jinja2-3.1.4-1.fc40) has been pushed to the Fedora 40 stable repository.\nIf problem still persists, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "18042452",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2024-06-01 01:12:21 +0000",
						"thetext": "FEDORA-2024-ce7649d28e (python-jinja2-3.1.4-1.fc39) has been pushed to the Fedora 39 stable repository.\nIf problem still persists, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-jinja2-3.1.4-1.fc38",
			"release_id": 66,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python3-jinja2",
						"version": "3.1.4",
						"release": "1.fc38",
						"arch": "noarch"
					},
					{
						"name": "python3-jinja2+i18n",
						"version": "3.1.4",
						"release": "1.fc38",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-jinja2",
						"version": "3.1.4",
						"release": "1.fc38",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 3526527,
			"text": "This update has been submitted for testing by lbalhar. ",
			"timestamp": "2024-05-16 11:53:46",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3526528,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2024-05-16 11:53:47",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3526529,
			"text": "This update's test gating status has been changed to 'waiting'.",
			"timestamp": "2024-05-16 11:53:47",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3526735,
			"text": "This update's test gating status has been changed to 'passed'.",
			"timestamp": "2024-05-16 14:51:40",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3527723,
			"text": "This update has been pushed to testing.",
			"timestamp": "2024-05-17 02:24:39",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 3532367,
			"text": "This update is marked obsolete because the F38 release is archived.",
			"timestamp": "2024-05-21 16:32:15",
			"update_id": 611216,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"critpath_groups": "critical-path-build critical-path-compose critical-path-server",
	"date_pushed": "2024-05-17 02:23:36",
	"date_submitted": "2024-05-16 11:53:46",
	"date_testing": "2024-05-17 02:23:36",
	"meets_testing_requirements": true,
	"notes": "Update to 3.1.4 (rhbz#2279211,rhbz#2279491)",
	"pushed": true,
	"release": {
		"branch": "f38",
		"candidate_tag": "f38-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f38",
		"eol": "2024-05-21",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 38",
		"mail_template": "fedora_errata_template",
		"name": "F38",
		"override_tag": "f38-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f38-signing-pending",
		"pending_stable_tag": "f38-updates-pending",
		"pending_testing_tag": "f38-updates-testing-pending",
		"stable_tag": "f38-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f38-updates-testing",
		"version": "38"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_days": 14,
	"stable_karma": 3,
	"status": "obsolete",
	"suggest": "unspecified",
	"test_gating_status": "passed",
	"title": "python-jinja2-3.1.4-1.fc38",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2024-903edb056a",
	"unstable_karma": -3,
	"updateid": "FEDORA-2024-903edb056a",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/43b68973106261bbbf2ac130b7c5d1c27fb91e2546b3e4a22dbcd5c50a3c681e?s=24&d=retro",
		"email": "lbalhar@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "realtime"
			},
			{
				"name": "machine-learning-sig"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 2936,
		"name": "lbalhar",
		"openid": "lbalhar.id.fedoraproject.org"
	},
	"version_hash": "ce3bf65cce7a3bf981e160edc65be641a0d79899"
}
