{
	"alias": "FEDORA-2018-b9581d9624",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1651973,
			"parent": true,
			"security": true,
			"title": "CVE-2018-19351 python-notebook: XSS via an untrusted notebook",
			"bugzilla": {
				"bug_id": "1651973",
				"alias": "CVE-2018-19351",
				"creation_ts": "2018-11-21 10:38:39 +0000",
				"short_desc": "CVE-2018-19351 python-notebook: XSS via an untrusted notebook",
				"delta_ts": "2019-09-29 15:02:13 +0000",
				"bug_status": "CLOSED",
				"resolution": "UPSTREAM",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1651976"
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12225705",
						"comment_count": "0",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:38:39 +0000",
						"thetext": "\nJupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this.\n\nReferences:\n\nhttps://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\nhttps://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491\nhttps://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY\nhttps://pypi.org/project/notebook/#history"
					},
					{
						"isprivate": "0",
						"commentid": "12225758",
						"comment_count": "1",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:40:15 +0000",
						"thetext": "Created python-notebook tracking bugs for this issue:\n\nAffects: fedora-all [bug 1651976]"
					},
					{
						"isprivate": "0",
						"commentid": "12825765",
						"comment_count": "2",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2019-06-10 10:43:00 +0000",
						"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
					}
				]
			}
		},
		{
			"bug_id": 1651975,
			"parent": true,
			"security": true,
			"title": "CVE-2018-19352 python-notebook: XSS via an crafted directory",
			"bugzilla": {
				"bug_id": "1651975",
				"alias": "CVE-2018-19352",
				"creation_ts": "2018-11-21 10:39:44 +0000",
				"short_desc": "CVE-2018-19352 python-notebook: XSS via an crafted directory",
				"delta_ts": "2019-09-29 15:03:11 +0000",
				"bug_status": "CLOSED",
				"resolution": "UPSTREAM",
				"keywords": "Security",
				"priority": "medium",
				"bug_severity": "medium",
				"depends_on": [
					"1651976"
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12225737",
						"comment_count": "0",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:39:44 +0000",
						"thetext": "\nJupyter Notebook before 5.7.2 allows XSS via a crafted directory name because notebook/static/tree/js/notebooklist.js handles certain URLs unsafely.\n\nReferences:\n\nhttps://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\nhttps://github.com/jupyter/notebook/commit/288b73e1edbf527740e273fcc69b889460871648\nhttps://pypi.org/project/notebook/#history"
					},
					{
						"isprivate": "0",
						"commentid": "12225763",
						"comment_count": "1",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:40:21 +0000",
						"thetext": "Created python-notebook tracking bugs for this issue:\n\nAffects: fedora-all [bug 1651976]"
					},
					{
						"isprivate": "0",
						"commentid": "12825766",
						"comment_count": "2",
						"who": {
							"text": "prodsec-dev",
							"name": "Product Security DevOps Team"
						},
						"bug_when": "2019-06-10 10:43:02 +0000",
						"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
					}
				]
			}
		},
		{
			"bug_id": 1651976,
			"security": true,
			"title": "CVE-2018-19351 CVE-2018-19352 python-notebook: various flaws [fedora-all]",
			"bugzilla": {
				"bug_id": "1651976",
				"creation_ts": "2018-11-21 10:40:07 +0000",
				"short_desc": "CVE-2018-19351 CVE-2018-19352 python-notebook: various flaws [fedora-all]",
				"delta_ts": "2018-12-14 20:41:19 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1651973",
						"alias": "CVE-2018-19351",
						"creation_ts": "2018-11-21 10:38:39 +0000",
						"short_desc": "CVE-2018-19351 python-notebook: XSS via an untrusted notebook",
						"delta_ts": "2019-09-29 15:02:13 +0000",
						"bug_status": "CLOSED",
						"resolution": "UPSTREAM",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1651976"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12225705",
								"comment_count": "0",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-11-21 10:38:39 +0000",
								"thetext": "\nJupyter Notebook before 5.7.1 allows XSS via an untrusted notebook because nbconvert responses are considered to have the same origin as the notebook server. In other words, nbconvert endpoints can execute JavaScript with access to the server API. In notebook/nbconvert/handlers.py, NbconvertFileHandler and NbconvertPostHandler do not set a Content Security Policy to prevent this.\n\nReferences:\n\nhttps://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\nhttps://github.com/jupyter/notebook/commit/107a89fce5f413fb5728c1c5d2c7788e1fb17491\nhttps://groups.google.com/forum/#!topic/jupyter/hWzu2BSsplY\nhttps://pypi.org/project/notebook/#history"
							},
							{
								"isprivate": "0",
								"commentid": "12225758",
								"comment_count": "1",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-11-21 10:40:15 +0000",
								"thetext": "Created python-notebook tracking bugs for this issue:\n\nAffects: fedora-all [bug 1651976]"
							},
							{
								"isprivate": "0",
								"commentid": "12825765",
								"comment_count": "2",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2019-06-10 10:43:00 +0000",
								"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
							}
						]
					},
					{
						"bug_id": "1651975",
						"alias": "CVE-2018-19352",
						"creation_ts": "2018-11-21 10:39:44 +0000",
						"short_desc": "CVE-2018-19352 python-notebook: XSS via an crafted directory",
						"delta_ts": "2019-09-29 15:03:11 +0000",
						"bug_status": "CLOSED",
						"resolution": "UPSTREAM",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1651976"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "12225737",
								"comment_count": "0",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-11-21 10:39:44 +0000",
								"thetext": "\nJupyter Notebook before 5.7.2 allows XSS via a crafted directory name because notebook/static/tree/js/notebooklist.js handles certain URLs unsafely.\n\nReferences:\n\nhttps://github.com/jupyter/notebook/blob/master/docs/source/changelog.rst\nhttps://github.com/jupyter/notebook/commit/288b73e1edbf527740e273fcc69b889460871648\nhttps://pypi.org/project/notebook/#history"
							},
							{
								"isprivate": "0",
								"commentid": "12225763",
								"comment_count": "1",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-11-21 10:40:21 +0000",
								"thetext": "Created python-notebook tracking bugs for this issue:\n\nAffects: fedora-all [bug 1651976]"
							},
							{
								"isprivate": "0",
								"commentid": "12825766",
								"comment_count": "2",
								"who": {
									"text": "prodsec-dev",
									"name": "Product Security DevOps Team"
								},
								"bug_when": "2019-06-10 10:43:02 +0000",
								"thetext": "This CVE Bugzilla entry is for community support informational purposes only as it does not affect a package in a commercially supported Red Hat product. Refer to the dependent bugs for status of those individual community products."
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "12225753",
						"comment_count": "0",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:40:07 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "12225755",
						"comment_count": "1",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-11-21 10:40:11 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1651973,1651975,1651976\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "12227669",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-21 17:07:07 +0000",
						"thetext": "python-notebook-5.7.2-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-b792d607fd"
					},
					{
						"isprivate": "0",
						"commentid": "12227847",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-21 18:05:12 +0000",
						"thetext": "python-notebook-5.5.0-6.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-b9581d9624"
					},
					{
						"isprivate": "0",
						"commentid": "12228795",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-22 04:30:05 +0000",
						"thetext": "python-notebook-5.5.0-6.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-b9581d9624"
					},
					{
						"isprivate": "0",
						"commentid": "12228860",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-22 05:38:29 +0000",
						"thetext": "python-notebook-5.7.2-1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-b792d607fd"
					},
					{
						"isprivate": "0",
						"commentid": "12258585",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-11-30 02:49:43 +0000",
						"thetext": "python-notebook-5.7.2-1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12293517",
						"comment_count": "7",
						"who": {
							"text": "rbarlow",
							"name": "Randy Barlow"
						},
						"bug_when": "2018-12-11 17:04:09 +0000",
						"thetext": "A Fedora update associated with this bug has been pushed to the stable repository."
					},
					{
						"isprivate": "0",
						"commentid": "12305691",
						"comment_count": "8",
						"who": {
							"text": "rbarlow",
							"name": "Randy Barlow"
						},
						"bug_when": "2018-12-14 20:41:19 +0000",
						"thetext": "A Fedora update associated with this bug has been pushed to the stable repository."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-notebook-5.5.0-6.fc28",
			"release_id": 21,
			"signed": true,
			"type": "rpm",
			"package": {
				"noarch": [
					{
						"name": "python2-notebook",
						"version": "5.5.0",
						"release": "6.fc28",
						"arch": "noarch"
					},
					{
						"name": "python-notebook-doc",
						"version": "5.5.0",
						"release": "6.fc28",
						"arch": "noarch"
					},
					{
						"name": "python3-notebook",
						"version": "5.5.0",
						"release": "6.fc28",
						"arch": "noarch"
					}
				],
				"src": [
					{
						"name": "python-notebook",
						"version": "5.5.0",
						"release": "6.fc28",
						"arch": "src"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 865437,
			"text": "This update has been submitted for testing by churchyard. ",
			"timestamp": "2018-11-21 18:05:07",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 865643,
			"text": "This update has been pushed to testing.",
			"timestamp": "2018-11-22 04:30:46",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 868374,
			"text": "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2018-11-29 06:00:36",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 872535,
			"text": "This update has been submitted for batched by churchyard. ",
			"timestamp": "2018-12-10 14:16:08",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 872658,
			"text": "This update has been submitted for stable by bodhi. ",
			"timestamp": "2018-12-10 23:45:18",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 872692,
			"text": "This update has been pushed to stable.",
			"timestamp": "2018-12-11 01:56:41",
			"update_id": 127184,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2018-12-11 01:56:16",
	"date_stable": "2018-12-11 01:56:16",
	"date_submitted": "2018-11-21 18:05:07",
	"date_testing": "2018-11-22 04:29:38",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2018-19351, CVE-2018-19352",
	"pushed": true,
	"release": {
		"branch": "f28",
		"candidate_tag": "f28-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f28",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 28",
		"mail_template": "fedora_errata_template",
		"name": "F28",
		"override_tag": "f28-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f28-signing-pending",
		"pending_stable_tag": "f28-updates-pending",
		"pending_testing_tag": "f28-updates-testing-pending",
		"stable_tag": "f28-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f28-updates-testing",
		"version": "28"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "medium",
	"stable_karma": 2,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-notebook-5.5.0-6.fc28",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2018-b9581d9624",
	"unstable_karma": -1,
	"updateid": "FEDORA-2018-b9581d9624",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/132a6c64fa9fbe9311973f5c5c6a70942b256d23d62be638718fe091076731cf?s=24&d=retro",
		"email": "mhroncok@redhat.com",
		"groups": [
			{
				"name": "provenpackager"
			},
			{
				"name": "packager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "3d-printing-sig"
			},
			{
				"name": "python-packagers-sig"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "sysadmin-badges"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "sysadmin"
			},
			{
				"name": "lua-packagers-sig"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "cvsadmin"
			},
			{
				"name": "ambassadors"
			},
			{
				"name": "packaging-committee"
			},
			{
				"name": "advocates"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 533,
		"name": "churchyard",
		"openid": "churchyard.id.fedoraproject.org"
	},
	"version_hash": "861b814dbfa8e185de8a28bff7efc838708c4602"
}
