{
	"alias": "FEDORA-2018-7eae87ec86",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1548683,
			"title": "Filter bogus rpmlint errors/warnings",
			"bugzilla": {
				"bug_id": "1548683",
				"creation_ts": "2018-02-24 11:54:36 +0000",
				"short_desc": "Filter bogus rpmlint errors/warnings",
				"delta_ts": "2018-04-09 19:08:31 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Reopened",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11317801",
						"comment_count": "0",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hron훾ok"
						},
						"bug_when": "2018-02-24 11:54:36 +0000",
						"thetext": "It si now possible to filter bogus rpmlint errors and warnings on taskotron: \n\nhttps://pagure.io/taskotron/task-rpmlint/issue/5\n\nhttps://fedoraproject.org/wiki/Taskotron/Tasks/dist.rpmlint#Whitelisting_errors\n\nLet's do that for python37 and later backport it to python3."
					},
					{
						"isprivate": "0",
						"commentid": "11395504",
						"comment_count": "1",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hron훾ok"
						},
						"bug_when": "2018-03-19 21:03:32 +0000",
						"thetext": "Fixed in python37\n\nProposal for python3 https://src.fedoraproject.org/rpms/python3/pull-request/28"
					},
					{
						"isprivate": "0",
						"commentid": "11450350",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:30:41 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-7eae87ec86"
					},
					{
						"isprivate": "0",
						"commentid": "11450373",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:32:40 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11450391",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:33:47 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451935",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:51:06 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451958",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:56:32 +0000",
						"thetext": "python-pip-9.0.3-1.fc26 python3-3.6.5-1.fc26 python3-docs-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11452028",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:04:43 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11452071",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:13:29 +0000",
						"thetext": "python-pip-9.0.3-1.fc27 python3-3.6.5-1.fc27 python3-docs-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11453978",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 11:09:18 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11455369",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 16:52:02 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11455416",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 17:16:21 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11461759",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 18:35:01 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11461918",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 19:08:31 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1560295,
			"title": "/usr/lib/debug/usr/lib64/libpython3.6m.so.1.0-3.6.4-20.fc28.x86_64.debug-gdb.py has wrong shebang",
			"bugzilla": {
				"bug_id": "1560295",
				"creation_ts": "2018-03-25 18:20:42 +0000",
				"short_desc": "/usr/lib/debug/usr/lib64/libpython3.6m.so.1.0-3.6.4-20.fc28.x86_64.debug-gdb.py has wrong shebang",
				"delta_ts": "2018-04-09 19:08:41 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Reopened",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11414496",
						"comment_count": "0",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hron훾ok"
						},
						"bug_when": "2018-03-25 18:20:42 +0000",
						"thetext": "See:\n\ntaskotron check: https://taskotron.fedoraproject.org/artifacts/all/18d43998-303b-11e8-9ee8-525400fc9f92/tests.yml/output.log\n\nbuild log: https://kojipkgs.fedoraproject.org/work/tasks/846/25960846/build.log\n\n*** WARNING: mangling shebang in /usr/lib/debug/usr/lib64/libpython3.6dm.so.1.0-3.6.4-20.fc28.x86_64.debug-gdb.py from #!/usr/bin/python to #!/usr/bin/python2. This will become an ERROR, fix it manually!\n*** WARNING: mangling shebang in /usr/lib/debug/usr/lib64/libpython3.6m.so.1.0-3.6.4-20.fc28.x86_64.debug-gdb.py from #!/usr/bin/python to #!/usr/bin/python2. This will become an ERROR, fix it manually!\n\nThis files end in python3-debuginfo and that package does not require /usr/bin/python2, so it's not a serious problem. Yet we should fix this."
					},
					{
						"isprivate": "0",
						"commentid": "11414507",
						"comment_count": "1",
						"who": {
							"text": "mhroncok",
							"name": "Miro Hron훾ok"
						},
						"bug_when": "2018-03-25 19:10:05 +0000",
						"thetext": "https://src.fedoraproject.org/rpms/python3/pull-request/30"
					},
					{
						"isprivate": "0",
						"commentid": "11450359",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:30:52 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-7eae87ec86"
					},
					{
						"isprivate": "0",
						"commentid": "11450375",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:32:51 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11450389",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:33:34 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451933",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:50:55 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451954",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:56:11 +0000",
						"thetext": "python-pip-9.0.3-1.fc26 python3-3.6.5-1.fc26 python3-docs-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11452030",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:04:54 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11452074",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:13:52 +0000",
						"thetext": "python-pip-9.0.3-1.fc27 python3-3.6.5-1.fc27 python3-docs-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11453979",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 11:09:24 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11455367",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 16:51:51 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11455418",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 17:16:32 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11461757",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 18:34:49 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11461920",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 19:08:41 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1563462,
			"security": true,
			"title": "CVE-2018-1060 CVE-2018-1061 python3: various flaws [fedora-all]",
			"bugzilla": {
				"bug_id": "1563462",
				"creation_ts": "2018-04-04 01:42:25 +0000",
				"short_desc": "CVE-2018-1060 CVE-2018-1061 python3: various flaws [fedora-all]",
				"delta_ts": "2018-04-09 19:08:46 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Reopened, Security, SecurityTracking",
				"priority": "medium",
				"bug_severity": "medium",
				"blocked": [
					{
						"bug_id": "1549191",
						"alias": "CVE-2018-1060",
						"creation_ts": "2018-02-26 16:19:47 +0000",
						"short_desc": "CVE-2018-1060 python: DOS via regular expression catastrophic backtracking in apop() method in pop3lib",
						"delta_ts": "2021-02-17 00:46:36 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"1563449",
							"1563450",
							"1563451",
							"1563452",
							"1563453",
							"1563454",
							"1563461",
							"1563462",
							"1563463",
							"1563464",
							"1563465",
							"1709356",
							"1709388",
							"1809255",
							"1809256"
						],
						"blocked": [
							{
								"bug_id": "1549194",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2020:1346",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "11321784",
								"comment_count": "0",
								"who": {
									"text": "psampaio",
									"name": "Pedro Sampaio"
								},
								"bug_when": "2018-02-26 16:19:47 +0000",
								"thetext": "Catastrophic backtracking vulnerability was found in Python. Exploitation of a regular expression in pop3lib's apop() method although limited by 2048 chars, can lead to denial of service.\n\nUpstream issue:\n\nhttps://bugs.python.org/issue32981"
							},
							{
								"isprivate": "0",
								"commentid": "11445344",
								"comment_count": "2",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 01:49:52 +0000",
								"thetext": "External References:\n\nhttps://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final"
							},
							{
								"isprivate": "0",
								"commentid": "11445365",
								"comment_count": "3",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 02:01:13 +0000",
								"thetext": "Created python33 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563465]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563461]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563463]\n\n\nCreated python26 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563464]\n\n\nCreated python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563462]"
							},
							{
								"isprivate": "0",
								"commentid": "11445421",
								"comment_count": "4",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 02:23:51 +0000",
								"thetext": "Acknowledgments:\n\nName: the Python security response team"
							},
							{
								"isprivate": "0",
								"commentid": "12153742",
								"comment_count": "5",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2018-10-30 07:24:31 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2018:3041 https://access.redhat.com/errata/RHSA-2018:3041"
							},
							{
								"isprivate": "0",
								"commentid": "12763276",
								"comment_count": "12",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-05-22 12:01:46 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:1260 https://access.redhat.com/errata/RHSA-2019:1260"
							},
							{
								"isprivate": "0",
								"commentid": "13334621",
								"comment_count": "14",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-11-06 09:45:09 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n\nVia RHSA-2019:3725 https://access.redhat.com/errata/RHSA-2019:3725"
							},
							{
								"isprivate": "0",
								"commentid": "13761610",
								"comment_count": "17",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-01 08:33:55 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.5 Extended Update Support\n\nVia RHSA-2020:1268 https://access.redhat.com/errata/RHSA-2020:1268"
							},
							{
								"isprivate": "0",
								"commentid": "13780643",
								"comment_count": "18",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-07 09:33:18 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.4 Advanced Update Support\n  Red Hat Enterprise Linux 7.4 Telco Extended Update Support\n  Red Hat Enterprise Linux 7.4 Update Services for SAP Solutions\n\nVia RHSA-2020:1346 https://access.redhat.com/errata/RHSA-2020:1346"
							}
						]
					},
					{
						"bug_id": "1549192",
						"alias": "CVE-2018-1061",
						"creation_ts": "2018-02-26 16:20:03 +0000",
						"short_desc": "CVE-2018-1061 python: DOS via regular expression backtracking in difflib.IS_LINE_JUNK method in difflib",
						"delta_ts": "2021-02-17 00:46:38 +0000",
						"bug_status": "CLOSED",
						"resolution": "ERRATA",
						"keywords": "Security",
						"priority": "medium",
						"bug_severity": "medium",
						"depends_on": [
							"1563459",
							"1563461",
							"1563462",
							"1563463",
							"1563464",
							"1563465",
							"1563485",
							"1563486",
							"1563487",
							"1563488",
							"1563489",
							"1709355",
							"1709381",
							"1802759",
							"1802760",
							"1802761"
						],
						"blocked": [
							{
								"bug_id": "1549194",
								"error": "NotPermitted"
							}
						],
						"external_bugs": {
							"text": "RHSA-2020:1346",
							"name": "Red Hat Product Errata"
						},
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "11321786",
								"comment_count": "0",
								"who": {
									"text": "psampaio",
									"name": "Pedro Sampaio"
								},
								"bug_when": "2018-02-26 16:20:03 +0000",
								"thetext": "Catastrophic backtracking vulnerability was found in Python. Exploitation of a regular expression in difflib.IS_LINE_JUNK method in servers that use difflib can lead to denial of service.\n\nUpstream issue:\n\nhttps://bugs.python.org/issue32981"
							},
							{
								"isprivate": "0",
								"commentid": "11445336",
								"comment_count": "1",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 01:42:43 +0000",
								"thetext": "Created python3 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563462]\n\n\nCreated python26 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563464]\n\n\nCreated python33 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563465]\n\n\nCreated python34 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563463]\n\n\nCreated python35 tracking bugs for this issue:\n\nAffects: fedora-all [bug 1563461]"
							},
							{
								"isprivate": "0",
								"commentid": "11445356",
								"comment_count": "2",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 01:56:23 +0000",
								"thetext": "External References:\n\nhttps://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-5-final"
							},
							{
								"isprivate": "0",
								"commentid": "11445415",
								"comment_count": "4",
								"who": {
									"text": "huzaifas",
									"name": "Huzaifa S. Sidhpurwala"
								},
								"bug_when": "2018-04-04 02:22:31 +0000",
								"thetext": "Acknowledgments:\n\nName: the Python security response team"
							},
							{
								"isprivate": "0",
								"commentid": "12153743",
								"comment_count": "5",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2018-10-30 07:24:32 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7\n\nVia RHSA-2018:3041 https://access.redhat.com/errata/RHSA-2018:3041"
							},
							{
								"isprivate": "0",
								"commentid": "12763277",
								"comment_count": "6",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-05-22 12:01:49 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.4 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n\nVia RHSA-2019:1260 https://access.redhat.com/errata/RHSA-2019:1260"
							},
							{
								"isprivate": "0",
								"commentid": "13334622",
								"comment_count": "7",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2019-11-06 09:45:09 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Software Collections for Red Hat Enterprise Linux 7\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.5 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.6 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 7.7 EUS\n  Red Hat Software Collections for Red Hat Enterprise Linux 6\n\nVia RHSA-2019:3725 https://access.redhat.com/errata/RHSA-2019:3725"
							},
							{
								"isprivate": "0",
								"commentid": "13761609",
								"comment_count": "9",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-01 08:33:52 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.5 Extended Update Support\n\nVia RHSA-2020:1268 https://access.redhat.com/errata/RHSA-2020:1268"
							},
							{
								"isprivate": "0",
								"commentid": "13780645",
								"comment_count": "10",
								"who": {
									"text": "errata-xmlrpc",
									"name": "errata-xmlrpc"
								},
								"bug_when": "2020-04-07 09:33:25 +0000",
								"thetext": "This issue has been addressed in the following products:\n\n  Red Hat Enterprise Linux 7.4 Advanced Update Support\n  Red Hat Enterprise Linux 7.4 Telco Extended Update Support\n  Red Hat Enterprise Linux 7.4 Update Services for SAP Solutions\n\nVia RHSA-2020:1346 https://access.redhat.com/errata/RHSA-2020:1346"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11445327",
						"comment_count": "0",
						"who": {
							"text": "huzaifas",
							"name": "Huzaifa S. Sidhpurwala"
						},
						"bug_when": "2018-04-04 01:42:25 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "11445335",
						"comment_count": "1",
						"who": {
							"text": "huzaifas",
							"name": "Huzaifa S. Sidhpurwala"
						},
						"bug_when": "2018-04-04 01:42:35 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1549192,1563462\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "11445360",
						"comment_count": "2",
						"who": {
							"text": "huzaifas",
							"name": "Huzaifa S. Sidhpurwala"
						},
						"bug_when": "2018-04-04 02:01:06 +0000",
						"thetext": "Added new parent flaw bugs 1549191 (CVE-2018-1060) to this tracking bug."
					},
					{
						"isprivate": "0",
						"commentid": "11450347",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:30:29 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-7eae87ec86"
					},
					{
						"isprivate": "0",
						"commentid": "11450376",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:32:57 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11450388",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 09:33:27 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451932",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:50:48 +0000",
						"thetext": "python3-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11451953",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 15:56:00 +0000",
						"thetext": "python-pip-9.0.3-1.fc26 python3-3.6.5-1.fc26 python3-docs-3.6.5-1.fc26 has been submitted as an update to Fedora 26. https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11452032",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:05:00 +0000",
						"thetext": "python3-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11452075",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-05 16:14:04 +0000",
						"thetext": "python-pip-9.0.3-1.fc27 python3-3.6.5-1.fc27 python3-docs-3.6.5-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11453971",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 11:08:52 +0000",
						"thetext": "python3-3.6.5-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11455365",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 16:51:26 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-aa8de9d66a"
					},
					{
						"isprivate": "0",
						"commentid": "11455419",
						"comment_count": "12",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-06 17:16:37 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a042f795b2"
					},
					{
						"isprivate": "0",
						"commentid": "11461756",
						"comment_count": "13",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 18:34:20 +0000",
						"thetext": "python-pip-9.0.3-1.fc26, python3-3.6.5-1.fc26, python3-docs-3.6.5-1.fc26 has been pushed to the Fedora 26 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11461921",
						"comment_count": "14",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-04-09 19:08:46 +0000",
						"thetext": "python-pip-9.0.3-1.fc27, python3-3.6.5-1.fc27, python3-docs-3.6.5-1.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python3-3.6.5-1.fc28",
			"release_id": 21,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "i686"
					}
				],
				"ppc64": [
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64"
					}
				],
				"ppc64le": [
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					},
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python3-libs",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-devel",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-debuginfo",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-idle",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-tkinter",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-test",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-debugsource",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					},
					{
						"name": "python3-debug",
						"version": "3.6.5",
						"release": "1.fc28",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 759426,
			"text": "This update has been submitted for testing by cstratak. ",
			"timestamp": "2018-04-03 13:24:38",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 760540,
			"text": "This update has been pushed to testing.",
			"timestamp": "2018-04-04 18:37:54",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 760669,
			"karma": 1,
			"text": "Works",
			"timestamp": "2018-04-04 21:07:54",
			"update_id": 111639,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/20f7756718e08ef810fe23344dfdcafe17dfb277e2c27d5cbf81e35b66247795?s=24&d=retro",
				"email": "walter.pete@yandex.com",
				"groups": [
					{
						"name": "packager"
					},
					{
						"name": "provenpackager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					}
				],
				"id": 491,
				"name": "pwalter",
				"openid": "pwalter.id.fedoraproject.org"
			},
			"user_id": 491
		},
		{
			"id": 761012,
			"karma": 1,
			"text": "Works great!  LGTM!  =)",
			"timestamp": "2018-04-05 06:27:38",
			"update_id": 111639,
			"user": {
				"avatar": "https://seccdn.libravatar.org/avatar/28bacfa3be75032390ac2c7a34599aeb825c3b62b2c55ef64821d2fc023b56cb?s=24&d=retro",
				"email": "besser82.fpo@gmail.com",
				"groups": [
					{
						"name": "proventesters"
					},
					{
						"name": "packager"
					},
					{
						"name": "ipausers"
					},
					{
						"name": "fedora-contributor"
					},
					{
						"name": "signed_fpca"
					},
					{
						"name": "fedorabugs"
					},
					{
						"name": "ambassadors"
					},
					{
						"name": "designteam"
					},
					{
						"name": "shogun-ca"
					},
					{
						"name": "alt-gtk-de-sig"
					},
					{
						"name": "trust admins"
					}
				],
				"id": 206,
				"name": "besser82",
				"openid": "besser82.id.fedoraproject.org"
			},
			"user_id": 206
		},
		{
			"id": 761152,
			"text": "cstratak edited this update.",
			"timestamp": "2018-04-05 09:30:23",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 761271,
			"text": "This update has been submitted for batched by cstratak. ",
			"timestamp": "2018-04-05 11:54:25",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 761272,
			"text": "This update has been submitted for stable by cstratak. ",
			"timestamp": "2018-04-05 11:54:38",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 762009,
			"text": "This update has been pushed to stable.",
			"timestamp": "2018-04-06 11:10:05",
			"update_id": 111639,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"critpath": true,
	"date_modified": "2018-04-05 09:30:24",
	"date_pushed": "2018-04-06 11:07:50",
	"date_stable": "2018-04-06 11:07:50",
	"date_submitted": "2018-04-03 13:24:38",
	"date_testing": "2018-04-04 18:34:03",
	"karma": 2,
	"meets_testing_requirements": true,
	"notes": "Update to 3.6.5\n",
	"pushed": true,
	"release": {
		"branch": "f28",
		"candidate_tag": "f28-updates-candidate",
		"composed_by_bodhi": true,
		"dist_tag": "f28",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 28",
		"mail_template": "fedora_errata_template",
		"name": "F28",
		"override_tag": "f28-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f28-signing-pending",
		"pending_stable_tag": "f28-updates-pending",
		"pending_testing_tag": "f28-updates-testing-pending",
		"stable_tag": "f28-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f28-updates-testing",
		"version": "28"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "unspecified",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "passed",
	"title": "python3-3.6.5-1.fc28",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2018-7eae87ec86",
	"unstable_karma": -3,
	"updateid": "FEDORA-2018-7eae87ec86",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/af49eb5320c1c40d81a98d1fcdccc06c470c1458daab1a4f27be4cb170dbab3c?s=24&d=retro",
		"email": "cstratak@redhat.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "provenpackager"
			},
			{
				"name": "python-sig"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "modularity-wg"
			},
			{
				"name": "python-packagers-sig"
			}
		],
		"id": 2512,
		"name": "cstratak",
		"openid": "cstratak.id.fedoraproject.org"
	},
	"version_hash": "a0cfb80181d6276b321a5595baf279204c859041"
}
