{
	"alias": "FEDORA-2018-4f06058324",
	"autokarma": true,
	"bugs": [
		{
			"bug_id": 1615183,
			"title": "python-pycryptodomex-3.6.5x is available",
			"bugzilla": {
				"bug_id": "1615183",
				"creation_ts": "2018-08-13 00:26:39 +0000",
				"short_desc": "python-pycryptodomex-3.6.5x is available",
				"delta_ts": "2018-09-21 05:21:48 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "FutureFeature, Triaged",
				"priority": "unspecified",
				"bug_severity": "unspecified",
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11901695",
						"comment_count": "0",
						"who": {
							"text": "upstream-release-monitoring",
							"name": "Upstream Release Monitoring"
						},
						"bug_when": "2018-08-13 00:26:39 +0000",
						"thetext": "Latest upstream release: 3.6.5x\nCurrent version/release in rawhide: 3.6.4-1.fc29\nURL: http://www.pycryptodome.org/\n\nPlease consult the package updates policy before you issue an update to a stable branch: https://fedoraproject.org/wiki/Updates_Policy\n\nMore information about the service that created this bug can be found at: https://fedoraproject.org/wiki/Upstream_release_monitoring\n\nPlease keep in mind that with any upstream change, there may also be packaging changes that need to be made. Specifically, please remember that it is your responsibility to review the new version to ensure that the licensing is still correct and that no non-free or legally problematic items have been added upstream.\n\nBased on the information from anitya:  https://release-monitoring.org/project/16968/"
					},
					{
						"isprivate": "0",
						"commentid": "11960449",
						"comment_count": "1",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:38 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11960452",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:48 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a42eb4ac61"
					},
					{
						"isprivate": "0",
						"commentid": "11960454",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:57 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-8fd21e2a72"
					},
					{
						"isprivate": "0",
						"commentid": "11966820",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-29 19:03:56 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11967491",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-29 23:12:59 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11967998",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-30 04:23:06 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a42eb4ac61"
					},
					{
						"isprivate": "0",
						"commentid": "11968256",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-30 05:54:44 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-8fd21e2a72"
					},
					{
						"isprivate": "0",
						"commentid": "11996703",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-07 15:23:06 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11996970",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-07 16:15:14 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12038413",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-21 05:21:48 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		},
		{
			"bug_id": 1623060,
			"parent": true,
			"security": true,
			"title": "CVE-2018-15560 python-pycryptodomex: Integer overflow in he data_len variable in AESNI.c",
			"bugzilla": {
				"bug_id": "1623060",
				"alias": "CVE-2018-15560",
				"creation_ts": "2018-08-28 12:28:31 +0000",
				"short_desc": "CVE-2018-15560 python-pycryptodomex: Integer overflow in he data_len variable in AESNI.c",
				"delta_ts": "2019-09-29 14:57:29 +0000",
				"bug_status": "CLOSED",
				"resolution": "CURRENTRELEASE",
				"keywords": "Security",
				"priority": "low",
				"bug_severity": "low",
				"depends_on": [
					"1623062"
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11959920",
						"comment_count": "0",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-08-28 12:28:31 +0000",
						"thetext": "\nPyCryptodome before 3.6.6 has an integer overflow in the data_len variable in AESNI.c, related to the AESNI_encrypt and AESNI_decrypt functions, leading to the mishandling of messages shorter than 16 bytes.\n\nUpstream issue:\n\nhttps://github.com/Legrandin/pycryptodome/issues/198\n\nReferences:\n\nhttps://whitehatck01.blogspot.com/2018/08/integer-overflow-vulnerability-in.html"
					},
					{
						"isprivate": "0",
						"commentid": "11959930",
						"comment_count": "1",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-08-28 12:30:51 +0000",
						"thetext": "Created python-pycryptodomex tracking bugs for this issue:\n\nAffects: fedora-all [bug 1623062]"
					}
				]
			}
		},
		{
			"bug_id": 1623062,
			"security": true,
			"title": "CVE-2018-15560 python-pycryptodomex: Integer overflow in he data_len variable in AESNI.c [fedora-all]",
			"bugzilla": {
				"bug_id": "1623062",
				"creation_ts": "2018-08-28 12:30:46 +0000",
				"short_desc": "CVE-2018-15560 python-pycryptodomex: Integer overflow in he data_len variable in AESNI.c [fedora-all]",
				"delta_ts": "2018-09-21 05:21:46 +0000",
				"bug_status": "CLOSED",
				"resolution": "ERRATA",
				"keywords": "Security, SecurityTracking",
				"priority": "low",
				"bug_severity": "low",
				"blocked": [
					{
						"bug_id": "1623060",
						"alias": "CVE-2018-15560",
						"creation_ts": "2018-08-28 12:28:31 +0000",
						"short_desc": "CVE-2018-15560 python-pycryptodomex: Integer overflow in he data_len variable in AESNI.c",
						"delta_ts": "2019-09-29 14:57:29 +0000",
						"bug_status": "CLOSED",
						"resolution": "CURRENTRELEASE",
						"keywords": "Security",
						"priority": "low",
						"bug_severity": "low",
						"depends_on": [
							"1623062"
						],
						"long_desc": [
							{
								"isprivate": "0",
								"commentid": "11959920",
								"comment_count": "0",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-08-28 12:28:31 +0000",
								"thetext": "\nPyCryptodome before 3.6.6 has an integer overflow in the data_len variable in AESNI.c, related to the AESNI_encrypt and AESNI_decrypt functions, leading to the mishandling of messages shorter than 16 bytes.\n\nUpstream issue:\n\nhttps://github.com/Legrandin/pycryptodome/issues/198\n\nReferences:\n\nhttps://whitehatck01.blogspot.com/2018/08/integer-overflow-vulnerability-in.html"
							},
							{
								"isprivate": "0",
								"commentid": "11959930",
								"comment_count": "1",
								"who": {
									"text": "anemec",
									"name": "Andrej Nemec"
								},
								"bug_when": "2018-08-28 12:30:51 +0000",
								"thetext": "Created python-pycryptodomex tracking bugs for this issue:\n\nAffects: fedora-all [bug 1623062]"
							}
						]
					}
				],
				"long_desc": [
					{
						"isprivate": "0",
						"commentid": "11959927",
						"comment_count": "0",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-08-28 12:30:46 +0000",
						"thetext": "\nThis is an automatically created tracking bug!  It was created to ensure\nthat one or more security vulnerabilities are fixed in affected versions\nof fedora-all.\n\nFor comments that are specific to the vulnerability please use bugs filed\nagainst the \"Security Response\" product referenced in the \"Blocks\" field.\n\nFor more information see:\nhttp://fedoraproject.org/wiki/Security/TrackingBugs\n\nWhen submitting as an update, use the fedpkg template provided in the next\ncomment(s).  This will include the bug IDs of this tracking bug as well as\nthe relevant top-level CVE bugs.\n\nPlease also mention the CVE IDs being fixed in the RPM changelog and the\nfedpkg commit message.\n\nNOTE: this issue affects multiple supported versions of Fedora. While only\none tracking bug has been filed, please correct all affected versions at\nthe same time.  If you need to fix the versions independent of each other,\nyou may clone this bug as appropriate."
					},
					{
						"isprivate": "0",
						"commentid": "11959929",
						"comment_count": "1",
						"who": {
							"text": "anemec",
							"name": "Andrej Nemec"
						},
						"bug_when": "2018-08-28 12:30:49 +0000",
						"thetext": "Use the following template to for the 'fedpkg update' request to submit an\nupdate for this issue as it contains the top-level parent bug(s) as well as\nthis tracking bug.  This will ensure that all associated bugs get updated\nwhen new packages are pushed to stable.\n\n=====\n\n# bugfix, security, enhancement, newpackage (required)\ntype=security\n\n# testing, stable\nrequest=testing\n\n# Bug numbers: 1234,9876\nbugs=1623060,1623062\n\n# Description of your update\nnotes=Security fix for [PUT CVEs HERE]\n\n# Enable request automation based on the stable/unstable karma thresholds\nautokarma=True\nstable_karma=3\nunstable_karma=-3\n\n# Automatically close bugs when this marked as stable\nclose_bugs=True\n\n# Suggest that users restart after update\nsuggest_reboot=False\n\n======\n\nAdditionally, you may opt to use the bodhi web interface to submit updates:\n\nhttps://bodhi.fedoraproject.org/updates/new"
					},
					{
						"isprivate": "0",
						"commentid": "11960448",
						"comment_count": "2",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:36 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11960451",
						"comment_count": "3",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:46 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been submitted as an update to Fedora 27. https://bodhi.fedoraproject.org/updates/FEDORA-2018-a42eb4ac61"
					},
					{
						"isprivate": "0",
						"commentid": "11960453",
						"comment_count": "4",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-28 14:15:54 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been submitted as an update to Fedora 28. https://bodhi.fedoraproject.org/updates/FEDORA-2018-8fd21e2a72"
					},
					{
						"isprivate": "0",
						"commentid": "11966819",
						"comment_count": "5",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-29 19:03:53 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been submitted as an update to Fedora 29. https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11967489",
						"comment_count": "6",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-29 23:12:56 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been pushed to the Fedora 29 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324"
					},
					{
						"isprivate": "0",
						"commentid": "11967996",
						"comment_count": "7",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-30 04:23:04 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been pushed to the Fedora 27 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-a42eb4ac61"
					},
					{
						"isprivate": "0",
						"commentid": "11968254",
						"comment_count": "8",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-08-30 05:54:42 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been pushed to the Fedora 28 testing repository. If problems still persist, please make note of it in this bug report.\nSee https://fedoraproject.org/wiki/QA:Updates_Testing for\ninstructions on how to install test updates.\nYou can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2018-8fd21e2a72"
					},
					{
						"isprivate": "0",
						"commentid": "11996702",
						"comment_count": "9",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-07 15:22:58 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc27 has been pushed to the Fedora 27 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "11996969",
						"comment_count": "10",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-07 16:15:12 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc28 has been pushed to the Fedora 28 stable repository. If problems still persist, please make note of it in this bug report."
					},
					{
						"isprivate": "0",
						"commentid": "12038412",
						"comment_count": "11",
						"who": {
							"text": "updates",
							"name": "Fedora Update System"
						},
						"bug_when": "2018-09-21 05:21:46 +0000",
						"thetext": "python-pycryptodomex-3.6.6-1.fc29 has been pushed to the Fedora 29 stable repository. If problems still persist, please make note of it in this bug report."
					}
				]
			}
		}
	],
	"builds": [
		{
			"epoch": 0,
			"nvr": "python-pycryptodomex-3.6.6-1.fc29",
			"release_id": 23,
			"signed": true,
			"type": "rpm",
			"package": {
				"aarch64": [
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "aarch64"
					}
				],
				"armv7hl": [
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					},
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "armv7hl"
					}
				],
				"i686": [
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					},
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					},
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "i686"
					}
				],
				"ppc64le": [
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					},
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "ppc64le"
					}
				],
				"s390x": [
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					},
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					},
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "s390x"
					}
				],
				"src": [
					{
						"name": "python-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "src"
					}
				],
				"x86_64": [
					{
						"name": "python2-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python-pycryptodomex-debugsource",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-pycryptodomex",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python3-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					},
					{
						"name": "python2-pycryptodomex-debuginfo",
						"version": "3.6.6",
						"release": "1.fc29",
						"arch": "x86_64"
					}
				]
			}
		}
	],
	"close_bugs": true,
	"comments": [
		{
			"id": 827274,
			"text": "This update has been submitted for testing by melmorabity. ",
			"timestamp": "2018-08-28 14:15:29",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 827739,
			"text": "python-pycryptodomex-3.6.6-1.fc29 ejected from the push because u\"Cannot find relevant tag for python-pycryptodomex-3.6.6-1.fc29.  None of ['f29-updates-candidate', 'f29-updates-testing-pending'] are in [u'f22-updates-candidate', u'f21-updates-candidate', u'f25-updates-candidate', u'f24-updates-candidate', u'f23-updates-candidate', u'f28-updates-candidate', u'f27-updates-candidate', u'f26-updates-candidate', u'dist-6E-epel-testing-candidate', u'epel7-testing-candidate', u'dist-5E-epel-testing-candidate', u'f27-modular-updates-candidate', u'f28-modular-updates-candidate'].\"",
			"timestamp": "2018-08-29 17:51:15",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 827767,
			"text": "This update has been submitted for testing by mohanboddu. ",
			"timestamp": "2018-08-29 19:03:48",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 827875,
			"text": "This update has been pushed to testing.",
			"timestamp": "2018-08-29 23:15:38",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 830223,
			"text": "This update has reached 7 days in testing and can be pushed to stable now if the maintainer wishes",
			"timestamp": "2018-09-06 00:00:27",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 830610,
			"text": "This update has been submitted for batched by melmorabity. ",
			"timestamp": "2018-09-06 06:28:39",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 830611,
			"text": "This update has been submitted for stable by melmorabity. ",
			"timestamp": "2018-09-06 06:28:46",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		},
		{
			"id": 837197,
			"text": "This update has been pushed to stable.",
			"timestamp": "2018-09-21 05:35:17",
			"update_id": 121455,
			"user": {
				"avatar": "https://apps.fedoraproject.org/img/icons/bodhi-24.png",
				"id": 91,
				"name": "bodhi",
				"openid": "bodhi.id.fedoraproject.org"
			},
			"user_id": 91
		}
	],
	"content_type": "rpm",
	"date_pushed": "2018-09-21 05:19:39",
	"date_stable": "2018-09-21 05:19:39",
	"date_submitted": "2018-08-28 14:15:29",
	"date_testing": "2018-08-29 23:12:02",
	"meets_testing_requirements": true,
	"notes": "Security fix for CVE-2018-15560",
	"pushed": true,
	"release": {
		"branch": "f29",
		"candidate_tag": "f29-updates-candidate",
		"composed_by_bodhi": true,
		"create_automatic_updates": false,
		"dist_tag": "f29",
		"id_prefix": "FEDORA",
		"long_name": "Fedora 29",
		"mail_template": "fedora_errata_template",
		"name": "F29",
		"override_tag": "f29-override",
		"package_manager": "dnf",
		"pending_signing_tag": "f29-signing-pending",
		"pending_stable_tag": "f29-updates-pending",
		"pending_testing_tag": "f29-updates-testing-pending",
		"stable_tag": "f29-updates",
		"state": "archived",
		"testing_repository": "updates-testing",
		"testing_tag": "f29-updates-testing",
		"version": "29"
	},
	"require_bugs": true,
	"require_testcases": true,
	"severity": "high",
	"stable_karma": 3,
	"status": "stable",
	"suggest": "unspecified",
	"test_gating_status": "ignored",
	"title": "python-pycryptodomex-3.6.6-1.fc29",
	"type": "security",
	"url": "https://bodhi.fedoraproject.org/updates/FEDORA-2018-4f06058324",
	"unstable_karma": -3,
	"updateid": "FEDORA-2018-4f06058324",
	"user": {
		"avatar": "https://seccdn.libravatar.org/avatar/0e8fdd3427cb3c57b9ef13ad31e7086a27cf0da8f73f8a267813b16badd88c13?s=24&d=retro",
		"email": "pikachu.2014@gmail.com",
		"groups": [
			{
				"name": "packager"
			},
			{
				"name": "ipausers"
			},
			{
				"name": "fedora-contributor"
			},
			{
				"name": "signed_fpca"
			},
			{
				"name": "fedorabugs"
			},
			{
				"name": "gitmuffin"
			},
			{
				"name": "trust admins"
			}
		],
		"id": 592,
		"name": "melmorabity",
		"openid": "melmorabity.id.fedoraproject.org"
	},
	"version_hash": "d5332b5881f15b4607a16139c7bbaae5a489a049"
}
